# -*- coding: utf-8 -*-
"""Bai01_Cobb_Douglas_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13-jWqoiftVxATDQilXn_OxFRElQsUbEQ
"""

# ============================================================
# BÀI 1 — HÀM SẢN XUẤT COBB–DOUGLAS MỞ RỘNG VỚI AI VÀ SỐ HÓA
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Hiển thị bảng đẹp trong Colab
pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Trong giai đoạn 2020–2025, kinh tế Việt Nam có sự chuyển dịch
đáng chú ý theo hướng tăng trưởng dựa nhiều hơn vào khoa học
công nghệ, chuyển đổi số và đổi mới sáng tạo.

GDP Việt Nam tăng từ 8.044,4 nghìn tỷ VND năm 2020 lên
12.847,6 nghìn tỷ VND năm 2025. Đồng thời, tỷ trọng kinh tế số
trong GDP tăng từ khoảng 12,0% lên 19,5%.

Bài toán đặt ra là: nếu mô hình hóa nền kinh tế Việt Nam bằng
hàm sản xuất Cobb–Douglas mở rộng, có bổ sung các yếu tố
số hóa D, năng lực AI và vốn nhân lực số H, thì mô hình có
mô phỏng sát GDP thực tế không? Và yếu tố nào đóng góp lớn
nhất vào tăng trưởng GDP?
""")

# ============================================================
# 1. MÔ HÌNH TOÁN HỌC
# ============================================================

print("""
============================================================
1. MÔ HÌNH TOÁN HỌC
============================================================

Hàm sản xuất Cobb–Douglas mở rộng được viết dưới dạng:

Y_t = A_t × K_t^α × L_t^β × D_t^γ × AI_t^δ × H_t^θ

Trong đó:
- Y_t  : GDP, đơn vị nghìn tỷ VND
- A_t  : năng suất nhân tố tổng hợp, hay TFP
- K_t  : vốn vật chất
- L_t  : lao động
- D_t  : mức độ số hóa, đo bằng tỷ trọng kinh tế số/GDP
- AI_t : năng lực AI, đại diện bởi số doanh nghiệp công nghệ số
- H_t  : vốn nhân lực số, đại diện bởi tỷ lệ lao động qua đào tạo

Bộ hệ số sử dụng:
α = 0,33
β = 0,42
γ = 0,10
δ = 0,08
θ = 0,07

Tổng các hệ số bằng 1, tức mô hình giả định lợi suất không đổi
theo quy mô.

Để phân rã tăng trưởng, lấy logarit và sai phân:

ΔlnY = ΔlnA + αΔlnK + βΔlnL + γΔlnD + δΔlnAI + θΔlnH
""")

# ============================================================
# 2. ĐỌC VÀ KHAI BÁO DỮ LIỆU
# ============================================================

print("""
============================================================
2. DỮ LIỆU SỬ DỤNG
============================================================

Dữ liệu sử dụng cho giai đoạn 2020–2025, bao gồm GDP,
vốn vật chất, lao động, tỷ trọng kinh tế số, năng lực AI và
vốn nhân lực số.

GDP được đọc từ file vietnam_macro_2020_2025.csv.
Các biến K, L, D, AI, H được khai báo theo bảng dữ liệu đề bài.
""")

# Nếu dùng Colab, upload file vietnam_macro_2020_2025.csv trước
try:
    df = pd.read_csv("vietnam_macro_2020_2025.csv")
except FileNotFoundError:
    print("Không tìm thấy file CSV. Sử dụng dữ liệu GDP mặc định theo đề bài.")
    df = pd.DataFrame({
        "year": [2020, 2021, 2022, 2023, 2024, 2025],
        "GDP_trillion_VND": [8044.4, 8487.5, 9513.3, 10221.8, 11511.9, 12847.6]
    })

display(df.head())

year = np.array([2020, 2021, 2022, 2023, 2024, 2025])

Y = df["GDP_trillion_VND"].values.astype(float)

K = np.array([16500, 17800, 19600, 21300, 23500, 25900], dtype=float)
L = np.array([53.6, 50.5, 51.7, 52.4, 52.9, 53.4], dtype=float)
D = np.array([12.0, 12.7, 14.3, 16.5, 18.3, 19.5], dtype=float)
AI = np.array([55.6, 60.2, 65.4, 67.0, 73.8, 80.1], dtype=float)
H = np.array([24.1, 26.1, 26.2, 27.0, 28.4, 29.2], dtype=float)

alpha = 0.33
beta = 0.42
gamma = 0.10
delta = 0.08
theta = 0.07

print("Tổng hệ số =", alpha + beta + gamma + delta + theta)

input_df = pd.DataFrame({
    "Năm": year,
    "GDP_Y": Y,
    "K": K,
    "L": L,
    "D": D,
    "AI": AI,
    "H": H
})

display(input_df)

# ============================================================
# 3. CÂU 1.4.1 — TÍNH TFP A_t
# ============================================================

print("""
============================================================
3. CÂU 1.4.1 — ƯỚC LƯỢNG TFP A_t
============================================================

Từ hàm sản xuất Cobb–Douglas mở rộng, TFP được tính ngược lại:

A_t = Y_t / (K_t^α × L_t^β × D_t^γ × AI_t^δ × H_t^θ)
""")

A = Y / (
    (K ** alpha)
    * (L ** beta)
    * (D ** gamma)
    * (AI ** delta)
    * (H ** theta)
)

tfp_df = pd.DataFrame({
    "Năm": year,
    "GDP_Y": Y,
    "TFP_A_t": A
})

display(tfp_df.round(4))

plt.figure(figsize=(10,5))
plt.plot(year, A, marker="o", linewidth=3)
plt.title("Xu hướng năng suất nhân tố tổng hợp TFP A_t, 2020–2025")
plt.xlabel("Năm")
plt.ylabel("TFP A_t")
plt.grid(True)
plt.show()

print(f"""
Nhận xét:
TFP tăng từ {A[0]:.2f} năm 2020 lên {A[-1]:.2f} năm 2025.
Điều này cho thấy chất lượng tăng trưởng của nền kinh tế có xu hướng
cải thiện, phản ánh hiệu quả sử dụng nguồn lực, chuyển đổi số,
đổi mới công nghệ và năng lực quản trị tốt hơn.
""")

# ============================================================
# 4. CÂU 1.4.2 — GDP DỰ BÁO VÀ MAPE
# ============================================================

print("""
============================================================
4. CÂU 1.4.2 — SO SÁNH GDP THỰC TẾ VÀ GDP DỰ BÁO
============================================================

Lấy A_t bằng giá trị trung bình của TFP giai đoạn 2020–2025,
sau đó tính GDP dự báo theo hàm Cobb–Douglas mở rộng.
""")

A_mean = A.mean()

Y_hat = A_mean * (
    (K ** alpha)
    * (L ** beta)
    * (D ** gamma)
    * (AI ** delta)
    * (H ** theta)
)

mape = np.mean(np.abs((Y - Y_hat) / Y)) * 100

forecast_fit_df = pd.DataFrame({
    "Năm": year,
    "GDP thực tế": Y,
    "GDP dự báo": Y_hat,
    "Sai số": Y - Y_hat,
    "Sai số tuyệt đối (%)": np.abs((Y - Y_hat) / Y) * 100
})

display(forecast_fit_df.round(3))

print("A trung bình =", round(A_mean, 4))
print("MAPE =", round(mape, 3), "%")

plt.figure(figsize=(10,5))
plt.plot(year, Y, marker="o", linewidth=3, label="GDP thực tế")
plt.plot(year, Y_hat, marker="s", linewidth=3, linestyle="--", label="GDP dự báo")
plt.title("So sánh GDP thực tế và GDP dự báo bằng Cobb–Douglas mở rộng")
plt.xlabel("Năm")
plt.ylabel("GDP, nghìn tỷ VND")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,5))
plt.bar(year, forecast_fit_df["Sai số tuyệt đối (%)"])
plt.title("Sai số tuyệt đối phần trăm của mô hình")
plt.xlabel("Năm")
plt.ylabel("Absolute Percentage Error (%)")
plt.grid(axis="y")
plt.show()

print(f"""
Nhận xét:
MAPE của mô hình là {mape:.2f}%. Đây là mức sai số tương đối chấp nhận được
đối với một mô hình kinh tế vĩ mô giản lược.

Mô hình mô phỏng khá tốt xu hướng GDP thực tế, nhưng sai số vẫn tồn tại do
mô hình chưa đưa vào các yếu tố ngoại sinh như COVID-19, biến động FDI,
xuất nhập khẩu, lạm phát, chính sách tài khóa và tiền tệ.
""")

# ============================================================
# 5. CÂU 1.4.3 — PHÂN RÃ TĂNG TRƯỞNG
# ============================================================

print("""
============================================================
5. CÂU 1.4.3 — PHÂN RÃ TĂNG TRƯỞNG GDP
============================================================

Sử dụng phương trình:

ΔlnY = ΔlnA + αΔlnK + βΔlnL + γΔlnD + δΔlnAI + θΔlnH

để phân rã tăng trưởng GDP thành phần đóng góp của:
TFP, vốn K, lao động L, số hóa D, AI và nhân lực số H.
""")

dlnY = np.diff(np.log(Y))
dlnA = np.diff(np.log(A))
dlnK = np.diff(np.log(K))
dlnL = np.diff(np.log(L))
dlnD = np.diff(np.log(D))
dlnAI = np.diff(np.log(AI))
dlnH = np.diff(np.log(H))

contrib_A = dlnA
contrib_K = alpha * dlnK
contrib_L = beta * dlnL
contrib_D = gamma * dlnD
contrib_AI = delta * dlnAI
contrib_H = theta * dlnH

growth_df = pd.DataFrame({
    "Giai đoạn": [f"{year[i]}-{year[i+1]}" for i in range(len(year)-1)],
    "Tăng trưởng GDP": dlnY,
    "Đóng góp TFP": contrib_A,
    "Đóng góp K": contrib_K,
    "Đóng góp L": contrib_L,
    "Đóng góp D": contrib_D,
    "Đóng góp AI": contrib_AI,
    "Đóng góp H": contrib_H,
    "Tổng đóng góp": contrib_A + contrib_K + contrib_L + contrib_D + contrib_AI + contrib_H
})

display(growth_df.round(4))

avg_contrib = pd.Series({
    "TFP": contrib_A.mean(),
    "K": contrib_K.mean(),
    "L": contrib_L.mean(),
    "D": contrib_D.mean(),
    "AI": contrib_AI.mean(),
    "H": contrib_H.mean()
})

avg_growth = dlnY.mean()
share_contrib = avg_contrib / avg_growth * 100

contrib_summary = pd.DataFrame({
    "Yếu tố": avg_contrib.index,
    "Đóng góp bình quân": avg_contrib.values,
    "Tỷ trọng trong tăng trưởng (%)": share_contrib.values
})

display(contrib_summary.round(3))

plt.figure(figsize=(10,5))
plt.bar(contrib_summary["Yếu tố"], contrib_summary["Tỷ trọng trong tăng trưởng (%)"])
plt.title("Tỷ trọng đóng góp vào tăng trưởng GDP bình quân, 2020–2025")
plt.ylabel("Tỷ trọng đóng góp (%)")
plt.grid(axis="y")
plt.show()

plot_growth = growth_df.set_index("Giai đoạn")[
    ["Đóng góp TFP", "Đóng góp K", "Đóng góp L", "Đóng góp D", "Đóng góp AI", "Đóng góp H"]
] * 100

plot_growth.plot(kind="bar", stacked=True, figsize=(12,6))
plt.title("Phân rã tăng trưởng GDP theo từng giai đoạn")
plt.ylabel("Đóng góp vào tăng trưởng log GDP (%)")
plt.xlabel("Giai đoạn")
plt.grid(axis="y")
plt.show()

largest_new_factor = share_contrib[["D", "AI", "H"]].idxmax()

print(f"""
Nhận xét:
Trong giai đoạn 2020–2025, yếu tố đóng góp lớn nhất vào tăng trưởng GDP
là TFP, chiếm khoảng {share_contrib["TFP"]:.2f}% tổng tăng trưởng bình quân.

Vốn vật chất K đóng góp khoảng {share_contrib["K"]:.2f}%, cho thấy nền kinh tế
Việt Nam vẫn phụ thuộc đáng kể vào đầu tư và mở rộng năng lực sản xuất.

Trong nhóm yếu tố mới D, AI và H, yếu tố đóng góp lớn nhất là {largest_new_factor}.
Điều này phản ánh vai trò ngày càng rõ của kinh tế số, năng lực công nghệ
và nhân lực số trong mô hình tăng trưởng mới.
""")

# ============================================================
# 6. BIỂU ĐỒ MỞ RỘNG — CHỈ SỐ HÓA 2020 = 100
# ============================================================

print("""
============================================================
6. BIỂU ĐỒ MỞ RỘNG — CHỈ SỐ HÓA CÁC BIẾN, 2020 = 100
============================================================

Biểu đồ này giúp so sánh tốc độ tăng tương đối của GDP, K, D, AI, H và TFP.
""")

index_df = pd.DataFrame({
    "Năm": year,
    "GDP": Y / Y[0] * 100,
    "K": K / K[0] * 100,
    "L": L / L[0] * 100,
    "D": D / D[0] * 100,
    "AI": AI / AI[0] * 100,
    "H": H / H[0] * 100,
    "TFP": A / A[0] * 100
})

display(index_df.round(2))

plt.figure(figsize=(12,6))
for col in ["GDP", "K", "D", "AI", "H", "TFP"]:
    plt.plot(index_df["Năm"], index_df[col], marker="o", linewidth=2, label=col)

plt.title("Diễn biến các biến chính, chỉ số 2020 = 100")
plt.xlabel("Năm")
plt.ylabel("Chỉ số")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# 7. CÂU 1.4.4 — KỊCH BẢN DỰ BÁO GDP ĐẾN 2030
# ============================================================

print("""
============================================================
7. CÂU 1.4.4 — KỊCH BẢN DỰ BÁO GDP VIỆT NAM ĐẾN 2030
============================================================

Giả định kịch bản:
- D đạt 30% GDP vào năm 2030
- AI đạt 100 nghìn doanh nghiệp số
- H đạt 35%
- K tăng 6%/năm
- L tăng 6%/năm
- TFP tăng 1,2%/năm
""")

years_forecast = np.arange(2026, 2031)
forecast_rows = []

for t, yr in enumerate(years_forecast, start=1):
    K_t = K[-1] * ((1 + 0.06) ** t)
    L_t = L[-1] * ((1 + 0.06) ** t)
    D_t = D[-1] + (30 - D[-1]) * t / 5
    AI_t = AI[-1] + (100 - AI[-1]) * t / 5
    H_t = H[-1] + (35 - H[-1]) * t / 5
    A_t = A[-1] * ((1 + 0.012) ** t)

    Y_t = A_t * (
        (K_t ** alpha)
        * (L_t ** beta)
        * (D_t ** gamma)
        * (AI_t ** delta)
        * (H_t ** theta)
    )

    forecast_rows.append({
        "Năm": yr,
        "GDP dự báo": Y_t,
        "K": K_t,
        "L": L_t,
        "D": D_t,
        "AI": AI_t,
        "H": H_t,
        "TFP": A_t
    })

forecast_df = pd.DataFrame(forecast_rows)
display(forecast_df.round(2))

Y_2030 = forecast_df.loc[forecast_df["Năm"] == 2030, "GDP dự báo"].values[0]

print(f"GDP dự báo năm 2030 = {Y_2030:,.2f} nghìn tỷ VND")

plt.figure(figsize=(12,6))
plt.plot(year, Y, marker="o", linewidth=3, label="GDP thực tế 2020–2025")
plt.plot(forecast_df["Năm"], forecast_df["GDP dự báo"], marker="s", linewidth=3, linestyle="--", label="GDP dự báo 2026–2030")
plt.title("Dự báo GDP Việt Nam đến 2030 theo Cobb–Douglas mở rộng")
plt.xlabel("Năm")
plt.ylabel("GDP, nghìn tỷ VND")
plt.legend()
plt.grid(True)
plt.show()

print(f"""
Nhận xét:
Theo kịch bản mô phỏng, GDP Việt Nam năm 2030 có thể đạt khoảng
{Y_2030:,.2f} nghìn tỷ VND.

Kịch bản này cho thấy mục tiêu kinh tế số đạt 30% GDP vào năm 2030
có thể khả thi nếu Việt Nam duy trì được tăng trưởng vốn, lao động,
TFP và đồng thời mở rộng năng lực AI cũng như vốn nhân lực số.
""")

# ============================================================
# 8. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
8. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

tfp_trend = "tăng" if A[-1] > A[0] else "giảm"

print(f"""
1. Xu hướng TFP

TFP của Việt Nam có xu hướng {tfp_trend} trong giai đoạn 2020–2025.
Điều này cho thấy chất lượng tăng trưởng được cải thiện. Tăng trưởng
không chỉ đến từ mở rộng vốn đầu tư và lao động, mà còn từ hiệu quả
sử dụng nguồn lực, công nghệ, chuyển đổi số và đổi mới sáng tạo.

2. Yếu tố mới đóng góp lớn nhất

Trong nhóm các yếu tố mới gồm số hóa D, năng lực AI và vốn nhân lực số H,
yếu tố đóng góp lớn nhất là {largest_new_factor}.

Nếu yếu tố D đứng đầu, điều đó cho thấy kinh tế số và chuyển đổi số đang
tạo tác động rõ ràng nhất tới tăng trưởng. Nếu AI hoặc H tăng lên trong
các kịch bản sau, điều đó phản ánh vai trò dài hạn của công nghệ và con người.

3. Khả năng đạt mục tiêu 30% kinh tế số/GDP vào năm 2030

Mục tiêu này có thể khả thi, nhưng không thể chỉ dựa vào việc tăng tỷ trọng
kinh tế số trên danh nghĩa. Cần có các điều kiện đi kèm:
- đầu tư hạ tầng số;
- phát triển dữ liệu và năng lực AI;
- đào tạo nhân lực số;
- nâng cao khả năng hấp thụ công nghệ của doanh nghiệp;
- bảo đảm an ninh dữ liệu;
- giảm bất bình đẳng số giữa các vùng.

4. Hàm ý chính sách

Kết quả mô hình nhấn mạnh rằng Việt Nam cần chuyển từ tăng trưởng dựa nhiều
vào vốn và lao động sang tăng trưởng dựa trên năng suất, công nghệ và đổi mới
sáng tạo. Đầu tư vào hạ tầng số, AI và nhân lực số cần được xem là nhóm chính
sách trung tâm trong chiến lược phát triển kinh tế giai đoạn tới.
""")

# ============================================================
# 9. KẾT LUẬN
# ============================================================

print("""
============================================================
9. KẾT LUẬN
============================================================

Bài 1 cho thấy mô hình Cobb–Douglas mở rộng là công cụ hữu ích để
phân tích tăng trưởng kinh tế Việt Nam trong bối cảnh chuyển đổi số
và AI.

Kết quả thực nghiệm cho thấy TFP tăng trong giai đoạn 2020–2025,
phản ánh sự cải thiện về chất lượng tăng trưởng. Mô hình có mức MAPE
tương đối chấp nhận được, cho thấy khả năng mô phỏng xu hướng GDP
thực tế.

Phân rã tăng trưởng cho thấy TFP và vốn vật chất vẫn là hai động lực
quan trọng. Trong nhóm yếu tố mới, số hóa D, AI và nhân lực số H đều
có vai trò nhất định, trong đó số hóa D là yếu tố nổi bật nhất trong
giai đoạn quan sát.

Dự báo đến năm 2030 cho thấy GDP Việt Nam có thể tiếp tục tăng mạnh
nếu mục tiêu kinh tế số 30% GDP được hiện thực hóa, đồng thời Việt Nam
duy trì tăng trưởng vốn, lao động, TFP và mở rộng năng lực AI, nhân lực số.
""")

