# -*- coding: utf-8 -*-
"""Bai02_LP_PhanBoNganSachSo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wwM3X243A8JQqqOFuPjNkIFjyBdEVhL
"""

# ============================================================
# BÀI 2 — PHÂN BỔ NGÂN SÁCH ĐƠN GIẢN THEO 4 HẠNG MỤC ĐẦU TƯ SỐ
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import linprog

# Nếu Colab chưa có PuLP thì cài
try:
    import pulp
except ModuleNotFoundError:
    !pip install pulp
    import pulp

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Theo Chương trình Chuyển đổi số quốc gia, Việt Nam đặt mục tiêu
kinh tế số đạt khoảng 20% GDP vào năm 2025.

Giả sử Chính phủ có 100.000 tỷ VND ngân sách trung ương cho năm 2026,
dành cho 4 hạng mục đầu tư số:

x1: Hạ tầng số
x2: AI và dữ liệu
x3: Nhân lực số
x4: R&D công nghệ

Mục tiêu là phân bổ ngân sách sao cho tối đa hóa mức tăng GDP kỳ vọng,
đồng thời vẫn bảo đảm các ràng buộc tối thiểu cho từng hạng mục và tỷ lệ
đầu tư vào công nghệ chiến lược.
""")

# ============================================================
# 1. MÔ HÌNH TOÁN HỌC
# ============================================================

print("""
============================================================
1. MÔ HÌNH TOÁN HỌC
============================================================

Biến quyết định:
x1 = đầu tư hạ tầng số
x2 = đầu tư AI và dữ liệu
x3 = đầu tư nhân lực số
x4 = đầu tư R&D công nghệ

Đơn vị: nghìn tỷ VND.

Hàm mục tiêu:

Max Z = 0.85*x1 + 1.20*x2 + 0.95*x3 + 1.35*x4

Các ràng buộc:

1) x1 + x2 + x3 + x4 <= 100

2) x1 >= 25

3) x2 >= 15

4) x3 >= 20

5) x4 >= 10

6) x2 + x4 >= 0.35*(x1 + x2 + x3 + x4)

7) x1, x2, x3, x4 >= 0

Trong đó, ràng buộc 6 yêu cầu tỷ trọng đầu tư cho công nghệ chiến lược
AI + R&D đạt ít nhất 35% tổng ngân sách.
""")

# ============================================================
# 2. KHAI BÁO DỮ LIỆU
# ============================================================

print("""
============================================================
2. DỮ LIỆU ĐẦU VÀO
============================================================
""")

items = ["Hạ tầng số", "AI và dữ liệu", "Nhân lực số", "R&D công nghệ"]
variables = ["x1", "x2", "x3", "x4"]

coef = np.array([0.85, 1.20, 0.95, 1.35])
min_invest = np.array([25, 15, 20, 10])
budget = 100

input_df = pd.DataFrame({
    "Biến": variables,
    "Hạng mục": items,
    "Hệ số GDP kỳ vọng": coef,
    "Mức đầu tư tối thiểu": min_invest
})

display(input_df)

print("""
Diễn giải:
- R&D có hệ số tác động cao nhất là 1.35.
- AI và dữ liệu có hệ số 1.20.
- Nhân lực số có hệ số 0.95.
- Hạ tầng số có hệ số 0.85.

Do đó, nếu chỉ xét hiệu quả biên, mô hình có xu hướng phân bổ phần ngân sách
còn lại nhiều hơn vào R&D và AI. Tuy nhiên, các ràng buộc tối thiểu giúp đảm bảo
không hạng mục nào bị bỏ qua.
""")

# ============================================================
# 3. CÂU 2.4.1 — GIẢI BẰNG SCIPY.OPTIMIZE.LINPROG
# ============================================================

print("""
============================================================
3. CÂU 2.4.1 — GIẢI BÀI TOÁN BẰNG SCIPY LINPROG
============================================================

Vì scipy.optimize.linprog giải bài toán tối thiểu hóa, ta đổi:

Max Z thành Min -Z.
""")

# Tối đa hóa Z = - tối thiểu hóa (-Z)
c = [-0.85, -1.20, -0.95, -1.35]

# Ràng buộc dạng A_ub x <= b_ub
A_ub = [
    [1, 1, 1, 1],             # tổng ngân sách <= 100
    [-1, 0, 0, 0],            # x1 >= 25  -> -x1 <= -25
    [0, -1, 0, 0],            # x2 >= 15
    [0, 0, -1, 0],            # x3 >= 20
    [0, 0, 0, -1],            # x4 >= 10
    [0.35, -0.65, 0.35, -0.65] # x2+x4 >= 0.35 total
]

b_ub = [100, -25, -15, -20, -10, 0]

res = linprog(
    c,
    A_ub=A_ub,
    b_ub=b_ub,
    bounds=[(0, None)] * 4,
    method="highs"
)

print("Trạng thái nghiệm:", res.message)

x_scipy = res.x
z_scipy = -res.fun

scipy_result_df = pd.DataFrame({
    "Biến": variables,
    "Hạng mục": items,
    "Phân bổ tối ưu": x_scipy,
    "Hệ số GDP": coef,
    "Đóng góp GDP kỳ vọng": coef * x_scipy
})

display(scipy_result_df.round(4))

print(f"Giá trị tối ưu Z* theo scipy = {z_scipy:.4f} nghìn tỷ VND")

# Biểu đồ phân bổ ngân sách
plt.figure(figsize=(10,5))
plt.bar(items, x_scipy)
plt.title("Phân bổ ngân sách tối ưu theo scipy.optimize.linprog")
plt.ylabel("Ngân sách phân bổ, nghìn tỷ VND")
plt.xticks(rotation=20)
plt.grid(axis="y")
plt.show()

# Biểu đồ đóng góp GDP kỳ vọng
plt.figure(figsize=(10,5))
plt.bar(items, coef * x_scipy)
plt.title("Đóng góp GDP kỳ vọng theo từng hạng mục")
plt.ylabel("GDP gain kỳ vọng, nghìn tỷ VND")
plt.xticks(rotation=20)
plt.grid(axis="y")
plt.show()

# ============================================================
# 4. CÂU 2.4.2 — GIẢI LẠI BẰNG PuLP VÀ SHADOW PRICE
# ============================================================

print("""
============================================================
4. CÂU 2.4.2 — GIẢI BẰNG PuLP VÀ GIÁ ĐỐI NGẪU
============================================================

PuLP cho phép đặt tên từng ràng buộc và lấy shadow price thông qua thuộc tính .pi,
nếu solver CBC trả về thông tin đối ngẫu cho bài toán LP.
""")

model = pulp.LpProblem("Digital_Budget_Allocation", pulp.LpMaximize)

x1 = pulp.LpVariable("x1_Ha_tang_so", lowBound=0)
x2 = pulp.LpVariable("x2_AI_du_lieu", lowBound=0)
x3 = pulp.LpVariable("x3_Nhan_luc_so", lowBound=0)
x4 = pulp.LpVariable("x4_RD_cong_nghe", lowBound=0)

# Objective
model += 0.85*x1 + 1.20*x2 + 0.95*x3 + 1.35*x4, "GDP_gain"

# Constraints
model += x1 + x2 + x3 + x4 <= 100, "Ngan_sach_tong"
model += x1 >= 25, "San_ha_tang_so"
model += x2 >= 15, "San_AI_du_lieu"
model += x3 >= 20, "San_nhan_luc_so"
model += x4 >= 10, "San_RD"
model += x2 + x4 >= 0.35*(x1 + x2 + x3 + x4), "Ty_trong_cong_nghe_chien_luoc"

solver = pulp.PULP_CBC_CMD(msg=False)
model.solve(solver)

x_pulp = np.array([x1.value(), x2.value(), x3.value(), x4.value()])
z_pulp = pulp.value(model.objective)

pulp_result_df = pd.DataFrame({
    "Biến": variables,
    "Hạng mục": items,
    "Phân bổ tối ưu": x_pulp,
    "Hệ số GDP": coef,
    "Đóng góp GDP kỳ vọng": coef * x_pulp
})

display(pulp_result_df.round(4))

print(f"Giá trị tối ưu Z* theo PuLP = {z_pulp:.4f} nghìn tỷ VND")

# Shadow price
shadow_rows = []

for name, constraint in model.constraints.items():
    shadow_rows.append({
        "Ràng buộc": name,
        "Shadow price": constraint.pi,
        "Slack": constraint.slack
    })

shadow_df = pd.DataFrame(shadow_rows)

print("Bảng giá đối ngẫu và slack của từng ràng buộc:")
display(shadow_df.round(4))

budget_shadow = shadow_df.loc[
    shadow_df["Ràng buộc"] == "Ngan_sach_tong",
    "Shadow price"
].values[0]

print(f"""
Diễn giải shadow price của ràng buộc ngân sách tổng:
Shadow price của ngân sách tổng là {budget_shadow:.4f}.

Nếu ràng buộc ngân sách tổng đang binding, shadow price cho biết khi ngân sách
tăng thêm 1 nghìn tỷ VND, giá trị GDP gain tối ưu có thể tăng thêm khoảng
{budget_shadow:.4f} nghìn tỷ VND, trong phạm vi mà cấu trúc nghiệm tối ưu
chưa thay đổi.
""")

# ============================================================
# 5. CÂU 2.4.3 — PHÂN TÍCH ĐỘ NHẠY THEO NGÂN SÁCH
# ============================================================

print("""
============================================================
5. CÂU 2.4.3 — PHÂN TÍCH ĐỘ NHẠY THEO NGÂN SÁCH
============================================================

Thử tăng ngân sách tổng từ 100 lên 120 và 140 nghìn tỷ VND.
Quan sát Z*(B) thay đổi như thế nào.
""")

def solve_with_budget(B, min_x3=20):
    c = [-0.85, -1.20, -0.95, -1.35]

    A_ub = [
        [1, 1, 1, 1],
        [-1, 0, 0, 0],
        [0, -1, 0, 0],
        [0, 0, -1, 0],
        [0, 0, 0, -1],
        [0.35, -0.65, 0.35, -0.65]
    ]

    b_ub = [B, -25, -15, -min_x3, -10, 0]

    res = linprog(
        c,
        A_ub=A_ub,
        b_ub=b_ub,
        bounds=[(0, None)] * 4,
        method="highs"
    )

    if not res.success:
        return None, None

    return res.x, -res.fun


budgets = [100, 120, 140]
sensitivity_rows = []

for B in budgets:
    x_B, z_B = solve_with_budget(B)
    sensitivity_rows.append({
        "Ngân sách": B,
        "x1_Hạ tầng": x_B[0],
        "x2_AI": x_B[1],
        "x3_Nhân lực": x_B[2],
        "x4_R&D": x_B[3],
        "Z*": z_B
    })

sensitivity_df = pd.DataFrame(sensitivity_rows)

display(sensitivity_df.round(4))

plt.figure(figsize=(9,5))
plt.plot(sensitivity_df["Ngân sách"], sensitivity_df["Z*"], marker="o", linewidth=3)
plt.title("Đường cong Z*(B) khi ngân sách thay đổi")
plt.xlabel("Ngân sách tổng, nghìn tỷ VND")
plt.ylabel("GDP gain tối ưu Z*")
plt.grid(True)
plt.show()

print("""
Nhận xét:
Khi ngân sách tổng tăng, giá trị tối ưu Z* cũng tăng. Điều này là hợp lý vì
mô hình có thêm nguồn lực để phân bổ vào các hạng mục có hiệu quả biên cao.

Nếu nghiệm tối ưu tiếp tục ưu tiên R&D hoặc AI cho phần ngân sách tăng thêm,
đường Z*(B) sẽ có xu hướng tăng gần tuyến tính theo hệ số tác động biên
của hạng mục được phân bổ thêm.
""")

# ============================================================
# 6. CÂU 2.4.4 — ƯU TIÊN NHÂN LỰC SỐ x3 >= 30
# ============================================================

print("""
============================================================
6. CÂU 2.4.4 — KỊCH BẢN ƯU TIÊN NHÂN LỰC SỐ
============================================================

Giả sử Chính phủ muốn ưu tiên nhân lực số do thiếu hụt kỹ sư AI,
ràng buộc mới là x3 >= 30 thay vì x3 >= 20.
""")

x_human30, z_human30 = solve_with_budget(100, min_x3=30)

if x_human30 is None:
    print("Bài toán không khả thi khi thêm ràng buộc x3 >= 30.")
else:
    human30_df = pd.DataFrame({
        "Biến": variables,
        "Hạng mục": items,
        "Phân bổ tối ưu khi x3 >= 30": x_human30,
        "Hệ số GDP": coef,
        "Đóng góp GDP kỳ vọng": coef * x_human30
    })

    display(human30_df.round(4))

    print(f"Z* ban đầu = {z_scipy:.4f}")
    print(f"Z* khi x3 >= 30 = {z_human30:.4f}")
    print(f"Mức thay đổi Z* = {z_human30 - z_scipy:.4f}")

    compare_df = pd.DataFrame({
        "Hạng mục": items,
        "Phân bổ gốc": x_scipy,
        "Phân bổ khi x3 >= 30": x_human30
    })

    compare_df.set_index("Hạng mục").plot(kind="bar", figsize=(10,5))
    plt.title("So sánh phân bổ ngân sách trước và sau khi tăng sàn nhân lực số")
    plt.ylabel("Ngân sách, nghìn tỷ VND")
    plt.grid(axis="y")
    plt.show()

    print("""
Nhận xét:
Khi tăng sàn nhân lực số từ 20 lên 30, bài toán vẫn có thể khả thi nếu tổng
ngân sách đủ đáp ứng các mức tối thiểu. Tuy nhiên, vì nhân lực số có hệ số GDP
0.95 thấp hơn R&D 1.35 và AI 1.20, việc buộc tăng đầu tư vào nhân lực số có thể
làm giảm Z* so với phương án tối ưu ban đầu.

Dù vậy, về mặt chính sách, ràng buộc này có thể hợp lý nếu Chính phủ coi nhân lực
số là điều kiện nền tảng để triển khai AI và chuyển đổi số trong dài hạn.
""")

# ============================================================
# 7. KIỂM TRA RÀNG BUỘC VÀ TỶ TRỌNG
# ============================================================

print("""
============================================================
7. KIỂM TRA RÀNG BUỘC VÀ TỶ TRỌNG ĐẦU TƯ
============================================================
""")

total_budget_used = x_scipy.sum()
strategic_share = (x_scipy[1] + x_scipy[3]) / total_budget_used * 100

constraint_check_df = pd.DataFrame({
    "Chỉ tiêu": [
        "Tổng ngân sách sử dụng",
        "Tỷ trọng AI + R&D",
        "Sàn hạ tầng số",
        "Sàn AI và dữ liệu",
        "Sàn nhân lực số",
        "Sàn R&D"
    ],
    "Giá trị": [
        total_budget_used,
        strategic_share,
        x_scipy[0],
        x_scipy[1],
        x_scipy[2],
        x_scipy[3]
    ],
    "Yêu cầu": [
        "<= 100",
        ">= 35%",
        ">= 25",
        ">= 15",
        ">= 20",
        ">= 10"
    ]
})

display(constraint_check_df.round(4))

plt.figure(figsize=(7,7))
plt.pie(
    x_scipy,
    labels=items,
    autopct="%1.1f%%",
    startangle=90
)
plt.title("Cơ cấu phân bổ ngân sách tối ưu")
plt.show()

# ============================================================
# 8. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
8. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

top_item = items[np.argmax(x_scipy)]
top_contribution_item = items[np.argmax(coef * x_scipy)]

print(f"""
1. Khi ngân sách tổng tăng thêm 1 nghìn tỷ VND, GDP kỳ vọng tăng thêm bao nhiêu?

Dựa trên shadow price của ràng buộc ngân sách tổng, nếu ngân sách tăng thêm
1 nghìn tỷ VND, GDP gain tối ưu có thể tăng thêm khoảng {budget_shadow:.4f}
nghìn tỷ VND, trong phạm vi nghiệm tối ưu chưa thay đổi.

Đây có thể được xem là một chỉ báo về chi phí cơ hội biên của vốn công trong
mô hình. Tuy nhiên, đây không phải là cận trên tuyệt đối trong thực tế vì mô hình
chưa xét đến độ trễ đầu tư, năng lực hấp thụ, thất thoát ngân sách, rủi ro triển khai
và tác động xã hội ngoài GDP.

2. Vì sao R&D có hệ số tác động cao nhất nhưng ràng buộc tối thiểu thấp nhất?

R&D có hệ số cao nhất vì tác động lan tỏa dài hạn lớn, có thể tạo đổi mới sáng tạo,
năng suất và công nghệ nền tảng. Tuy nhiên, ràng buộc tối thiểu của R&D thấp hơn
vì R&D thường có độ trễ dài, rủi ro cao và cần năng lực hấp thụ tốt.

Trong quản lý ngân sách công, không thể phân bổ quá nhiều vào R&D nếu thiếu
nhân lực số, hạ tầng số và dữ liệu. Vì vậy, mức tối thiểu thấp không có nghĩa là
R&D kém quan trọng, mà phản ánh đặc điểm rủi ro và tính dài hạn của đầu tư R&D.

3. Tỷ lệ 35% cho AI + R&D có khả thi không?

Tỷ lệ công nghệ chiến lược trong nghiệm tối ưu là {strategic_share:.2f}%.
Điều này cho thấy mô hình đáp ứng ràng buộc tối thiểu 35%.

Tuy nhiên, trong thực tiễn, khả năng duy trì tỷ lệ 35% phụ thuộc vào ưu tiên ngân sách
của Nhà nước. Nếu ngân sách 2025–2026 phải ưu tiên hạ tầng giao thông, an sinh xã hội,
y tế và giáo dục cơ bản, việc dành tối thiểu 35% cho AI + R&D có thể gặp khó khăn.

4. Hạng mục được ưu tiên

Hạng mục nhận ngân sách lớn nhất trong nghiệm tối ưu là: {top_item}.
Hạng mục đóng góp GDP kỳ vọng lớn nhất là: {top_contribution_item}.

Kết quả phản ánh logic của mô hình LP: sau khi thỏa mãn các sàn tối thiểu,
ngân sách còn lại sẽ được phân bổ vào những hạng mục có hệ số tác động biên cao hơn.
""")

# ============================================================
# 9. KẾT LUẬN
# ============================================================

print("""
============================================================
9. KẾT LUẬN
============================================================

Bài 2 đã xây dựng và giải một bài toán quy hoạch tuyến tính đơn giản
cho phân bổ ngân sách chuyển đổi số theo 4 hạng mục: hạ tầng số, AI và dữ liệu,
nhân lực số, và R&D công nghệ.

Kết quả từ scipy.optimize.linprog và PuLP cho thấy mô hình có thể tìm được
phương án phân bổ tối ưu thỏa mãn ngân sách tổng, các mức đầu tư tối thiểu
và tỷ lệ công nghệ chiến lược.

Việc phân tích shadow price giúp hiểu ý nghĩa chính sách của ràng buộc ngân sách:
nếu ngân sách tăng thêm một đơn vị, GDP gain tối ưu có thể tăng thêm bao nhiêu
trong điều kiện cấu trúc nghiệm chưa đổi.

Phân tích độ nhạy cho thấy khi ngân sách tăng từ 100 lên 120 và 140 nghìn tỷ VND,
giá trị tối ưu Z* cũng tăng. Kịch bản tăng sàn nhân lực số lên 30 cho thấy đánh đổi
giữa hiệu quả GDP ngắn hạn và nhu cầu đầu tư nền tảng cho nhân lực số dài hạn.

Về mặt chính sách, mô hình cho thấy R&D và AI có vai trò quan trọng trong tăng trưởng,
nhưng cần đi kèm với đầu tư hạ tầng và nhân lực số để bảo đảm khả năng triển khai
và hấp thụ công nghệ.
""")

