# -*- coding: utf-8 -*-
"""Bai03_Priority_Index_Nganh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19YH8VWc7Mp6SsG6CMHP50KrcOhiaTgPA

# Chào mừng bạn đến với Colab!

## Truy cập vào các mô hình AI phổ biến thông qua Google-Colab-AI mà không cần khoá API
Tất cả người dùng đều có thể truy cập vào hầu hết các LLM phổ biến thông qua thư viện Python <code>Google-Colab-AI</code>. Người dùng trả tiền có thể truy cập vào nhiều mô hình hơn. Để biết thêm chi tiết, hãy tham khảo bài viết <a href="https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/Getting_started_with_google_colab_ai.ipynb">cách bắt đầu sử dụng Google-Colab-AI</a>.
"""

# ============================================================
# BÀI 3 — TÍNH CHỈ SỐ ƯU TIÊN NGÀNH PRIORITY_i
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Nếu cần heatmap đẹp hơn, dùng seaborn
try:
    import seaborn as sns
except ModuleNotFoundError:
    !pip install seaborn
    import seaborn as sns

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Việt Nam đang đẩy mạnh chuyển đổi số và ứng dụng AI trong nền kinh tế.
Tuy nhiên, nguồn lực chính sách và ngân sách là có hạn, vì vậy cần xác định
ngành nào nên được ưu tiên đầu tư trước để tạo hiệu ứng lan tỏa lớn nhất.

Theo cơ cấu kinh tế năm 2024, nền kinh tế Việt Nam gồm các khu vực lớn như:
nông-lâm-thủy sản, công nghiệp - xây dựng và dịch vụ. Mỗi ngành có đặc điểm
khác nhau về tăng trưởng, năng suất, xuất khẩu, việc làm, mức độ sẵn sàng AI
và rủi ro tự động hóa.

Bài toán đặt ra là xây dựng một chỉ số định lượng Priority_i để xếp hạng
10 ngành kinh tế Việt Nam theo mức độ ưu tiên chuyển đổi số và ứng dụng AI.
""")

# ============================================================
# 1. MÔ HÌNH TOÁN HỌC
# ============================================================

print("""
============================================================
1. MÔ HÌNH TOÁN HỌC
============================================================

Chỉ số ưu tiên ngành i được xác định theo công thức:

Priority_i =
a1*Growth_i
+ a2*Productivity_i
+ a3*Spillover_i
+ a4*Export_i
+ a5*Employment_i
+ a6*AIReadiness_i
- a7*Risk_i

Trong đó:
- Growth       : tốc độ tăng trưởng ngành
- Productivity : năng suất lao động
- Spillover    : hệ số lan tỏa
- Export       : giá trị xuất khẩu
- Employment   : quy mô việc làm
- AIReadiness  : mức độ sẵn sàng AI
- Risk         : rủi ro tự động hóa

Các biến có đơn vị đo khác nhau, vì vậy cần chuẩn hóa min-max về thang [0,1].

Với tiêu chí tốt:
x_tilde = (x - min(x)) / (max(x) - min(x))

Với tiêu chí xấu như rủi ro tự động hóa:
risk_tilde = (risk - min(risk)) / (max(risk) - min(risk))

Trong công thức Priority, Risk được trừ đi để phản ánh tác động bất lợi.
""")

# ============================================================
# 2. ĐỌC VÀ KHAI BÁO DỮ LIỆU
# ============================================================

print("""
============================================================
2. DỮ LIỆU SỬ DỤNG
============================================================

Dữ liệu gồm 10 ngành kinh tế Việt Nam năm 2024 với các chỉ tiêu:
tăng trưởng, năng suất, lan tỏa, xuất khẩu, việc làm, AI readiness
và rủi ro tự động hóa.

Nếu có file vietnam_sectors_2024.csv thì notebook sẽ đọc file đó.
Nếu chưa có file, notebook sử dụng dữ liệu mặc định theo đề bài.
""")

try:
    df = pd.read_csv("vietnam_sectors_2024.csv")
except FileNotFoundError:
    print("Không tìm thấy file vietnam_sectors_2024.csv. Sử dụng dữ liệu mặc định theo đề bài.")

    df = pd.DataFrame({
        "sector_name_vi": [
            "Nông-Lâm-Thủy sản",
            "CN chế biến chế tạo",
            "Xây dựng",
            "Khai khoáng",
            "Bán buôn-bán lẻ",
            "Tài chính-Ngân hàng",
            "Logistics-Vận tải",
            "CNTT-Truyền thông",
            "Giáo dục-Đào tạo",
            "Y tế"
        ],
        "growth_rate_2024_pct": [3.27, 9.64, 7.45, -1.20, 7.10, 7.36, 9.93, 7.85, 6.42, 6.85],
        "productivity_million_VND_per_worker": [103.4, 241.2, 168.8, 1290.5, 145.3, 1072.4, 321.4, 713.8, 205.7, 437.1],
        "spillover_coef_0_1": [0.35, 0.78, 0.42, 0.30, 0.55, 0.85, 0.72, 0.92, 0.65, 0.60],
        "export_billion_USD": [40.5, 290.9, 2.5, 8.2, 5.5, 1.2, 3.1, 178.0, 0.0, 0.0],
        "labor_million": [13.20, 11.50, 4.80, 0.30, 7.80, 0.55, 1.95, 0.62, 2.15, 0.75],
        "ai_readiness_0_100": [15, 55, 20, 30, 48, 72, 42, 88, 38, 45],
        "automation_risk_pct": [18, 42, 25, 55, 38, 52, 35, 28, 22, 18]
    })

# Chuẩn hóa tên cột trong trường hợp file CSV dùng tên khác
if "gdp_share_2024_pct" in df.columns and "productivity_million_VND_per_worker" not in df.columns:
    df["productivity_million_VND_per_worker"] = df["gdp_share_2024_pct"]

display(df)

# ============================================================
# 3. CÂU 3.4.1 — CHUẨN HÓA MIN-MAX
# ============================================================

print("""
============================================================
3. CÂU 3.4.1 — CHUẨN HÓA MIN-MAX CÁC CHỈ TIÊU
============================================================

Các chỉ tiêu tốt được chuẩn hóa theo công thức:

x_tilde = (x - min) / (max - min)

Rủi ro tự động hóa được chuẩn hóa như một tiêu chí bất lợi.
Trong công thức Priority, phần Risk chuẩn hóa sẽ bị trừ đi.
""")

cols_good = [
    "growth_rate_2024_pct",
    "productivity_million_VND_per_worker",
    "spillover_coef_0_1",
    "export_billion_USD",
    "labor_million",
    "ai_readiness_0_100"
]

col_bad = "automation_risk_pct"

def norm_good(x):
    if x.max() == x.min():
        return x * 0
    return (x - x.min()) / (x.max() - x.min())

def norm_bad(x):
    if x.max() == x.min():
        return x * 0
    return (x - x.min()) / (x.max() - x.min())

Xg = df[cols_good].apply(norm_good)
Xrisk = norm_bad(df[col_bad])

normalized_df = pd.DataFrame({
    "Ngành": df["sector_name_vi"],
    "Growth_norm": Xg["growth_rate_2024_pct"],
    "Productivity_norm": Xg["productivity_million_VND_per_worker"],
    "Spillover_norm": Xg["spillover_coef_0_1"],
    "Export_norm": Xg["export_billion_USD"],
    "Employment_norm": Xg["labor_million"],
    "AIReadiness_norm": Xg["ai_readiness_0_100"],
    "Risk_norm": Xrisk
})

display(normalized_df.round(4))

print("""
Nhận xét:
Sau chuẩn hóa, tất cả các tiêu chí được đưa về cùng thang đo [0,1].
Điều này giúp có thể cộng có trọng số các tiêu chí khác đơn vị như
tăng trưởng, xuất khẩu, lao động, AI readiness và rủi ro tự động hóa.
""")

# Heatmap ma trận chuẩn hóa
plt.figure(figsize=(12,6))
sns.heatmap(
    normalized_df.set_index("Ngành"),
    annot=True,
    fmt=".2f",
    cmap="YlGnBu"
)
plt.title("Heatmap ma trận chỉ tiêu đã chuẩn hóa")
plt.xlabel("Chỉ tiêu")
plt.ylabel("Ngành")
plt.show()

# ============================================================
# 4. CÂU 3.4.2 — TÍNH PRIORITY VỚI TRỌNG SỐ MẶC ĐỊNH
# ============================================================

print("""
============================================================
4. CÂU 3.4.2 — TÍNH PRIORITY_i VỚI TRỌNG SỐ MẶC ĐỊNH
============================================================

Bộ trọng số mặc định:
a1 = 0.15 cho tăng trưởng
a2 = 0.15 cho năng suất
a3 = 0.20 cho lan tỏa
a4 = 0.15 cho xuất khẩu
a5 = 0.10 cho việc làm
a6 = 0.20 cho AI readiness
a7 = 0.15 cho rủi ro tự động hóa
""")

weights_default = {
    "Growth": 0.15,
    "Productivity": 0.15,
    "Spillover": 0.20,
    "Export": 0.15,
    "Employment": 0.10,
    "AIReadiness": 0.20,
    "Risk": 0.15
}

priority = (
    weights_default["Growth"] * normalized_df["Growth_norm"]
    + weights_default["Productivity"] * normalized_df["Productivity_norm"]
    + weights_default["Spillover"] * normalized_df["Spillover_norm"]
    + weights_default["Export"] * normalized_df["Export_norm"]
    + weights_default["Employment"] * normalized_df["Employment_norm"]
    + weights_default["AIReadiness"] * normalized_df["AIReadiness_norm"]
    - weights_default["Risk"] * normalized_df["Risk_norm"]
)

df_result = df.copy()
df_result["Priority"] = priority

ranking_df = df_result.sort_values("Priority", ascending=False).reset_index(drop=True)
ranking_df["Xếp hạng"] = ranking_df.index + 1

display(ranking_df[["Xếp hạng", "sector_name_vi", "Priority"]].round(4))

# Bar chart ranking
plt.figure(figsize=(12,6))
plt.barh(ranking_df["sector_name_vi"], ranking_df["Priority"])
plt.gca().invert_yaxis()
plt.title("Xếp hạng 10 ngành theo chỉ số Priority")
plt.xlabel("Priority score")
plt.ylabel("Ngành")
plt.grid(axis="x")
plt.show()

# Biểu đồ top 5
top5 = ranking_df.head(5)

plt.figure(figsize=(10,5))
plt.bar(top5["sector_name_vi"], top5["Priority"])
plt.title("Top 5 ngành ưu tiên chuyển đổi số và AI")
plt.ylabel("Priority score")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

top3_default = ranking_df.head(3)["sector_name_vi"].tolist()

print(f"""
Nhận xét:
Ba ngành đứng đầu theo bộ trọng số mặc định là:

1. {top3_default[0]}
2. {top3_default[1]}
3. {top3_default[2]}

Các ngành này có điểm ưu tiên cao vì kết hợp được nhiều tiêu chí như tăng trưởng,
lan tỏa, xuất khẩu, AI readiness và/hoặc quy mô việc làm.
""")

# ============================================================
# 5. BIỂU ĐỒ MỞ RỘNG — PHÂN RÃ ĐIỂM PRIORITY
# ============================================================

print("""
============================================================
5. BIỂU ĐỒ MỞ RỘNG — PHÂN RÃ ĐIỂM PRIORITY THEO TIÊU CHÍ
============================================================

Biểu đồ này cho thấy điểm Priority của mỗi ngành đến từ tiêu chí nào.
""")

component_df = pd.DataFrame({
    "Ngành": df["sector_name_vi"],
    "Growth": weights_default["Growth"] * normalized_df["Growth_norm"],
    "Productivity": weights_default["Productivity"] * normalized_df["Productivity_norm"],
    "Spillover": weights_default["Spillover"] * normalized_df["Spillover_norm"],
    "Export": weights_default["Export"] * normalized_df["Export_norm"],
    "Employment": weights_default["Employment"] * normalized_df["Employment_norm"],
    "AIReadiness": weights_default["AIReadiness"] * normalized_df["AIReadiness_norm"],
    "Risk_penalty": -weights_default["Risk"] * normalized_df["Risk_norm"],
    "Priority": priority
})

display(component_df.round(4))

component_plot = component_df.set_index("Ngành")[
    ["Growth", "Productivity", "Spillover", "Export", "Employment", "AIReadiness", "Risk_penalty"]
]

component_plot.loc[ranking_df["sector_name_vi"]].plot(
    kind="bar",
    stacked=True,
    figsize=(14,6)
)
plt.title("Phân rã điểm Priority theo từng tiêu chí")
plt.ylabel("Điểm đóng góp")
plt.xlabel("Ngành")
plt.xticks(rotation=35, ha="right")
plt.grid(axis="y")
plt.show()

# Radar chart cho top 3
print("""
Biểu đồ radar dưới đây so sánh hồ sơ tiêu chí của top 3 ngành.
""")

radar_cols = [
    "Growth_norm",
    "Productivity_norm",
    "Spillover_norm",
    "Export_norm",
    "Employment_norm",
    "AIReadiness_norm"
]

top3_names = top3_default
radar_df = normalized_df[normalized_df["Ngành"].isin(top3_names)].copy()

labels = ["Growth", "Productivity", "Spillover", "Export", "Employment", "AI"]
num_vars = len(labels)
angles = np.linspace(0, 2*np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]

plt.figure(figsize=(8,8))
ax = plt.subplot(111, polar=True)

for _, row in radar_df.iterrows():
    values = row[radar_cols].values.flatten().tolist()
    values += values[:1]
    ax.plot(angles, values, linewidth=2, label=row["Ngành"])
    ax.fill(angles, values, alpha=0.08)

ax.set_xticks(angles[:-1])
ax.set_xticklabels(labels)
ax.set_title("Radar chart hồ sơ tiêu chí của Top 3 ngành")
ax.legend(loc="upper right", bbox_to_anchor=(1.3, 1.1))
plt.show()

# ============================================================
# 6. CÂU 3.4.3 — PHÂN TÍCH ĐỘ NHẠY THEO TRỌNG SỐ AI READINESS
# ============================================================

print("""
============================================================
6. CÂU 3.4.3 — PHÂN TÍCH ĐỘ NHẠY THEO TRỌNG SỐ AI READINESS
============================================================

Thay đổi trọng số AI Readiness từ 0.05 đến 0.40.
Các trọng số còn lại được chuẩn hóa lại để tổng trọng số tuyệt đối bằng 1.
""")

criteria_names = ["Growth", "Productivity", "Spillover", "Export", "Employment", "AIReadiness", "Risk"]
base_weights = np.array([
    weights_default["Growth"],
    weights_default["Productivity"],
    weights_default["Spillover"],
    weights_default["Export"],
    weights_default["Employment"],
    weights_default["AIReadiness"],
    weights_default["Risk"]
])

ai_weight_values = np.arange(0.05, 0.401, 0.05)

sensitivity_scores = []
top3_by_ai_weight = {}

for ai_w in ai_weight_values:
    other_indices = [0, 1, 2, 3, 4, 6]
    other_weights = base_weights[other_indices]
    other_weights_scaled = other_weights / other_weights.sum() * (1 - ai_w)

    w = np.zeros(7)
    w[0] = other_weights_scaled[0]
    w[1] = other_weights_scaled[1]
    w[2] = other_weights_scaled[2]
    w[3] = other_weights_scaled[3]
    w[4] = other_weights_scaled[4]
    w[5] = ai_w
    w[6] = other_weights_scaled[5]

    priority_ai = (
        w[0] * normalized_df["Growth_norm"]
        + w[1] * normalized_df["Productivity_norm"]
        + w[2] * normalized_df["Spillover_norm"]
        + w[3] * normalized_df["Export_norm"]
        + w[4] * normalized_df["Employment_norm"]
        + w[5] * normalized_df["AIReadiness_norm"]
        - w[6] * normalized_df["Risk_norm"]
    )

    temp = pd.DataFrame({
        "Ngành": df["sector_name_vi"],
        "AI_weight": round(ai_w, 2),
        "Priority": priority_ai
    }).sort_values("Priority", ascending=False).reset_index(drop=True)

    temp["Rank"] = temp.index + 1
    sensitivity_scores.append(temp)

    top3_by_ai_weight[round(ai_w, 2)] = temp.head(3)["Ngành"].tolist()

sensitivity_df = pd.concat(sensitivity_scores, ignore_index=True)

display(sensitivity_df.head(20).round(4))

# Pivot score heatmap
score_heatmap = sensitivity_df.pivot(index="Ngành", columns="AI_weight", values="Priority")

# Sắp xếp theo ranking mặc định
score_heatmap = score_heatmap.loc[ranking_df["sector_name_vi"]]

plt.figure(figsize=(12,7))
sns.heatmap(score_heatmap, annot=True, fmt=".2f", cmap="YlOrRd")
plt.title("Heatmap điểm Priority khi thay đổi trọng số AI Readiness")
plt.xlabel("Trọng số AI Readiness")
plt.ylabel("Ngành")
plt.show()

# Heatmap rank
rank_heatmap = sensitivity_df.pivot(index="Ngành", columns="AI_weight", values="Rank")
rank_heatmap = rank_heatmap.loc[ranking_df["sector_name_vi"]]

plt.figure(figsize=(12,7))
sns.heatmap(rank_heatmap, annot=True, fmt=".0f", cmap="viridis_r")
plt.title("Heatmap thứ hạng ngành khi thay đổi trọng số AI Readiness")
plt.xlabel("Trọng số AI Readiness")
plt.ylabel("Ngành")
plt.show()

print("Top-3 theo từng mức trọng số AI Readiness:")
for ai_w, top3 in top3_by_ai_weight.items():
    print(f"AI weight = {ai_w:.2f}: {top3}")

top3_sets = [tuple(v) for v in top3_by_ai_weight.values()]
is_stable = len(set(top3_sets)) == 1

if is_stable:
    print("""
Nhận xét:
Top-3 không thay đổi khi tăng trọng số AI Readiness.
Điều này cho thấy kết quả xếp hạng khá ổn định theo tiêu chí AI.
""")
else:
    print("""
Nhận xét:
Top-3 có thay đổi khi tăng trọng số AI Readiness.
Điều này cho thấy lựa chọn ngành ưu tiên khá nhạy cảm với ưu tiên chính sách
về AI readiness. Khi trọng số AI tăng, các ngành có nền tảng số và năng lực AI
cao như CNTT-Truyền thông hoặc Tài chính-Ngân hàng thường có xu hướng tăng hạng.
""")

# ============================================================
# 7. CÂU 3.4.4 — SO SÁNH HAI BỘ TRỌNG SỐ CHÍNH SÁCH
# ============================================================

print("""
============================================================
7. CÂU 3.4.4 — SO SÁNH HAI BỘ TRỌNG SỐ CHÍNH SÁCH
============================================================

So sánh hai định hướng:

1. Định hướng tăng trưởng:
   Ưu tiên tăng trưởng, năng suất, xuất khẩu và AI readiness.

2. Định hướng bao trùm:
   Ưu tiên việc làm, lan tỏa và giảm rủi ro tự động hóa.
""")

weights_growth = {
    "Growth": 0.25,
    "Productivity": 0.20,
    "Spillover": 0.15,
    "Export": 0.20,
    "Employment": 0.05,
    "AIReadiness": 0.10,
    "Risk": 0.05
}

weights_inclusive = {
    "Growth": 0.10,
    "Productivity": 0.10,
    "Spillover": 0.25,
    "Export": 0.05,
    "Employment": 0.25,
    "AIReadiness": 0.10,
    "Risk": 0.15
}

def compute_priority(w):
    return (
        w["Growth"] * normalized_df["Growth_norm"]
        + w["Productivity"] * normalized_df["Productivity_norm"]
        + w["Spillover"] * normalized_df["Spillover_norm"]
        + w["Export"] * normalized_df["Export_norm"]
        + w["Employment"] * normalized_df["Employment_norm"]
        + w["AIReadiness"] * normalized_df["AIReadiness_norm"]
        - w["Risk"] * normalized_df["Risk_norm"]
    )

priority_growth = compute_priority(weights_growth)
priority_inclusive = compute_priority(weights_inclusive)

compare_policy_df = pd.DataFrame({
    "Ngành": df["sector_name_vi"],
    "Priority mặc định": priority,
    "Priority tăng trưởng": priority_growth,
    "Priority bao trùm": priority_inclusive
})

compare_policy_df["Rank mặc định"] = compare_policy_df["Priority mặc định"].rank(ascending=False, method="min").astype(int)
compare_policy_df["Rank tăng trưởng"] = compare_policy_df["Priority tăng trưởng"].rank(ascending=False, method="min").astype(int)
compare_policy_df["Rank bao trùm"] = compare_policy_df["Priority bao trùm"].rank(ascending=False, method="min").astype(int)

display(compare_policy_df.sort_values("Rank mặc định").round(4))

top3_growth = compare_policy_df.sort_values("Priority tăng trưởng", ascending=False).head(3)["Ngành"].tolist()
top3_inclusive = compare_policy_df.sort_values("Priority bao trùm", ascending=False).head(3)["Ngành"].tolist()

print(f"Top-3 theo định hướng tăng trưởng: {top3_growth}")
print(f"Top-3 theo định hướng bao trùm: {top3_inclusive}")

# Biểu đồ so sánh điểm theo ba bộ trọng số
plot_compare = compare_policy_df.set_index("Ngành")[
    ["Priority mặc định", "Priority tăng trưởng", "Priority bao trùm"]
]

plot_compare.loc[ranking_df["sector_name_vi"]].plot(kind="bar", figsize=(14,6))
plt.title("So sánh điểm Priority theo ba bộ trọng số")
plt.ylabel("Priority score")
plt.xlabel("Ngành")
plt.xticks(rotation=35, ha="right")
plt.grid(axis="y")
plt.show()

# Biểu đồ thay đổi thứ hạng
rank_compare = compare_policy_df.set_index("Ngành")[
    ["Rank mặc định", "Rank tăng trưởng", "Rank bao trùm"]
]

rank_compare.loc[ranking_df["sector_name_vi"]].plot(kind="bar", figsize=(14,6))
plt.title("So sánh thứ hạng ngành theo ba bộ trọng số")
plt.ylabel("Thứ hạng")
plt.xlabel("Ngành")
plt.xticks(rotation=35, ha="right")
plt.gca().invert_yaxis()
plt.grid(axis="y")
plt.show()

print("""
Nhận xét:
Bộ trọng số tăng trưởng thường ưu tiên các ngành có năng suất, xuất khẩu,
tăng trưởng và AI readiness cao. Vì vậy, các ngành như CNTT-Truyền thông,
CN chế biến chế tạo hoặc Tài chính-Ngân hàng thường có thứ hạng cao.

Bộ trọng số bao trùm lại ưu tiên việc làm, lan tỏa và giảm rủi ro tự động hóa.
Do đó, các ngành sử dụng nhiều lao động hoặc có tác động xã hội rộng như
Nông-Lâm-Thủy sản, Giáo dục-Đào tạo hoặc Bán buôn-bán lẻ có thể được cải thiện
thứ hạng.

Kết quả cho thấy lựa chọn ngành ưu tiên phụ thuộc mạnh vào mục tiêu chính sách.
Không có một bộ trọng số tuyệt đối đúng cho mọi bối cảnh.
""")

# ============================================================
# 8. BIỂU ĐỒ MỞ RỘNG — MA TRẬN TƯƠNG QUAN VÀ RISK-AI MAP
# ============================================================

print("""
============================================================
8. BIỂU ĐỒ MỞ RỘNG — TƯƠNG QUAN VÀ BẢN ĐỒ AI-RISK
============================================================

Phần mở rộng giúp hiểu sâu hơn quan hệ giữa các tiêu chí.
""")

corr_cols = cols_good + [col_bad]
corr_df = df[corr_cols].corr()

plt.figure(figsize=(10,7))
sns.heatmap(corr_df, annot=True, fmt=".2f", cmap="coolwarm", center=0)
plt.title("Ma trận tương quan giữa các chỉ tiêu ngành")
plt.show()

plt.figure(figsize=(10,6))
plt.scatter(
    df["ai_readiness_0_100"],
    df["automation_risk_pct"],
    s=df["labor_million"] * 80,
    alpha=0.7
)

for i, row in df.iterrows():
    plt.text(
        row["ai_readiness_0_100"] + 0.5,
        row["automation_risk_pct"] + 0.5,
        row["sector_name_vi"],
        fontsize=9
    )

plt.title("Bản đồ AI Readiness - Rủi ro tự động hóa")
plt.xlabel("AI Readiness")
plt.ylabel("Rủi ro tự động hóa (%)")
plt.grid(True)
plt.show()

print("""
Diễn giải biểu đồ AI-Risk:
- Góc phải phía trên: ngành vừa có AI readiness cao vừa có rủi ro tự động hóa cao.
  Đây là nhóm cần chính sách chuyển đổi việc làm và đào tạo lại.
- Góc phải phía dưới: ngành có AI readiness cao nhưng rủi ro thấp hơn.
  Đây là nhóm có thể ưu tiên triển khai AI sớm.
- Kích thước điểm phản ánh quy mô lao động, giúp nhận diện tác động xã hội.
""")

# ============================================================
# 9. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
9. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

top3_text = "\n".join([f"{i+1}. {name}" for i, name in enumerate(top3_default)])

mining_rank = int(compare_policy_df.loc[
    compare_policy_df["Ngành"] == "Khai khoáng",
    "Rank mặc định"
].values[0])

print(f"""
1. Ba ngành nên được ưu tiên chuyển đổi số và AI trước

Theo bộ trọng số mặc định, top-3 ngành ưu tiên là:

{top3_text}

Các ngành này nổi bật nhờ kết hợp nhiều yếu tố như tăng trưởng, lan tỏa,
xuất khẩu, AI readiness và/hoặc quy mô việc làm. Kết quả này nhìn chung phù hợp
với định hướng thúc đẩy khoa học công nghệ, đổi mới sáng tạo và chuyển đổi số
trong phát triển kinh tế.

2. Vì sao Khai khoáng có năng suất cao nhưng không nhất thiết nằm trong nhóm ưu tiên?

Ngành Khai khoáng có năng suất lao động rất cao, nhưng lại có một số hạn chế:
- tăng trưởng thấp hoặc âm;
- hệ số lan tỏa thấp;
- quy mô việc làm nhỏ;
- rủi ro tự động hóa cao;
- khả năng tạo hiệu ứng chuyển đổi số rộng không lớn bằng các ngành khác.

Trong kết quả mặc định, Khai khoáng xếp hạng {mining_rank}.
Điều này cho thấy năng suất cao riêng lẻ không đủ để trở thành ngành ưu tiên
nếu thiếu lan tỏa, tăng trưởng, việc làm và khả năng hấp thụ AI.

3. Ai nên quyết định bộ trọng số?

Bộ trọng số không nên chỉ do chuyên gia kỹ thuật quyết định, vì lựa chọn trọng số
phản ánh ưu tiên xã hội và định hướng chính sách. Một quy trình hợp lý nên kết hợp:

- chuyên gia kỹ thuật: bảo đảm phương pháp định lượng đúng;
- cơ quan hoạch định chính sách: phản ánh mục tiêu phát triển quốc gia;
- doanh nghiệp và hiệp hội ngành: cung cấp thông tin thực tiễn;
- người lao động và xã hội dân sự: phản ánh tác động xã hội;
- quy trình tham vấn công khai: tăng tính minh bạch và chính danh.

Vì vậy, trọng số nên được quyết định thông qua một quy trình governance đa bên,
không phải chỉ bởi một nhóm chuyên gia.
""")

# ============================================================
# 10. KẾT LUẬN
# ============================================================

print("""
============================================================
10. KẾT LUẬN
============================================================

Bài 3 đã xây dựng chỉ số Priority_i để xếp hạng mức độ ưu tiên chuyển đổi số
và ứng dụng AI cho 10 ngành kinh tế Việt Nam.

Kết quả cho thấy xếp hạng ngành phụ thuộc vào nhiều yếu tố: tăng trưởng,
năng suất, lan tỏa, xuất khẩu, việc làm, AI readiness và rủi ro tự động hóa.
Việc chuẩn hóa min-max giúp đưa các chỉ tiêu khác đơn vị về cùng thang đo,
từ đó có thể tính điểm tổng hợp có trọng số.

Phân tích độ nhạy theo trọng số AI Readiness cho thấy top-3 ngành có thể thay đổi
khi ưu tiên chính sách thay đổi. Điều này chứng minh rằng mô hình không chỉ là
bài toán kỹ thuật mà còn là công cụ hỗ trợ thảo luận chính sách.

So sánh giữa định hướng tăng trưởng và định hướng bao trùm cho thấy mỗi bộ trọng số
dẫn đến một tập ngành ưu tiên khác nhau. Do đó, việc xác định trọng số cần được thực hiện
một cách minh bạch, có tham vấn đa bên và gắn với mục tiêu phát triển của Việt Nam.
""")

