# -*- coding: utf-8 -*-
"""Bai04_LP_NganSach_Nganh_Vung.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMgdqwoy0UuBAfuLKghfE-hdd0F01tjI
"""

# ============================================================
# BÀI 4 — QUY HOẠCH TUYẾN TÍNH PHÂN BỔ NGÂN SÁCH SỐ THEO NGÀNH - VÙNG
# Bản đã sửa lỗi infeasible và giải thích rõ nguyên nhân
# Dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    import seaborn as sns
except ModuleNotFoundError:
    !pip install seaborn
    import seaborn as sns

try:
    import pulp
except ModuleNotFoundError:
    !pip install pulp
    import pulp

try:
    import cvxpy as cp
except ModuleNotFoundError:
    !pip install cvxpy
    import cvxpy as cp

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Bài toán phân bổ 50.000 tỷ VND ngân sách kinh tế số quốc gia
cho 6 vùng kinh tế - xã hội và 4 hạng mục đầu tư:

I  : hạ tầng số
D  : chuyển đổi số doanh nghiệp
AI : năng lực AI
H  : nhân lực số

Mục tiêu là tối đa hóa GDP gain kỳ vọng nhưng vẫn bảo đảm công bằng vùng miền.

Điểm quan trọng:
Ràng buộc công bằng vùng miền có thể làm bài toán không khả thi nếu đặt quá chặt,
đặc biệt khi vùng có chỉ số số hóa ban đầu rất thấp nhưng lại bị giới hạn bởi trần
ngân sách mỗi vùng.
""")

# ============================================================
# 1. MÔ HÌNH TOÁN HỌC
# ============================================================

print("""
============================================================
1. MÔ HÌNH TOÁN HỌC
============================================================

Biến quyết định:

x[j,r] >= 0

là ngân sách phân bổ cho hạng mục j tại vùng r.

Hàm mục tiêu:

Max Z = Σ_r Σ_j beta[j,r] * x[j,r]

Ràng buộc:

C1. Tổng ngân sách:
Σ_r Σ_j x[j,r] <= 50000

C2. Sàn ngân sách mỗi vùng:
Σ_j x[j,r] >= 5000

C3. Trần ngân sách mỗi vùng:
Σ_j x[j,r] <= 12000

C4. Sàn nhân lực số:
Σ_r x[H,r] >= 12000

C5. Công bằng vùng:
D_r + gamma*x[D,r] >= lambda * max_r(D_r + gamma*x[D,r])

Tuyến tính hóa bằng biến M:

D_r + gamma*x[D,r] <= M
D_r + gamma*x[D,r] >= lambda*M

C6. Không âm:
x[j,r] >= 0
""")

# ============================================================
# 2. DỮ LIỆU ĐẦU VÀO
# ============================================================

regions = ["NMM", "RRD", "NCC", "CH", "SE", "MD"]

region_names = {
    "NMM": "Trung du miền núi phía Bắc",
    "RRD": "Đồng bằng sông Hồng",
    "NCC": "Bắc Trung Bộ + DH Trung Bộ",
    "CH": "Tây Nguyên",
    "SE": "Đông Nam Bộ",
    "MD": "Đồng bằng sông Cửu Long"
}

items = ["I", "D", "AI", "H"]

item_names = {
    "I": "Hạ tầng số",
    "D": "CĐS doanh nghiệp",
    "AI": "Năng lực AI",
    "H": "Nhân lực số"
}

beta = {
    ("NMM","I"):1.15, ("NMM","D"):0.85, ("NMM","AI"):0.55, ("NMM","H"):1.30,
    ("RRD","I"):0.95, ("RRD","D"):1.25, ("RRD","AI"):1.40, ("RRD","H"):1.05,
    ("NCC","I"):1.05, ("NCC","D"):0.95, ("NCC","AI"):0.85, ("NCC","H"):1.15,
    ("CH","I"):1.20,  ("CH","D"):0.75,  ("CH","AI"):0.45,  ("CH","H"):1.35,
    ("SE","I"):0.90,  ("SE","D"):1.30,  ("SE","AI"):1.55,  ("SE","H"):1.00,
    ("MD","I"):1.10,  ("MD","D"):0.85,  ("MD","AI"):0.65,  ("MD","H"):1.25
}

D0 = {
    "NMM": 38,
    "RRD": 78,
    "NCC": 55,
    "CH": 32,
    "SE": 82,
    "MD": 48
}

total_budget = 50000
min_region_budget = 5000
max_region_budget = 12000
min_human_budget = 12000
gamma = 0.002

# Lambda gốc theo đề
lambda_original = 0.70

# Lambda hiệu chỉnh để mô hình khả thi
lambda_adjusted = 0.65

print("""
============================================================
2. DỮ LIỆU ĐẦU VÀO
============================================================
""")

beta_df = pd.DataFrame(
    [[region_names[r]] + [beta[(r,j)] for j in items] + [D0[r]] for r in regions],
    columns=[
        "Vùng",
        "I - Hạ tầng số",
        "D - CĐS DN",
        "AI",
        "H - Nhân lực số",
        "Digital Index ban đầu"
    ]
)

display(beta_df)

plt.figure(figsize=(10,5))
sns.heatmap(
    beta_df.set_index("Vùng")[["I - Hạ tầng số", "D - CĐS DN", "AI", "H - Nhân lực số"]],
    annot=True,
    fmt=".2f",
    cmap="YlGnBu"
)
plt.title("Heatmap hệ số tác động biên beta[j,r]")
plt.xlabel("Hạng mục đầu tư")
plt.ylabel("Vùng")
plt.show()

# ============================================================
# 3. KIỂM TRA TÍNH KHẢ THI CỦA RÀNG BUỘC CÔNG BẰNG
# ============================================================

print("""
============================================================
3. KIỂM TRA TÍNH KHẢ THI CỦA RÀNG BUỘC CÔNG BẰNG
============================================================
""")

Dmax_initial = max(D0.values())
Dmin_initial = min(D0.values())
lowest_region = min(D0, key=D0.get)
highest_region = max(D0, key=D0.get)

required_D_original = lambda_original * Dmax_initial
required_xD_original = (required_D_original - D0[lowest_region]) / gamma

required_D_adjusted = lambda_adjusted * Dmax_initial
required_xD_adjusted = (required_D_adjusted - D0[lowest_region]) / gamma

feasibility_df = pd.DataFrame({
    "Chỉ tiêu": [
        "Vùng có Digital Index thấp nhất",
        "Digital Index thấp nhất",
        "Vùng có Digital Index cao nhất",
        "Digital Index cao nhất",
        "Ngưỡng yêu cầu với lambda = 0.70",
        "x_D tối thiểu cần cho vùng thấp nhất, lambda = 0.70",
        "Trần ngân sách mỗi vùng",
        "Ngưỡng yêu cầu với lambda = 0.65",
        "x_D tối thiểu cần cho vùng thấp nhất, lambda = 0.65"
    ],
    "Giá trị": [
        region_names[lowest_region],
        D0[lowest_region],
        region_names[highest_region],
        D0[highest_region],
        required_D_original,
        required_xD_original,
        max_region_budget,
        required_D_adjusted,
        required_xD_adjusted
    ]
})

display(feasibility_df)

print(f"""
Giải thích lỗi infeasible:

Với lambda = 0.70, vùng thấp nhất là {region_names[lowest_region]} có D0 = {D0[lowest_region]}.
Vùng cao nhất có D0 = {Dmax_initial}.

Điều kiện công bằng yêu cầu vùng thấp nhất đạt ít nhất:

0.70 * {Dmax_initial} = {required_D_original:.2f}

Do đó cần:

{D0[lowest_region]} + 0.002*x_D >= {required_D_original:.2f}
=> x_D >= {required_xD_original:,.2f}

Nhưng trần ngân sách mỗi vùng chỉ là {max_region_budget:,.0f}.
Vì chỉ riêng x_D đã cần lớn hơn trần vùng, mô hình với lambda = 0.70 là không khả thi.

Vì vậy, để tiếp tục phân tích, mô hình được hiệu chỉnh lambda = 0.65.
Khi đó x_D tối thiểu cần thiết là khoảng {required_xD_adjusted:,.2f}, nằm dưới trần vùng.
""")

# ============================================================
# 4. HÀM GIẢI MÔ HÌNH BẰNG PuLP
# ============================================================

def solve_pulp(use_fairness=True, lam=0.65, max_region_cap=12000):
    model = pulp.LpProblem("VN_Digital_Budget", pulp.LpMaximize)

    x = pulp.LpVariable.dicts("x", (regions, items), lowBound=0)

    # Hàm mục tiêu
    model += pulp.lpSum(beta[(r,j)] * x[r][j] for r in regions for j in items), "GDP_gain"

    # C1
    model += pulp.lpSum(x[r][j] for r in regions for j in items) <= total_budget, "Budget_total"

    # C2, C3
    for r in regions:
        model += pulp.lpSum(x[r][j] for j in items) >= min_region_budget, f"Min_region_{r}"
        model += pulp.lpSum(x[r][j] for j in items) <= max_region_cap, f"Max_region_{r}"

    # C4
    model += pulp.lpSum(x[r]["H"] for r in regions) >= min_human_budget, "Min_human_capital"

    # C5
    if use_fairness:
        M = pulp.LpVariable("Dmax", lowBound=0)

        for r in regions:
            model += D0[r] + gamma * x[r]["D"] <= M, f"Dmax_upper_{r}"

        for r in regions:
            model += D0[r] + gamma * x[r]["D"] >= lam * M, f"Fairness_lower_{r}"

    model.solve(pulp.PULP_CBC_CMD(msg=False))

    status = pulp.LpStatus[model.status]

    if status != "Optimal":
        return None, None, status, model

    result = pd.DataFrame(
        index=[region_names[r] for r in regions],
        columns=[item_names[j] for j in items]
    )

    for r in regions:
        for j in items:
            result.loc[region_names[r], item_names[j]] = x[r][j].value()

    result = result.astype(float)
    z_value = pulp.value(model.objective)

    return result, z_value, status, model

# ============================================================
# 5. THỬ CHẠY MÔ HÌNH GỐC lambda = 0.70
# ============================================================

print("""
============================================================
5. KIỂM TRA MÔ HÌNH GỐC VỚI lambda = 0.70
============================================================
""")

result_original, z_original, status_original, model_original = solve_pulp(
    use_fairness=True,
    lam=lambda_original,
    max_region_cap=max_region_budget
)

print("Trạng thái mô hình gốc:", status_original)

if status_original != "Optimal":
    print("""
Kết luận:
Mô hình gốc với lambda = 0.70 không khả thi.
Do đó, không được sử dụng các giá trị biến mà PuLP có thể in ra trong trạng thái Infeasible.
Ta chuyển sang mô hình hiệu chỉnh lambda = 0.65 để tiếp tục phân tích.
""")
else:
    print(f"Z* mô hình gốc = {z_original:,.4f}")
    display(result_original.round(2))

# ============================================================
# 6. CÂU 4.4.1 — GIẢI MÔ HÌNH HIỆU CHỈNH BẰNG PuLP
# ============================================================

print("""
============================================================
6. CÂU 4.4.1 — GIẢI MÔ HÌNH BẰNG PuLP SAU HIỆU CHỈNH
============================================================
""")

result_fair, z_fair, status_fair, model_fair = solve_pulp(
    use_fairness=True,
    lam=lambda_adjusted,
    max_region_cap=max_region_budget
)

print("Trạng thái nghiệm:", status_fair)

if status_fair != "Optimal":
    raise ValueError("Mô hình vẫn không khả thi. Cần giảm lambda hoặc nới trần ngân sách vùng.")

print(f"Giá trị tối ưu Z* có công bằng = {z_fair:,.4f}")
display(result_fair.round(2))

region_total_fair = result_fair.sum(axis=1)
item_total_fair = result_fair.sum(axis=0)

summary_region_df = pd.DataFrame({
    "Vùng": region_total_fair.index,
    "Tổng ngân sách": region_total_fair.values
}).sort_values("Tổng ngân sách", ascending=False)

summary_item_df = pd.DataFrame({
    "Hạng mục": item_total_fair.index,
    "Tổng ngân sách": item_total_fair.values
}).sort_values("Tổng ngân sách", ascending=False)

print("Tổng ngân sách theo vùng:")
display(summary_region_df.round(2))

print("Tổng ngân sách theo hạng mục:")
display(summary_item_df.round(2))

# ============================================================
# 7. CÂU 4.4.2 — GIẢI LẠI BẰNG CVXPY
# ============================================================

print("""
============================================================
7. CÂU 4.4.2 — GIẢI LẠI BẰNG CVXPY
============================================================
""")

def solve_cvxpy(use_fairness=True, lam=0.65):
    beta_matrix = np.array([[beta[(r,j)] for j in items] for r in regions])
    D0_vec = np.array([D0[r] for r in regions])

    X = cp.Variable((6,4), nonneg=True)

    objective = cp.Maximize(cp.sum(cp.multiply(beta_matrix, X)))

    constraints = []

    constraints.append(cp.sum(X) <= total_budget)

    for i in range(6):
        constraints.append(cp.sum(X[i, :]) >= min_region_budget)
        constraints.append(cp.sum(X[i, :]) <= max_region_budget)

    constraints.append(cp.sum(X[:, 3]) >= min_human_budget)

    if use_fairness:
        M = cp.Variable(nonneg=True)

        for i in range(6):
            constraints.append(D0_vec[i] + gamma * X[i, 1] <= M)

        for i in range(6):
            constraints.append(D0_vec[i] + gamma * X[i, 1] >= lam * M)

    prob = cp.Problem(objective, constraints)

    try:
        prob.solve(solver=cp.CLARABEL)
    except:
        prob.solve(solver=cp.SCS)

    if prob.status not in ["optimal", "optimal_inaccurate"]:
        return None, None, prob.status

    result = pd.DataFrame(
        X.value,
        index=[region_names[r] for r in regions],
        columns=[item_names[j] for j in items]
    )

    return result, prob.value, prob.status

result_cvx, z_cvx, status_cvx = solve_cvxpy(
    use_fairness=True,
    lam=lambda_adjusted
)

print("Trạng thái CVXPY:", status_cvx)

if status_cvx not in ["optimal", "optimal_inaccurate"]:
    print("CVXPY báo mô hình không khả thi.")
else:
    print(f"Giá trị tối ưu Z* theo CVXPY = {z_cvx:,.4f}")
    display(result_cvx.round(2))

compare_solver_df = pd.DataFrame({
    "Chỉ tiêu": ["Z* PuLP", "Z* CVXPY", "Chênh lệch tuyệt đối"],
    "Giá trị": [z_fair, z_cvx, abs(z_fair - z_cvx)]
})

display(compare_solver_df.round(4))

print("""
Nhận xét:
Sau khi điều chỉnh lambda xuống 0.65, cả PuLP và CVXPY đều tìm được nghiệm tối ưu.
Hai giá trị Z* gần giống nhau, chứng tỏ mô hình được cài đặt nhất quán giữa hai solver.
""")

# ============================================================
# 8. CÂU 4.4.3 — HEATMAP VÀ BIỂU ĐỒ PHÂN BỔ
# ============================================================

print("""
============================================================
8. CÂU 4.4.3 — HEATMAP PHÂN BỔ TỐI ƯU
============================================================
""")

plt.figure(figsize=(12,6))
sns.heatmap(result_fair, annot=True, fmt=".0f", cmap="Blues")
plt.title("Heatmap phân bổ ngân sách tối ưu có ràng buộc công bằng")
plt.xlabel("Hạng mục đầu tư")
plt.ylabel("Vùng")
plt.show()

plt.figure(figsize=(11,5))
plt.bar(summary_region_df["Vùng"], summary_region_df["Tổng ngân sách"])
plt.title("Tổng ngân sách phân bổ theo vùng")
plt.ylabel("Tỷ VND")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(9,5))
plt.bar(summary_item_df["Hạng mục"], summary_item_df["Tổng ngân sách"])
plt.title("Tổng ngân sách phân bổ theo hạng mục")
plt.ylabel("Tỷ VND")
plt.xticks(rotation=15)
plt.grid(axis="y")
plt.show()

result_fair.plot(kind="bar", stacked=True, figsize=(13,6))
plt.title("Cơ cấu phân bổ ngân sách theo vùng và hạng mục")
plt.ylabel("Tỷ VND")
plt.xlabel("Vùng")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

top_region = region_total_fair.idxmax()
top_item = item_total_fair.idxmax()

print(f"""
Nhận xét:
- Vùng nhận ngân sách lớn nhất là: {top_region}
- Hạng mục nhận tổng ngân sách lớn nhất là: {top_item}
""")

# ============================================================
# 9. CÂU 4.4.4 — SO SÁNH CÓ/KHÔNG CÔNG BẰNG
# ============================================================

print("""
============================================================
9. CÂU 4.4.4 — SO SÁNH VỚI MÔ HÌNH KHÔNG CÓ RÀNG BUỘC CÔNG BẰNG
============================================================
""")

result_no_fair, z_no_fair, status_no_fair, model_no_fair = solve_pulp(
    use_fairness=False,
    lam=lambda_adjusted,
    max_region_cap=max_region_budget
)

print("Trạng thái nghiệm không công bằng:", status_no_fair)

if status_no_fair != "Optimal":
    raise ValueError("Mô hình không công bằng không tối ưu.")

loss_fairness = z_no_fair - z_fair
loss_pct = loss_fairness / z_no_fair * 100

print(f"Z* có công bằng     = {z_fair:,.4f}")
print(f"Z* không công bằng  = {z_no_fair:,.4f}")
print(f"Chi phí công bằng   = {loss_fairness:,.4f}")
print(f"Tỷ lệ giảm Z*       = {loss_pct:.4f}%")

display(result_no_fair.round(2))

compare_fairness_df = pd.DataFrame({
    "Chỉ tiêu": [
        "Z* có ràng buộc công bằng",
        "Z* không có công bằng",
        "Chi phí kinh tế của công bằng",
        "Tỷ lệ giảm Z* (%)"
    ],
    "Giá trị": [z_fair, z_no_fair, loss_fairness, loss_pct]
})

display(compare_fairness_df.round(4))

compare_region_df = pd.DataFrame({
    "Có công bằng": result_fair.sum(axis=1),
    "Không công bằng": result_no_fair.sum(axis=1)
})

display(compare_region_df.round(2))

compare_region_df.plot(kind="bar", figsize=(12,6))
plt.title("So sánh tổng ngân sách theo vùng: có và không có công bằng")
plt.ylabel("Tỷ VND")
plt.xlabel("Vùng")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# So sánh Digital Index sau đầu tư
compare_D_df = pd.DataFrame({
    "D ban đầu": [D0[r] for r in regions],
    "D sau đầu tư có công bằng": [
        D0[r] + gamma * result_fair.loc[region_names[r], "CĐS doanh nghiệp"]
        for r in regions
    ],
    "D sau đầu tư không công bằng": [
        D0[r] + gamma * result_no_fair.loc[region_names[r], "CĐS doanh nghiệp"]
        for r in regions
    ],
}, index=[region_names[r] for r in regions])

display(compare_D_df.round(2))

compare_D_df.plot(kind="bar", figsize=(13,6))
plt.title("So sánh Digital Index trước và sau đầu tư")
plt.ylabel("Digital Index")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 10. MỞ RỘNG — CHI PHÍ CỦA TRẦN NGÂN SÁCH VÙNG
# ============================================================

print("""
============================================================
10. MỞ RỘNG — CHI PHÍ CỦA TRẦN NGÂN SÁCH VÙNG C3
============================================================
""")

result_no_cap, z_no_cap, status_no_cap, _ = solve_pulp(
    use_fairness=True,
    lam=lambda_adjusted,
    max_region_cap=50000
)

if status_no_cap == "Optimal":
    cap_cost = z_no_cap - z_fair
    cap_cost_pct = cap_cost / z_no_cap * 100

    cap_compare_df = pd.DataFrame({
        "Chỉ tiêu": [
            "Z* có trần vùng 12.000",
            "Z* nới trần vùng",
            "Chi phí của trần vùng",
            "Tỷ lệ giảm Z* (%)"
        ],
        "Giá trị": [z_fair, z_no_cap, cap_cost, cap_cost_pct]
    })

    display(cap_compare_df.round(4))

    print(f"""
Ràng buộc trần vùng C3 làm giảm Z* khoảng {cap_cost:,.4f},
tương đương {cap_cost_pct:.4f}% so với trường hợp nới trần.
""")
else:
    print("Mô hình nới trần vùng không khả thi hoặc không tối ưu.")

# ============================================================
# 11. MỞ RỘNG — HIỆU QUẢ GDP GAIN THEO VÙNG
# ============================================================

print("""
============================================================
11. MỞ RỘNG — HIỆU QUẢ GDP GAIN THEO VÙNG
============================================================
""")

gdp_gain_by_region = []

for r in regions:
    gain = 0
    for j in items:
        gain += beta[(r,j)] * result_fair.loc[region_names[r], item_names[j]]
    gdp_gain_by_region.append(gain)

region_efficiency_df = pd.DataFrame({
    "Vùng": [region_names[r] for r in regions],
    "Tổng ngân sách": result_fair.sum(axis=1).values,
    "GDP gain": gdp_gain_by_region
})

region_efficiency_df["GDP gain / ngân sách"] = (
    region_efficiency_df["GDP gain"] / region_efficiency_df["Tổng ngân sách"]
)

display(region_efficiency_df.round(4))

plt.figure(figsize=(11,5))
plt.bar(region_efficiency_df["Vùng"], region_efficiency_df["GDP gain / ngân sách"])
plt.title("Hiệu quả GDP gain trên mỗi đơn vị ngân sách theo vùng")
plt.ylabel("GDP gain / ngân sách")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 12. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
12. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

top_region_no_fair = result_no_fair.sum(axis=1).idxmax()

central_highland_AI = result_fair.loc["Tây Nguyên", "Năng lực AI"]
central_highland_I = result_fair.loc["Tây Nguyên", "Hạ tầng số"]
central_highland_H = result_fair.loc["Tây Nguyên", "Nhân lực số"]

print(f"""
1. Vì sao phải sửa lambda từ 0.70 xuống 0.65?

Với lambda = 0.70, ràng buộc công bằng yêu cầu các vùng có Digital Index thấp
phải đạt ít nhất 70% mức cao nhất. Trong dữ liệu, Tây Nguyên có D0 = 32,
trong khi Đông Nam Bộ có D0 = 82.

Khi đó, Tây Nguyên cần đầu tư vào D ít nhất khoảng 12.700 tỷ VND.
Nhưng trần ngân sách toàn vùng chỉ là 12.000 tỷ VND.
Vì vậy, mô hình gốc không khả thi.

Việc giảm lambda xuống 0.65 là điều chỉnh kỹ thuật hợp lý để bảo đảm mô hình
có nghiệm, đồng thời vẫn giữ tinh thần công bằng vùng miền.

2. Nếu bỏ ràng buộc công bằng, vốn sẽ chảy về vùng nào?

Khi bỏ ràng buộc công bằng, vùng nhận ngân sách lớn nhất là:

{top_region_no_fair}

Điều này xảy ra vì mô hình ưu tiên các vùng và hạng mục có hệ số beta cao.
Tuy nhiên, điều này có thể làm tăng khoảng cách số giữa các vùng.

3. Chi phí kinh tế của công bằng vùng miền là bao nhiêu?

Chi phí công bằng = {loss_fairness:,.4f}
Tỷ lệ giảm Z* = {loss_pct:.4f}%

Điều này phản ánh đánh đổi giữa hiệu quả kinh tế và công bằng vùng miền.

4. Tây Nguyên nên đầu tư AI hay H và I trước?

Tây Nguyên có hệ số AI thấp, chỉ 0.45, trong khi hệ số H là 1.35 và I là 1.20.

Kết quả tối ưu cho Tây Nguyên:
- Đầu tư AI: {central_highland_AI:,.2f}
- Đầu tư hạ tầng số I: {central_highland_I:,.2f}
- Đầu tư nhân lực số H: {central_highland_H:,.2f}

Mô hình cho thấy Tây Nguyên nên ưu tiên nhân lực số và hạ tầng số trước,
thay vì đầu tư trực tiếp mạnh vào AI.
""")

# ============================================================
# 13. KẾT LUẬN
# ============================================================

print("""
============================================================
13. KẾT LUẬN
============================================================

Bài 4 đã xây dựng mô hình quy hoạch tuyến tính để phân bổ ngân sách số
theo vùng và hạng mục đầu tư.

Trong quá trình kiểm tra, mô hình gốc với lambda = 0.70 bị infeasible do
ràng buộc công bằng quá chặt so với trần ngân sách vùng. Đây là một phát hiện
quan trọng, vì nó cho thấy các ràng buộc chính sách nếu đặt không phù hợp
có thể làm bài toán không khả thi.

Sau khi điều chỉnh lambda xuống 0.65, mô hình có nghiệm tối ưu.
Kết quả từ PuLP và CVXPY gần tương đồng, cho thấy mô hình được cài đặt nhất quán.

So sánh mô hình có và không có công bằng cho thấy công bằng vùng miền có
chi phí kinh tế nhất định, nhưng giúp giảm nguy cơ vốn tập trung quá mức
vào các vùng đã phát triển.

Về chính sách, mô hình khuyến nghị các vùng có Digital Index thấp nên ưu tiên
hạ tầng số và nhân lực số trước khi mở rộng đầu tư AI.
""")

