# -*- coding: utf-8 -*-
"""Bài 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oxxr3XZ9ePJ25UM3q4gn5VoTdrpGdrbc
"""

# ============================================================
# BÀI 12 — AIDEOM-VN POLICY LAB
# Đồ án tích hợp: nguyên mẫu mô hình hỗ trợ ra quyết định kinh tế số Việt Nam
# Google Colab version
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH
# ============================================================

print("""
============================================================
0. BỐI CẢNH ĐỒ ÁN AIDEOM-VN
============================================================

AIDEOM-VN là nguyên mẫu hệ thống hỗ trợ ra quyết định chính sách kinh tế số
cho Việt Nam. Mô hình tích hợp các kỹ thuật đã học từ Bài 1 đến Bài 11:

M1. Dự báo kinh tế vĩ mô
M2. Đánh giá sẵn sàng số theo vùng
M3. Mô phỏng phân bổ ngân sách
M4. Mô phỏng tác động lao động
M5. Đánh giá rủi ro chính sách
M6. Dashboard hỗ trợ ra quyết định

Mục tiêu không phải thay thế nhà hoạch định chính sách, mà giúp minh bạch hóa
các đánh đổi giữa tăng trưởng, việc làm, rủi ro, chuyển đổi số và AI.
""")

# ============================================================
# 1. KỊCH BẢN CHÍNH SÁCH
# ============================================================

scenarios = {
    "S1": {
        "name": "S1 - Truyền thống",
        "desc": "Tập trung vốn vật chất, FDI, hạ tầng truyền thống, xuất khẩu",
        "alloc": np.array([0.70, 0.10, 0.10, 0.10])
    },
    "S2": {
        "name": "S2 - Số hóa nhanh",
        "desc": "Tăng đầu tư chính phủ số, doanh nghiệp số, thanh toán số",
        "alloc": np.array([0.25, 0.45, 0.15, 0.15])
    },
    "S3": {
        "name": "S3 - AI dẫn dắt",
        "desc": "Ưu tiên AI, dữ liệu lớn, bán dẫn, trung tâm dữ liệu",
        "alloc": np.array([0.20, 0.20, 0.45, 0.15])
    },
    "S4": {
        "name": "S4 - Bao trùm số",
        "desc": "Ưu tiên vùng yếu, SME, giáo dục số, nông nghiệp số",
        "alloc": np.array([0.30, 0.20, 0.10, 0.40])
    },
    "S5": {
        "name": "S5 - Tối ưu cân bằng",
        "desc": "Kịch bản cân bằng từ logic AIDEOM-VN",
        "alloc": np.array([0.40, 0.25, 0.15, 0.20])
    }
}

alloc_df = pd.DataFrame({
    s: scenarios[s]["alloc"] for s in scenarios
}, index=["K", "D", "AI", "H"]).T

alloc_df["Tên kịch bản"] = [scenarios[s]["name"] for s in scenarios]
alloc_df = alloc_df[["Tên kịch bản", "K", "D", "AI", "H"]]

print("""
============================================================
1. NĂM KỊCH BẢN CHÍNH SÁCH
============================================================
""")

display(alloc_df)

alloc_plot = alloc_df.set_index("Tên kịch bản")[["K", "D", "AI", "H"]]
alloc_plot.plot(kind="bar", stacked=True, figsize=(12,6))
plt.title("Cơ cấu phân bổ ngân sách theo 5 kịch bản")
plt.ylabel("Tỷ trọng ngân sách")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 2. M1 — DỰ BÁO KINH TẾ VĨ MÔ
# ============================================================

print("""
============================================================
2. M1 — DỰ BÁO KINH TẾ VĨ MÔ 2026-2030
============================================================
""")

def simulate_macro(allocation, years=np.arange(2026, 2031)):
    K = 27500.0
    D = 20.3
    AI = 86.0
    H = 30.0
    A = 35.0
    L = 54.0

    alpha_K, alpha_L, alpha_D, alpha_AI, alpha_H = 0.33, 0.42, 0.10, 0.08, 0.07

    rows = []

    for t, year in enumerate(years):
        budget = 1000
        IK, ID, IAI, IH = allocation * budget

        K = 0.95*K + IK
        D = 0.88*D + ID/100
        AI = 0.85*AI + IAI/20
        H = 0.98*H + IH/200

        A = A * (1 + 0.0008*D + 0.0005*AI + 0.0010*H)

        Y = A * (K**alpha_K) * (L**alpha_L) * (D**alpha_D) * (AI**alpha_AI) * (H**alpha_H)

        rows.append({
            "Year": year,
            "K": K,
            "D": D,
            "AI": AI,
            "H": H,
            "TFP_A": A,
            "GDP_forecast": Y
        })

    return pd.DataFrame(rows)

macro_results = {}

for s in scenarios:
    macro_results[s] = simulate_macro(scenarios[s]["alloc"])

macro_summary = []

for s, df_s in macro_results.items():
    last = df_s.iloc[-1]
    macro_summary.append({
        "Kịch bản": scenarios[s]["name"],
        "GDP 2030": last["GDP_forecast"],
        "K 2030": last["K"],
        "D 2030": last["D"],
        "AI 2030": last["AI"],
        "H 2030": last["H"],
        "TFP 2030": last["TFP_A"]
    })

macro_summary_df = pd.DataFrame(macro_summary)
display(macro_summary_df.round(3))

plt.figure(figsize=(12,6))
for s, df_s in macro_results.items():
    plt.plot(df_s["Year"], df_s["GDP_forecast"], marker="o", linewidth=2, label=scenarios[s]["name"])
plt.title("M1 - Dự báo GDP 2026-2030 theo 5 kịch bản")
plt.xlabel("Năm")
plt.ylabel("GDP dự báo")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# 3. M2 — ĐÁNH GIÁ SẴN SÀNG SỐ THEO VÙNG
# ============================================================

print("""
============================================================
3. M2 — ĐÁNH GIÁ SẴN SÀNG SỐ THEO VÙNG
============================================================
""")

regions_df = pd.DataFrame({
    "Vùng": [
        "Trung du miền núi phía Bắc",
        "Đồng bằng sông Hồng",
        "Bắc Trung Bộ + DH Trung Bộ",
        "Tây Nguyên",
        "Đông Nam Bộ",
        "Đồng bằng sông Cửu Long"
    ],
    "Digital_Index": [38, 78, 55, 32, 82, 48],
    "AI_Readiness": [22, 68, 40, 18, 75, 30],
    "Internet": [72, 92, 84, 68, 94, 78],
    "Labor_Trained": [21.5, 36.8, 27.5, 18.2, 42.5, 16.8],
    "Gini": [0.405, 0.358, 0.372, 0.412, 0.385, 0.392]
})

def norm_good(x):
    return (x - x.min()) / (x.max() - x.min())

def norm_bad(x):
    return (x.max() - x) / (x.max() - x.min())

regions_df["Digital_norm"] = norm_good(regions_df["Digital_Index"])
regions_df["AI_norm"] = norm_good(regions_df["AI_Readiness"])
regions_df["Internet_norm"] = norm_good(regions_df["Internet"])
regions_df["Labor_norm"] = norm_good(regions_df["Labor_Trained"])
regions_df["Gini_norm"] = norm_bad(regions_df["Gini"])

regions_df["Regional_Readiness"] = (
    0.30*regions_df["Digital_norm"]
    + 0.30*regions_df["AI_norm"]
    + 0.15*regions_df["Internet_norm"]
    + 0.15*regions_df["Labor_norm"]
    + 0.10*regions_df["Gini_norm"]
)

regions_rank = regions_df.sort_values("Regional_Readiness", ascending=False).reset_index(drop=True)
regions_rank["Rank"] = regions_rank.index + 1

display(regions_rank[["Rank", "Vùng", "Digital_Index", "AI_Readiness", "Regional_Readiness"]].round(4))

plt.figure(figsize=(11,5))
plt.barh(regions_rank["Vùng"], regions_rank["Regional_Readiness"])
plt.gca().invert_yaxis()
plt.title("M2 - Xếp hạng sẵn sàng số theo vùng")
plt.xlabel("Regional Readiness Score")
plt.grid(axis="x")
plt.show()

# ============================================================
# 4. M3 — PHÂN BỔ NGÂN SÁCH THEO KỊCH BẢN
# ============================================================

print("""
============================================================
4. M3 — PHÂN BỔ NGÂN SÁCH THEO KỊCH BẢN
============================================================
""")

total_budget = 50000

budget_rows = []

for s in scenarios:
    alloc = scenarios[s]["alloc"]
    budget_rows.append({
        "Kịch bản": scenarios[s]["name"],
        "K": alloc[0]*total_budget,
        "D": alloc[1]*total_budget,
        "AI": alloc[2]*total_budget,
        "H": alloc[3]*total_budget,
        "Tổng": total_budget
    })

budget_df = pd.DataFrame(budget_rows)
display(budget_df.round(2))

budget_df.set_index("Kịch bản")[["K", "D", "AI", "H"]].plot(kind="bar", stacked=True, figsize=(12,6))
plt.title("M3 - Phân bổ ngân sách 50.000 tỷ VND theo kịch bản")
plt.ylabel("Tỷ VND")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 5. M4 — 9 NGÀNH VÀ CHÍNH SÁCH RIÊNG TỪNG NGÀNH
# ============================================================

print("""
============================================================
5. M4 — 9 NGÀNH CHIẾN LƯỢC VÀ CHÍNH SÁCH RIÊNG
============================================================
""")

sector_df = pd.DataFrame({
    "Ngành": [
        "Nông-Lâm-Thủy sản",
        "CN chế biến chế tạo",
        "Xây dựng",
        "Bán buôn-bán lẻ",
        "Tài chính-Ngân hàng",
        "Logistics-Vận tải",
        "CNTT-Truyền thông",
        "Giáo dục-Đào tạo",
        "Y tế"
    ],
    "Growth": [3.27, 9.64, 7.45, 7.10, 7.36, 9.93, 7.85, 6.42, 6.85],
    "Productivity": [103.4, 241.2, 168.8, 145.3, 1072.4, 321.4, 713.8, 205.7, 437.1],
    "Spillover": [0.35, 0.78, 0.42, 0.55, 0.85, 0.72, 0.92, 0.65, 0.60],
    "Export": [40.5, 290.9, 2.5, 5.5, 1.2, 3.1, 178.0, 0.0, 0.0],
    "Labor": [13.20, 11.50, 4.80, 7.80, 0.55, 1.95, 0.62, 2.15, 0.75],
    "AI_Readiness": [15, 55, 20, 48, 72, 42, 88, 38, 45],
    "Automation_Risk": [18, 42, 25, 38, 52, 35, 28, 22, 18]
})

sector_df["Growth_norm"] = norm_good(sector_df["Growth"])
sector_df["Productivity_norm"] = norm_good(sector_df["Productivity"])
sector_df["Spillover_norm"] = norm_good(sector_df["Spillover"])
sector_df["Export_norm"] = norm_good(sector_df["Export"])
sector_df["Labor_norm"] = norm_good(sector_df["Labor"])
sector_df["AI_norm"] = norm_good(sector_df["AI_Readiness"])
sector_df["Risk_norm"] = norm_good(sector_df["Automation_Risk"])

sector_df["Priority_Score"] = (
    0.15*sector_df["Growth_norm"]
    + 0.15*sector_df["Productivity_norm"]
    + 0.20*sector_df["Spillover_norm"]
    + 0.15*sector_df["Export_norm"]
    + 0.10*sector_df["Labor_norm"]
    + 0.20*sector_df["AI_norm"]
    - 0.15*sector_df["Risk_norm"]
)

sector_df["Labor_Vulnerability"] = (
    0.60*sector_df["Labor_norm"]
    + 0.40*sector_df["Risk_norm"]
)

def assign_policy_group(row):
    if row["AI_Readiness"] >= 70 and row["Spillover"] >= 0.80:
        return "A - Dẫn dắt AI"
    elif row["Automation_Risk"] >= 40 and row["Labor"] >= 5:
        return "B - Rủi ro tự động hóa cao"
    elif row["Labor"] >= 7:
        return "C - Bao trùm lao động lớn"
    elif row["Spillover"] >= 0.70:
        return "D - Lan tỏa chuỗi giá trị"
    else:
        return "E - Chuyển đổi có chọn lọc"

def policy_recommendation(row):
    group = row["Policy_Group"]

    if group == "A - Dẫn dắt AI":
        return "Ưu tiên AI, dữ liệu lớn, R&D, sandbox và tiêu chuẩn an toàn dữ liệu."
    if group == "B - Rủi ro tự động hóa cao":
        return "Gắn AI với đào tạo lại, chuyển đổi nghề, bảo hiểm thất nghiệp chủ động."
    if group == "C - Bao trùm lao động lớn":
        return "Ưu tiên công nghệ hỗ trợ lao động, thương mại điện tử, kỹ năng số cơ bản."
    if group == "D - Lan tỏa chuỗi giá trị":
        return "Đầu tư dữ liệu chuỗi cung ứng, logistics số, nền tảng kết nối doanh nghiệp."
    return "Triển khai số hóa có chọn lọc, tránh đầu tư dàn trải, ưu tiên dự án chi phí thấp."

sector_df["Policy_Group"] = sector_df.apply(assign_policy_group, axis=1)
sector_df["Policy_Recommendation"] = sector_df.apply(policy_recommendation, axis=1)

sector_rank = sector_df.sort_values("Priority_Score", ascending=False).reset_index(drop=True)
sector_rank["Rank"] = sector_rank.index + 1

display(sector_rank[[
    "Rank", "Ngành", "Priority_Score", "Labor_Vulnerability",
    "Policy_Group", "Policy_Recommendation"
]].round(4))

plt.figure(figsize=(12,6))
plt.barh(sector_rank["Ngành"], sector_rank["Priority_Score"])
plt.gca().invert_yaxis()
plt.title("M4 - Xếp hạng ưu tiên chính sách theo 9 ngành")
plt.xlabel("Priority Score")
plt.grid(axis="x")
plt.show()

plt.figure(figsize=(10,6))
plt.scatter(
    sector_df["AI_Readiness"],
    sector_df["Automation_Risk"],
    s=sector_df["Labor"]*80,
    alpha=0.7
)
for _, row in sector_df.iterrows():
    plt.text(row["AI_Readiness"]+0.5, row["Automation_Risk"]+0.5, row["Ngành"], fontsize=9)
plt.title("Bản đồ ngành: AI Readiness - Automation Risk")
plt.xlabel("AI Readiness")
plt.ylabel("Automation Risk (%)")
plt.grid(True)
plt.show()

# ============================================================
# 6. M5 — MÔ PHỎNG NETJOB VÀ RỦI RO THEO KỊCH BẢN
# ============================================================

print("""
============================================================
6. M5 — NETJOB VÀ RỦI RO THEO KỊCH BẢN
============================================================
""")

risk = sector_df["Automation_Risk"].values / 100
a1 = np.array([8.5, 32.5, 12.8, 22.4, 45.8, 28.5, 62.5, 18.5, 20.0])
b1 = np.array([45.0, 28.0, 35.0, 32.0, 22.0, 30.0, 20.0, 55.0, 40.0])
c1 = np.array([5.2, 62.4, 18.5, 48.2, 72.5, 42.8, 32.5, 12.5, 15.0])

def simulate_labor(allocation):
    labor_budget = 30000
    x_AI_total = allocation[2] * labor_budget
    x_H_total = allocation[3] * labor_budget

    x_AI = x_AI_total * a1 / a1.sum()
    x_H = x_H_total * b1 / b1.sum()

    newjob = a1 * x_AI
    upgrade = b1 * x_H
    displaced = c1 * risk * x_AI
    netjob = newjob + upgrade - displaced

    return pd.DataFrame({
        "Ngành": sector_df["Ngành"],
        "x_AI": x_AI,
        "x_H": x_H,
        "NewJob": newjob,
        "UpgradeJob": upgrade,
        "DisplacedJob": displaced,
        "NetJob": netjob
    })

def assess_risk(allocation):
    K, D, AI, H = allocation
    cyber = max(0, 100*(0.55*AI + 0.25*D - 0.30*H))
    emission = max(0, 100*(0.50*K + 0.40*AI - 0.20*D))
    dependency = max(0, 100*(0.45*AI + 0.30*D - 0.20*H))
    total = 0.40*cyber + 0.35*emission + 0.25*dependency
    return cyber, emission, dependency, total

labor_summary_rows = []
risk_rows = {}

for s in scenarios:
    alloc = scenarios[s]["alloc"]
    labor_s = simulate_labor(alloc)
    cyber, emission, dependency, total_risk = assess_risk(alloc)

    labor_summary_rows.append({
        "Kịch bản": scenarios[s]["name"],
        "Total NewJob": labor_s["NewJob"].sum(),
        "Total UpgradeJob": labor_s["UpgradeJob"].sum(),
        "Total DisplacedJob": labor_s["DisplacedJob"].sum(),
        "Total NetJob": labor_s["NetJob"].sum(),
        "Cyber Risk": cyber,
        "Emission Risk": emission,
        "Dependency Risk": dependency,
        "Total Risk": total_risk
    })

labor_risk_df = pd.DataFrame(labor_summary_rows)
display(labor_risk_df.round(2))

plt.figure(figsize=(12,6))
plt.bar(labor_risk_df["Kịch bản"], labor_risk_df["Total NetJob"])
plt.title("M5 - Total NetJob theo kịch bản")
plt.ylabel("Việc làm ròng")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

labor_risk_df.set_index("Kịch bản")[["Cyber Risk", "Emission Risk", "Dependency Risk"]].plot(kind="bar", figsize=(12,6))
plt.title("M5 - Rủi ro theo kịch bản")
plt.ylabel("Risk score")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 7. M6 — AIDEOM SCORE VÀ BẢNG RA QUYẾT ĐỊNH
# ============================================================

print("""
============================================================
7. M6 — AIDEOM SCORE VÀ BẢNG RA QUYẾT ĐỊNH
============================================================
""")

summary = macro_summary_df[["Kịch bản", "GDP 2030", "D 2030", "AI 2030", "H 2030"]].merge(
    labor_risk_df[["Kịch bản", "Total NetJob", "Total Risk"]],
    on="Kịch bản"
)

summary["GDP_norm"] = norm_good(summary["GDP 2030"])
summary["NetJob_norm"] = norm_good(summary["Total NetJob"])
summary["Risk_norm"] = norm_bad(summary["Total Risk"])

summary["AIDEOM_Score"] = (
    0.45*summary["GDP_norm"]
    + 0.30*summary["NetJob_norm"]
    + 0.25*summary["Risk_norm"]
)

summary_rank = summary.sort_values("AIDEOM_Score", ascending=False).reset_index(drop=True)
summary_rank["Rank"] = summary_rank.index + 1

display(summary_rank[[
    "Rank", "Kịch bản", "GDP 2030", "Total NetJob", "Total Risk", "AIDEOM_Score"
]].round(4))

plt.figure(figsize=(12,6))
plt.barh(summary_rank["Kịch bản"], summary_rank["AIDEOM_Score"])
plt.gca().invert_yaxis()
plt.title("M6 - Xếp hạng 5 kịch bản theo AIDEOM Score")
plt.xlabel("AIDEOM Score")
plt.grid(axis="x")
plt.show()

summary_rank.set_index("Kịch bản")[["GDP_norm", "NetJob_norm", "Risk_norm", "AIDEOM_Score"]].plot(
    kind="bar",
    figsize=(12,6)
)
plt.title("So sánh chuẩn hóa GDP - NetJob - Risk - AIDEOM Score")
plt.ylabel("Điểm chuẩn hóa")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 8. CẢNH BÁO RỦI RO TỰ ĐỘNG
# ============================================================

print("""
============================================================
8. HỆ THỐNG CẢNH BÁO RỦI RO
============================================================
""")

warnings = []

for _, row in summary_rank.iterrows():
    if row["Total Risk"] > summary["Total Risk"].median():
        warnings.append(f"{row['Kịch bản']}: rủi ro tổng hợp cao, cần tăng H hoặc giảm tốc độ AI/K.")
    if row["Total NetJob"] < summary["Total NetJob"].median():
        warnings.append(f"{row['Kịch bản']}: NetJob thấp, cần bổ sung chính sách đào tạo lại lao động.")
    if row["GDP 2030"] < summary["GDP 2030"].median():
        warnings.append(f"{row['Kịch bản']}: GDP 2030 thấp, cần tăng đầu tư năng suất.")

for w in warnings:
    print("⚠", w)

# ============================================================
# 9. AI POLICY AGENT GIẢ LẬP
# ============================================================

print("""
============================================================
9. AI POLICY AGENT — PHÂN TÍCH TỰ ĐỘNG
============================================================
""")

best = summary_rank.iloc[0]
best_name = best["Kịch bản"]

highest_gdp = summary.sort_values("GDP 2030", ascending=False).iloc[0]["Kịch bản"]
highest_jobs = summary.sort_values("Total NetJob", ascending=False).iloc[0]["Kịch bản"]
lowest_risk = summary.sort_values("Total Risk", ascending=True).iloc[0]["Kịch bản"]

top_sector = sector_rank.iloc[0]["Ngành"]
high_risk_sector = sector_df.sort_values("Automation_Risk", ascending=False).iloc[0]["Ngành"]

print(f"""
AIDEOM-VN Policy Agent nhận định:

1. Kịch bản tổng hợp tốt nhất hiện tại là: {best_name}
với AIDEOM Score = {best['AIDEOM_Score']:.4f}.

2. Tuy nhiên, các mục tiêu có đánh đổi:
- GDP 2030 cao nhất thuộc về: {highest_gdp}
- NetJob cao nhất thuộc về: {highest_jobs}
- Rủi ro thấp nhất thuộc về: {lowest_risk}

3. Ngành ưu tiên cao nhất theo chỉ số Priority là: {top_sector}.
Ngành có rủi ro tự động hóa cao nhất là: {high_risk_sector}.

4. Khuyến nghị chính sách:
Việt Nam không nên theo đuổi kịch bản AI dẫn dắt một cách cực đoan nếu chưa có đủ
nền tảng nhân lực số, an ninh dữ liệu và cơ chế đào tạo lại lao động.

Chiến lược phù hợp hơn là kết hợp:
- đầu tư hạ tầng số,
- AI có kiểm soát,
- phát triển nhân lực số,
- chính sách chuyển đổi lao động theo ngành,
- và hệ thống cảnh báo rủi ro sớm.

5. AIDEOM-VN nên được sử dụng như hệ thống hỗ trợ ra quyết định, không thay thế
quyết định chính trị - xã hội của Chính phủ, Quốc hội và các bên liên quan.
""")

# ============================================================
# 10. HƯỚNG MỞ RỘNG NGHIÊN CỨU SAU ĐỒ ÁN
# ============================================================

print("""
============================================================
10. HƯỚNG MỞ RỘNG NGHIÊN CỨU SAU ĐỒ ÁN
============================================================
""")

future_research = pd.DataFrame({
    "Hướng mở rộng": [
        "Bài báo SCIE Q2-Q3",
        "Mở rộng sang CGE hoặc DSGE-AI",
        "Tích hợp dữ liệu thời gian thực",
        "Multi-Agent Reinforcement Learning"
    ],
    "Mô tả": [
        "Chọn một use case cụ thể như ĐBSCL hoặc ngành chế biến chế tạo để viết bài nghiên cứu định lượng.",
        "Mở rộng từ mô hình tối ưu cục bộ sang cân bằng tổng thể để đánh giá tác động liên ngành.",
        "Kết nối Open Data Portal, Vietstock, hải quan, dữ liệu lao động để cập nhật theo tháng/quý.",
        "Mở rộng Q-learning thành môi trường nhiều agent đại diện cho các bộ, ngành, vùng và doanh nghiệp."
    ],
    "Giá trị học thuật": [
        "Tạo sản phẩm nghiên cứu có thể công bố.",
        "Tăng độ chặt chẽ kinh tế học và mô phỏng chính sách vĩ mô.",
        "Biến AIDEOM-VN thành hệ thống policy intelligence cập nhật liên tục.",
        "Mô phỏng xung đột lợi ích và phối hợp chính sách giữa nhiều tác nhân."
    ]
})

display(future_research)

# ============================================================
# 11. KẾT LUẬN
# ============================================================

print("""
============================================================
11. KẾT LUẬN
============================================================

Bài 12 đã xây dựng nguyên mẫu AIDEOM-VN Policy Lab, tích hợp các kỹ thuật
từ Bài 1 đến Bài 11 thành một hệ thống hỗ trợ ra quyết định.

Hệ thống gồm 6 module:
M1 dự báo kinh tế vĩ mô,
M2 đánh giá sẵn sàng số,
M3 mô phỏng phân bổ ngân sách,
M4 khuyến nghị chính sách theo 9 ngành,
M5 mô phỏng lao động và rủi ro,
M6 bảng tổng hợp AIDEOM Score và policy agent.

Điểm mạnh của AIDEOM-VN là không chỉ tạo ra một kết quả tối ưu duy nhất,
mà cho phép so sánh các kịch bản chính sách, nhận diện đánh đổi,
xác định ngành ưu tiên, cảnh báo rủi ro và đưa ra khuyến nghị chính sách.

Kết quả cho thấy chiến lược tối ưu cho Việt Nam không nên cực đoan theo
một hướng duy nhất, mà cần cân bằng giữa tăng trưởng, chuyển đổi số,
AI, nhân lực số, an sinh lao động và kiểm soát rủi ro.

Sau bước Colab, mô hình này nên được chuyển thành dashboard Streamlit với
các tab:
1. Tổng quan
2. Phân bổ ngân sách
3. Kịch bản so sánh
4. Chính sách theo 9 ngành
5. Lao động và rủi ro
6. AI Policy Agent
""")

