# -*- coding: utf-8 -*-
"""Bài 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XBy5LziXMFTQOYp1a9-Tj05-D2ZWBhIe
"""

# ============================================================
# BÀI 5 — QUY HOẠCH NGUYÊN HỖN HỢP MIP LỰA CHỌN DỰ ÁN CHUYỂN ĐỔI SỐ
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    import seaborn as sns
except ModuleNotFoundError:
    !pip install seaborn
    import seaborn as sns

try:
    import pulp
except ModuleNotFoundError:
    !pip install pulp
    import pulp

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Bài toán xem xét 15 dự án ứng cử cho chương trình chuyển đổi số quốc gia
giai đoạn 2026–2030.

Tổng ngân sách 5 năm là 80.000 tỷ VND. Mỗi dự án có:
- chi phí tổng,
- lợi ích NPV kỳ vọng,
- chi phí giai đoạn năm 1–2,
- chi phí giai đoạn năm 3–5,
- lĩnh vực chính sách,
- và một số ràng buộc đặc thù.

Mục tiêu là chọn tập dự án tối ưu sao cho tổng lợi ích NPV lớn nhất,
đồng thời thỏa mãn ngân sách, ràng buộc loại trừ, ràng buộc tiên quyết
và yêu cầu cân đối lĩnh vực.
""")

# ============================================================
# 1. MÔ HÌNH TOÁN HỌC
# ============================================================

print("""
============================================================
1. MÔ HÌNH TOÁN HỌC
============================================================

Biến quyết định:

y_i ∈ {0,1}

Trong đó:
y_i = 1 nếu chọn dự án i
y_i = 0 nếu không chọn dự án i

Hàm mục tiêu:

Max Z = Σ_i B_i * y_i

Trong đó B_i là lợi ích NPV kỳ vọng của dự án i.

Ràng buộc:

C1. Ngân sách tổng 5 năm:
Σ_i C_i*y_i <= 80000

C2. Ngân sách năm 1–2:
Σ_i C1_i*y_i <= 40000

C3. Loại trừ trung tâm dữ liệu:
y1 + y2 <= 1

C4. Tiên quyết AI quốc gia cần đào tạo kỹ sư:
y8 <= y12

C5. Tiên quyết khu bán dẫn cần đào tạo:
y13 <= y12

C6. Cân đối lĩnh vực:
y4 + y5 >= 1
y14 >= 1

C7. Số lượng dự án:
7 <= Σ_i y_i <= 11
""")

# ============================================================
# 2. DỮ LIỆU ĐẦU VÀO
# ============================================================

print("""
============================================================
2. DỮ LIỆU ĐẦU VÀO
============================================================
""")

projects = list(range(1, 16))

project_name = {
    1: "Trung tâm dữ liệu quốc gia Hòa Lạc",
    2: "Trung tâm dữ liệu quốc gia phía Nam",
    3: "Hệ thống 5G phủ sóng toàn quốc",
    4: "Hệ thống định danh điện tử VNeID 2.0",
    5: "Cổng dịch vụ công quốc gia v3",
    6: "Y tế số quốc gia",
    7: "Giáo dục số K-12 toàn quốc",
    8: "Trung tâm AI quốc gia + supercomputing",
    9: "Sandbox tài chính số",
    10: "Logistics thông minh + cảng biển số",
    11: "Nông nghiệp số ĐBSCL",
    12: "Đào tạo 50.000 kỹ sư AI/bán dẫn",
    13: "Khu CN bán dẫn Bắc Ninh - Bắc Giang",
    14: "An ninh mạng quốc gia SOC",
    15: "Open Data + dữ liệu mở quốc gia"
}

field = {
    1: "Hạ tầng",
    2: "Hạ tầng",
    3: "Hạ tầng",
    4: "Chính phủ số",
    5: "Chính phủ số",
    6: "Y tế số",
    7: "Giáo dục",
    8: "AI",
    9: "Tài chính số",
    10: "Logistics",
    11: "Nông nghiệp",
    12: "Nhân lực",
    13: "Bán dẫn",
    14: "An ninh",
    15: "Dữ liệu"
}

# Chi phí tổng
C = {
    1:12000, 2:11500, 3:18000, 4:4500, 5:3200,
    6:5800, 7:6500, 8:15000, 9:2500, 10:7200,
    11:4800, 12:8500, 13:20000, 14:3800, 15:1500
}

# Chi phí năm 1-2
C1 = {
    1:8500, 2:7500, 3:12000, 4:3500, 5:2500,
    6:4000, 7:4500, 8:9000, 9:1800, 10:5000,
    11:3500, 12:5500, 13:13000, 14:2800, 15:1200
}

# Lợi ích NPV
B = {
    1:21500, 2:20800, 3:32500, 4:9200, 5:6800,
    6:11400, 7:12200, 8:28500, 9:5800, 10:13800,
    11:8500, 12:16200, 13:35000, 14:7500, 15:3800
}

project_df = pd.DataFrame({
    "Mã": [f"P{i}" for i in projects],
    "Tên dự án": [project_name[i] for i in projects],
    "Lĩnh vực": [field[i] for i in projects],
    "Chi phí tổng": [C[i] for i in projects],
    "Lợi ích NPV": [B[i] for i in projects],
    "Chi phí năm 1-2": [C1[i] for i in projects],
    "Chi phí năm 3-5": [C[i] - C1[i] for i in projects],
    "NPV/Chi phí": [B[i] / C[i] for i in projects]
})

display(project_df.round(3))

# Biểu đồ dữ liệu đầu vào
plt.figure(figsize=(14,6))
plt.bar(project_df["Mã"], project_df["Chi phí tổng"], label="Chi phí")
plt.bar(project_df["Mã"], project_df["Lợi ích NPV"], alpha=0.6, label="Lợi ích NPV")
plt.title("So sánh chi phí và lợi ích NPV của 15 dự án")
plt.xlabel("Dự án")
plt.ylabel("Tỷ VND")
plt.legend()
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(12,5))
plt.bar(project_df["Mã"], project_df["NPV/Chi phí"])
plt.title("Tỷ suất lợi ích/chi phí của các dự án")
plt.xlabel("Dự án")
plt.ylabel("NPV/Chi phí")
plt.grid(axis="y")
plt.show()

# ============================================================
# 3. HÀM GIẢI MÔ HÌNH MIP
# ============================================================

def solve_project_selection(
    total_budget=80000,
    early_budget=40000,
    force_p1_p2=False,
    force_p14=True,
    use_expected_value=False
):
    """
    Giải bài toán lựa chọn dự án bằng PuLP.

    total_budget: ngân sách tổng 5 năm
    early_budget: ngân sách năm 1-2
    force_p1_p2: nếu True thì bắt buộc chọn cả P1 và P2
    force_p14: nếu True thì bắt buộc chọn P14
    use_expected_value: nếu True thì tối đa hóa lợi ích kỳ vọng p_i*B_i
    """

    model = pulp.LpProblem("VN_Project_Selection", pulp.LpMaximize)

    y = pulp.LpVariable.dicts("y", projects, cat="Binary")

    if use_expected_value:
        benefit = expected_B
    else:
        benefit = B

    # Objective
    model += pulp.lpSum(benefit[i] * y[i] for i in projects), "Total_Benefit"

    # C1 ngân sách tổng
    model += pulp.lpSum(C[i] * y[i] for i in projects) <= total_budget, "Total_budget"

    # C2 ngân sách năm 1-2
    model += pulp.lpSum(C1[i] * y[i] for i in projects) <= early_budget, "Early_budget"

    # C3 loại trừ trung tâm dữ liệu
    if force_p1_p2:
        model += y[1] == 1, "Force_P1"
        model += y[2] == 1, "Force_P2"
    else:
        model += y[1] + y[2] <= 1, "Data_center_exclusion"

    # C4, C5 tiên quyết
    model += y[8] <= y[12], "AI_requires_training"
    model += y[13] <= y[12], "Semiconductor_requires_training"

    # C6 cân đối lĩnh vực
    model += y[4] + y[5] >= 1, "At_least_one_digital_gov"

    if force_p14:
        model += y[14] >= 1, "Cybersecurity_required"

    # C7 số lượng dự án
    model += pulp.lpSum(y[i] for i in projects) >= 7, "Min_projects"
    model += pulp.lpSum(y[i] for i in projects) <= 11, "Max_projects"

    model.solve(pulp.PULP_CBC_CMD(msg=False))

    status = pulp.LpStatus[model.status]

    if status != "Optimal":
        return None, None, status, model

    selected = [i for i in projects if y[i].value() > 0.5]

    selected_df = project_df[project_df["Mã"].isin([f"P{i}" for i in selected])].copy()

    total_cost = sum(C[i] for i in selected)
    total_early_cost = sum(C1[i] for i in selected)
    total_benefit = sum(B[i] for i in selected)
    total_objective = pulp.value(model.objective)

    summary = {
        "selected": selected,
        "selected_df": selected_df,
        "total_cost": total_cost,
        "total_early_cost": total_early_cost,
        "total_benefit": total_benefit,
        "objective": total_objective,
        "benefit_cost_ratio": total_objective / total_cost if total_cost > 0 else np.nan,
        "num_projects": len(selected)
    }

    return summary, model, status, model

# ============================================================
# 4. CÂU 5.4.1 — GIẢI MÔ HÌNH CƠ SỞ
# ============================================================

print("""
============================================================
4. CÂU 5.4.1 — GIẢI MÔ HÌNH CƠ SỞ BẰNG PuLP CBC
============================================================
""")

base_summary, base_model, base_status, _ = solve_project_selection(
    total_budget=80000,
    early_budget=40000,
    force_p1_p2=False,
    force_p14=True,
    use_expected_value=False
)

print("Trạng thái nghiệm:", base_status)

if base_status != "Optimal":
    raise ValueError("Mô hình cơ sở không tìm được nghiệm tối ưu.")

print("Các dự án được chọn:", [f"P{i}" for i in base_summary["selected"]])
print(f"Tổng chi phí = {base_summary['total_cost']:,.0f} tỷ VND")
print(f"Chi phí năm 1-2 = {base_summary['total_early_cost']:,.0f} tỷ VND")
print(f"Tổng lợi ích NPV = {base_summary['total_benefit']:,.0f} tỷ VND")
print(f"Z* = {base_summary['objective']:,.0f} tỷ VND")
print(f"NPV biên Z*/Chi phí = {base_summary['benefit_cost_ratio']:.4f}")
print(f"Số dự án được chọn = {base_summary['num_projects']}")

display(base_summary["selected_df"].round(3))

# Bảng chọn/không chọn
selection_df = project_df.copy()
selection_df["Được chọn"] = selection_df["Mã"].apply(
    lambda code: "Có" if int(code.replace("P","")) in base_summary["selected"] else "Không"
)

display(selection_df)

# Biểu đồ dự án được chọn
plt.figure(figsize=(14,6))
colors = ["tab:blue" if int(code.replace("P","")) in base_summary["selected"] else "lightgray"
          for code in project_df["Mã"]]
plt.bar(project_df["Mã"], project_df["Lợi ích NPV"], color=colors)
plt.title("Dự án được chọn trong mô hình cơ sở")
plt.xlabel("Dự án")
plt.ylabel("Lợi ích NPV")
plt.grid(axis="y")
plt.show()

# Cơ cấu lĩnh vực dự án được chọn
selected_field_counts = base_summary["selected_df"]["Lĩnh vực"].value_counts()

plt.figure(figsize=(8,8))
plt.pie(
    selected_field_counts.values,
    labels=selected_field_counts.index,
    autopct="%1.1f%%",
    startangle=90
)
plt.title("Cơ cấu lĩnh vực trong tập dự án được chọn")
plt.show()

# ============================================================
# 5. KIỂM TRA RÀNG BUỘC MÔ HÌNH CƠ SỞ
# ============================================================

print("""
============================================================
5. KIỂM TRA RÀNG BUỘC MÔ HÌNH CƠ SỞ
============================================================
""")

constraint_check = pd.DataFrame({
    "Ràng buộc": [
        "Ngân sách tổng 5 năm",
        "Ngân sách năm 1-2",
        "Chỉ chọn một trung tâm dữ liệu P1/P2",
        "P8 chỉ được chọn nếu P12 được chọn",
        "P13 chỉ được chọn nếu P12 được chọn",
        "Ít nhất một chính phủ số P4/P5",
        "An ninh mạng P14 bắt buộc",
        "Số lượng dự án"
    ],
    "Giá trị thực tế": [
        base_summary["total_cost"],
        base_summary["total_early_cost"],
        int(1 in base_summary["selected"]) + int(2 in base_summary["selected"]),
        f"P8={int(8 in base_summary['selected'])}, P12={int(12 in base_summary['selected'])}",
        f"P13={int(13 in base_summary['selected'])}, P12={int(12 in base_summary['selected'])}",
        int(4 in base_summary["selected"]) + int(5 in base_summary["selected"]),
        int(14 in base_summary["selected"]),
        base_summary["num_projects"]
    ],
    "Yêu cầu": [
        "<= 80.000",
        "<= 40.000",
        "<= 1",
        "P8 <= P12",
        "P13 <= P12",
        ">= 1",
        ">= 1",
        "7 đến 11"
    ]
})

display(constraint_check)

# ============================================================
# 6. CÂU 5.4.2 — NỚI NGÂN SÁCH LÊN 100.000
# ============================================================

print("""
============================================================
6. CÂU 5.4.2 — PHÂN TÍCH TRƯỜNG HỢP NỚI NGÂN SÁCH LÊN 100.000
============================================================
""")

budget100_summary, budget100_model, budget100_status, _ = solve_project_selection(
    total_budget=100000,
    early_budget=40000,
    force_p1_p2=False,
    force_p14=True,
    use_expected_value=False
)

print("Trạng thái nghiệm:", budget100_status)

if budget100_status != "Optimal":
    print("Mô hình ngân sách 100.000 không có nghiệm tối ưu.")
else:
    print("Các dự án được chọn:", [f"P{i}" for i in budget100_summary["selected"]])
    print(f"Tổng chi phí = {budget100_summary['total_cost']:,.0f}")
    print(f"Chi phí năm 1-2 = {budget100_summary['total_early_cost']:,.0f}")
    print(f"Z* = {budget100_summary['objective']:,.0f}")
    print(f"NPV biên = {budget100_summary['benefit_cost_ratio']:.4f}")

    display(budget100_summary["selected_df"].round(3))

    base_set = set(base_summary["selected"])
    budget100_set = set(budget100_summary["selected"])

    added_projects = sorted(list(budget100_set - base_set))
    removed_projects = sorted(list(base_set - budget100_set))

    print("Dự án được thêm khi tăng ngân sách:", [f"P{i}" for i in added_projects])
    print("Dự án bị loại khi tăng ngân sách:", [f"P{i}" for i in removed_projects])

    compare_budget_df = pd.DataFrame({
        "Chỉ tiêu": [
            "Z* ngân sách 80.000",
            "Z* ngân sách 100.000",
            "Chênh lệch Z*",
            "Tổng chi phí 80.000",
            "Tổng chi phí 100.000",
            "Số dự án 80.000",
            "Số dự án 100.000"
        ],
        "Giá trị": [
            base_summary["objective"],
            budget100_summary["objective"],
            budget100_summary["objective"] - base_summary["objective"],
            base_summary["total_cost"],
            budget100_summary["total_cost"],
            base_summary["num_projects"],
            budget100_summary["num_projects"]
        ]
    })

    display(compare_budget_df.round(3))

# Biểu đồ so sánh selection 80k vs 100k
compare_selection = pd.DataFrame({
    "Dự án": [f"P{i}" for i in projects],
    "80.000": [1 if i in base_summary["selected"] else 0 for i in projects],
    "100.000": [1 if budget100_status == "Optimal" and i in budget100_summary["selected"] else 0 for i in projects]
})

compare_selection.set_index("Dự án")[["80.000", "100.000"]].plot(kind="bar", figsize=(13,5))
plt.title("So sánh dự án được chọn khi ngân sách 80.000 và 100.000")
plt.ylabel("Được chọn = 1")
plt.grid(axis="y")
plt.show()

# ============================================================
# 7. CÂU 5.4.3 — BẮT BUỘC CÓ CẢ P1 VÀ P2
# ============================================================

print("""
============================================================
7. CÂU 5.4.3 — KỊCH BẢN BẮT BUỘC CÓ CẢ P1 VÀ P2
============================================================

Giả sử Quốc hội yêu cầu phải có cả P1 và P2 vì cần redundancy.
Khi đó ràng buộc loại trừ y1 + y2 <= 1 được thay bằng y1 = 1 và y2 = 1.
""")

force12_summary, force12_model, force12_status, _ = solve_project_selection(
    total_budget=80000,
    early_budget=40000,
    force_p1_p2=True,
    force_p14=True,
    use_expected_value=False
)

print("Trạng thái nghiệm:", force12_status)

if force12_status != "Optimal":
    print("""
Kết luận:
Bài toán không khả thi hoặc không tìm được nghiệm tối ưu khi bắt buộc chọn cả P1 và P2.
Nguyên nhân có thể do hai dự án trung tâm dữ liệu tiêu tốn nhiều ngân sách tổng
và ngân sách năm 1-2, làm giảm khả năng thỏa mãn các ràng buộc khác.
""")
else:
    print("Các dự án được chọn:", [f"P{i}" for i in force12_summary["selected"]])
    print(f"Tổng chi phí = {force12_summary['total_cost']:,.0f}")
    print(f"Chi phí năm 1-2 = {force12_summary['total_early_cost']:,.0f}")
    print(f"Z* = {force12_summary['objective']:,.0f}")
    print(f"Chênh lệch Z* so với cơ sở = {force12_summary['objective'] - base_summary['objective']:,.0f}")

    display(force12_summary["selected_df"].round(3))

    force_compare_df = pd.DataFrame({
        "Chỉ tiêu": [
            "Z* cơ sở",
            "Z* bắt buộc P1+P2",
            "Chênh lệch Z*",
            "Tổng chi phí cơ sở",
            "Tổng chi phí P1+P2",
            "Chi phí năm 1-2 cơ sở",
            "Chi phí năm 1-2 P1+P2"
        ],
        "Giá trị": [
            base_summary["objective"],
            force12_summary["objective"],
            force12_summary["objective"] - base_summary["objective"],
            base_summary["total_cost"],
            force12_summary["total_cost"],
            base_summary["total_early_cost"],
            force12_summary["total_early_cost"]
        ]
    })

    display(force_compare_df.round(3))

# ============================================================
# 8. CÂU 5.4.4 — MỞ RỘNG RỦI RO DỰ ÁN
# ============================================================

print("""
============================================================
8. CÂU 5.4.4 — MỞ RỘNG: THÊM RỦI RO DỰ ÁN
============================================================

Thay vì tối đa hóa lợi ích NPV danh nghĩa B_i, ta tối đa hóa lợi ích kỳ vọng:

E[Z] = Σ_i p_i * B_i * y_i

Giả định xác suất hoàn thành đúng tiến độ:
- Hạ tầng: 0.85
- Chính phủ số: 0.75
- AI và bán dẫn: 0.65
- Còn lại: 0.80
""")

def project_probability(i):
    if field[i] == "Hạ tầng":
        return 0.85
    elif field[i] == "Chính phủ số":
        return 0.75
    elif field[i] in ["AI", "Bán dẫn"]:
        return 0.65
    else:
        return 0.80

p = {i: project_probability(i) for i in projects}
expected_B = {i: p[i] * B[i] for i in projects}

risk_df = project_df.copy()
risk_df["Xác suất p_i"] = [p[i] for i in projects]
risk_df["Lợi ích kỳ vọng p_i*B_i"] = [expected_B[i] for i in projects]
risk_df["Expected NPV/Chi phí"] = risk_df["Lợi ích kỳ vọng p_i*B_i"] / risk_df["Chi phí tổng"]

display(risk_df.round(3))

risk_summary, risk_model, risk_status, _ = solve_project_selection(
    total_budget=80000,
    early_budget=40000,
    force_p1_p2=False,
    force_p14=True,
    use_expected_value=True
)

print("Trạng thái nghiệm:", risk_status)

if risk_status != "Optimal":
    print("Mô hình mở rộng rủi ro không có nghiệm tối ưu.")
else:
    print("Các dự án được chọn khi xét rủi ro:", [f"P{i}" for i in risk_summary["selected"]])
    print(f"Tổng chi phí = {risk_summary['total_cost']:,.0f}")
    print(f"Tổng NPV danh nghĩa = {risk_summary['total_benefit']:,.0f}")
    print(f"Lợi ích kỳ vọng E[Z] = {risk_summary['objective']:,.0f}")
    print(f"E[Z]/Chi phí = {risk_summary['benefit_cost_ratio']:.4f}")

    display(risk_summary["selected_df"].round(3))

    base_set = set(base_summary["selected"])
    risk_set = set(risk_summary["selected"])

    added_risk = sorted(list(risk_set - base_set))
    removed_risk = sorted(list(base_set - risk_set))

    print("Dự án được thêm khi xét rủi ro:", [f"P{i}" for i in added_risk])
    print("Dự án bị loại khi xét rủi ro:", [f"P{i}" for i in removed_risk])

    risk_compare_df = pd.DataFrame({
        "Chỉ tiêu": [
            "Z* danh nghĩa cơ sở",
            "E[Z] khi xét rủi ro",
            "Tổng chi phí cơ sở",
            "Tổng chi phí xét rủi ro",
            "Số dự án cơ sở",
            "Số dự án xét rủi ro"
        ],
        "Giá trị": [
            base_summary["objective"],
            risk_summary["objective"],
            base_summary["total_cost"],
            risk_summary["total_cost"],
            base_summary["num_projects"],
            risk_summary["num_projects"]
        ]
    })

    display(risk_compare_df.round(3))

# Biểu đồ so sánh lợi ích danh nghĩa và kỳ vọng
plt.figure(figsize=(14,6))
plt.bar(risk_df["Mã"], risk_df["Lợi ích NPV"], label="NPV danh nghĩa")
plt.bar(risk_df["Mã"], risk_df["Lợi ích kỳ vọng p_i*B_i"], alpha=0.7, label="NPV kỳ vọng")
plt.title("So sánh NPV danh nghĩa và NPV kỳ vọng sau khi xét rủi ro")
plt.xlabel("Dự án")
plt.ylabel("Tỷ VND")
plt.legend()
plt.grid(axis="y")
plt.show()

# ============================================================
# 9. MỞ RỘNG — PHÂN TÍCH RÀNG BUỘC P14
# ============================================================

print("""
============================================================
9. MỞ RỘNG — P14 AN NINH MẠNG BẮT BUỘC CÓ LÀM GIẢM Z* KHÔNG?
============================================================
""")

no_p14_summary, no_p14_model, no_p14_status, _ = solve_project_selection(
    total_budget=80000,
    early_budget=40000,
    force_p1_p2=False,
    force_p14=False,
    use_expected_value=False
)

if no_p14_status != "Optimal":
    print("Mô hình không bắt buộc P14 không có nghiệm tối ưu.")
else:
    p14_cost_df = pd.DataFrame({
        "Chỉ tiêu": [
            "Z* có bắt buộc P14",
            "Z* không bắt buộc P14",
            "Chênh lệch Z*",
            "P14 được chọn khi không bắt buộc?"
        ],
        "Giá trị": [
            base_summary["objective"],
            no_p14_summary["objective"],
            no_p14_summary["objective"] - base_summary["objective"],
            "Có" if 14 in no_p14_summary["selected"] else "Không"
        ]
    })

    display(p14_cost_df)

    print(f"""
Nếu không bắt buộc P14, mô hình {'vẫn chọn' if 14 in no_p14_summary['selected'] else 'không chọn'} P14.
Điều này cho biết ràng buộc an ninh mạng có làm giảm Z* hay không.
Nếu P14 vẫn được chọn, ràng buộc bắt buộc không gây chi phí kinh tế trong mô hình.
Nếu P14 không được chọn, việc bắt buộc P14 phản ánh đánh đổi giữa hiệu quả NPV và an ninh quốc gia.
""")

# ============================================================
# 10. MỞ RỘNG — HIỆU ỨNG CỘNG HƯỞNG P8 VÀ P13
# ============================================================

print("""
============================================================
10. MỞ RỘNG — MÔ HÌNH HÓA HIỆU ỨNG CỘNG HƯỞNG P8 VÀ P13
============================================================

Trong thực tế, Trung tâm AI quốc gia P8 và Khu công nghiệp bán dẫn P13 có thể
tạo hiệu ứng cộng hưởng. Có thể mô hình hóa bằng biến nhị phân z_8_13:

z_8_13 = 1 nếu cả P8 và P13 cùng được chọn.

Ràng buộc tuyến tính hóa:
z <= y8
z <= y13
z >= y8 + y13 - 1

Hàm mục tiêu mở rộng:
Max Σ B_i*y_i + S*z

Trong đó S là lợi ích cộng hưởng bổ sung.
""")

def solve_with_synergy(S=5000):
    model = pulp.LpProblem("VN_Project_Selection_Synergy", pulp.LpMaximize)

    y = pulp.LpVariable.dicts("y", projects, cat="Binary")
    z = pulp.LpVariable("z_P8_P13_synergy", cat="Binary")

    model += pulp.lpSum(B[i] * y[i] for i in projects) + S * z

    model += pulp.lpSum(C[i] * y[i] for i in projects) <= 80000
    model += pulp.lpSum(C1[i] * y[i] for i in projects) <= 40000

    model += y[1] + y[2] <= 1
    model += y[8] <= y[12]
    model += y[13] <= y[12]
    model += y[4] + y[5] >= 1
    model += y[14] >= 1
    model += pulp.lpSum(y[i] for i in projects) >= 7
    model += pulp.lpSum(y[i] for i in projects) <= 11

    # Linear hóa synergy P8-P13
    model += z <= y[8]
    model += z <= y[13]
    model += z >= y[8] + y[13] - 1

    model.solve(pulp.PULP_CBC_CMD(msg=False))

    status = pulp.LpStatus[model.status]

    if status != "Optimal":
        return None, None, None, status

    selected = [i for i in projects if y[i].value() > 0.5]

    return selected, pulp.value(model.objective), z.value(), status

synergy_values = [0, 3000, 5000, 8000, 10000, 15000]
synergy_rows = []

for S in synergy_values:
    selected_S, z_S, synergy_binary, status_S = solve_with_synergy(S=S)

    synergy_rows.append({
        "Synergy S": S,
        "Status": status_S,
        "Z*": z_S,
        "P8 chọn": 1 if selected_S and 8 in selected_S else 0,
        "P13 chọn": 1 if selected_S and 13 in selected_S else 0,
        "Synergy active": synergy_binary,
        "Dự án chọn": [f"P{i}" for i in selected_S] if selected_S else None
    })

synergy_df = pd.DataFrame(synergy_rows)
display(synergy_df)

plt.figure(figsize=(10,5))
plt.plot(synergy_df["Synergy S"], synergy_df["Z*"], marker="o", linewidth=3)
plt.title("Ảnh hưởng của lợi ích cộng hưởng P8-P13 đến Z*")
plt.xlabel("Lợi ích cộng hưởng S")
plt.ylabel("Z*")
plt.grid(True)
plt.show()

# ============================================================
# 11. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
11. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

p15_ratio = B[15] / C[15]
p15_selected = 15 in base_summary["selected"]

print(f"""
1. Vì sao mô hình có thể bỏ qua P15 dù tỷ suất lợi ích/chi phí cao?

P15 có tỷ suất lợi ích/chi phí là {p15_ratio:.2f}, khá cao.
Trong nghiệm cơ sở, P15 {'được chọn' if p15_selected else 'không được chọn'}.

Nếu P15 không được chọn, nguyên nhân có thể là do mô hình không chỉ tối đa hóa
tỷ suất lợi ích/chi phí mà tối đa hóa tổng NPV dưới nhiều ràng buộc:
ngân sách tổng, ngân sách năm 1-2, số lượng dự án, ràng buộc tiên quyết
và các yêu cầu bắt buộc.

Một dự án nhỏ, dù tỷ suất cao, vẫn có thể bị loại nếu phần ngân sách và số lượng
dự án được ưu tiên cho các dự án lớn có tổng NPV cao hơn.

Về chính sách, nếu Open Data được coi là hạ tầng dữ liệu nền tảng cho toàn bộ
hệ sinh thái số, có thể cần thêm ràng buộc bắt buộc chọn P15 hoặc thêm hiệu ứng
lan tỏa/cộng hưởng cho P15 trong hàm mục tiêu.

2. Ràng buộc bắt buộc P14 có hợp lý không?

P14 là dự án an ninh mạng quốc gia. Dù việc bắt buộc chọn P14 có thể làm giảm
tổng NPV trong một số trường hợp, ràng buộc này hợp lý vì an ninh mạng là điều kiện
nền tảng để bảo vệ hệ thống số quốc gia.

Trong chính sách công, không phải dự án nào cũng được chọn chỉ vì NPV cao.
Một số dự án có vai trò bảo hiểm rủi ro, bảo vệ chủ quyền số và giảm thiểu thiệt hại
hệ thống.

3. Mô hình hóa cộng hưởng P8 và P13 như thế nào?

Có thể thêm biến nhị phân z_8_13 để biểu diễn việc P8 và P13 cùng được chọn.
Nếu cả hai dự án được chọn, mô hình cộng thêm lợi ích synergy S vào hàm mục tiêu.

Cách này giúp phản ánh thực tế rằng Trung tâm AI quốc gia và khu công nghiệp bán dẫn
không độc lập hoàn toàn, mà có thể tạo hiệu ứng bổ trợ về dữ liệu, năng lực tính toán,
chuỗi cung ứng và nhân lực công nghệ cao.

4. Hàm ý chung

MIP là công cụ phù hợp cho lựa chọn danh mục dự án công vì có thể xử lý:
- dự án chọn/không chọn,
- ngân sách đa giai đoạn,
- dự án bắt buộc,
- dự án loại trừ nhau,
- dự án có quan hệ tiên quyết,
- và hiệu ứng cộng hưởng.
""")

# ============================================================
# 12. KẾT LUẬN
# ============================================================

print("""
============================================================
12. KẾT LUẬN
============================================================

Bài 5 đã xây dựng mô hình quy hoạch nguyên hỗn hợp MIP để lựa chọn danh mục
dự án chuyển đổi số quốc gia giai đoạn 2026–2030.

Mô hình sử dụng biến nhị phân để biểu diễn quyết định chọn hoặc không chọn
15 dự án. Hàm mục tiêu tối đa hóa tổng lợi ích NPV, trong khi các ràng buộc
bảo đảm ngân sách tổng, ngân sách năm 1–2, loại trừ dự án, tiên quyết dự án,
cân đối lĩnh vực và số lượng dự án.

Kịch bản ngân sách 100.000 tỷ VND cho phép đánh giá tác động của nới lỏng
nguồn lực. Kịch bản bắt buộc P1 và P2 giúp kiểm tra tính khả thi khi có yêu cầu
redundancy về trung tâm dữ liệu. Mở rộng rủi ro cho thấy khi xét xác suất hoàn thành,
danh mục tối ưu có thể thay đổi theo hướng thận trọng hơn.

Về mặt chính sách, mô hình cho thấy lựa chọn dự án công không chỉ là bài toán
tối đa hóa lợi ích tài chính, mà còn phải tính đến an ninh mạng, dữ liệu mở,
năng lực nhân lực, quan hệ tiên quyết và hiệu ứng cộng hưởng giữa các dự án chiến lược.
""")

