# -*- coding: utf-8 -*-
"""Bài 11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15npAleFrY8uVN2I0eYf6v0LsDRi42joJ
"""

# ============================================================
# BÀI 11 — HỌC TĂNG CƯỜNG Q-LEARNING CHO CHÍNH SÁCH KINH TẾ THÍCH NGHI
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    import gymnasium as gym
    from gymnasium import spaces
except ModuleNotFoundError:
    !pip install gymnasium
    import gymnasium as gym
    from gymnasium import spaces

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Bài 11 mô hình hóa nền kinh tế Việt Nam như một môi trường Markov Decision Process.

Trong mô hình này:
- Trạng thái là tình hình kinh tế hiện tại.
- Hành động là lựa chọn chính sách phân bổ ngân sách.
- Phần thưởng phản ánh phúc lợi xã hội.
- Q-learning học dần chính sách thích nghi qua nhiều episode.

Mục tiêu của bài không phải là để AI tự động quyết định chính sách,
mà là minh họa cách học tăng cường có thể hỗ trợ phân tích kịch bản
và đề xuất phương án tham khảo cho nhà hoạch định chính sách.
""")

# ============================================================
# 1. MÔ HÌNH MDP
# ============================================================

print("""
============================================================
1. MÔ HÌNH MDP
============================================================

Trạng thái gồm 4 thành phần, mỗi thành phần có 3 mức:

1. GDP growth: low, medium, high
2. Digital index: low, medium, high
3. AI capacity: low, medium, high
4. Unemployment risk: low, medium, high

Tổng số trạng thái: 3^4 = 81.

Hành động gồm 5 chính sách phân bổ ngân sách:

a0: Truyền thống    = 70% K, 10% D, 10% AI, 10% H
a1: Cân bằng        = 40% K, 25% D, 15% AI, 20% H
a2: Số hóa nhanh    = 25% K, 45% D, 15% AI, 15% H
a3: AI dẫn dắt      = 20% K, 20% D, 45% AI, 15% H
a4: Bao trùm        = 30% K, 20% D, 10% AI, 40% H

Phần thưởng:

R_t = 0.40*DeltaGDP - 0.25*DeltaUnemployment - 0.20*CyberRisk - 0.15*Emission
""")

# ============================================================
# 2. ĐỊNH NGHĨA MÔI TRƯỜNG GYMNASIUM
# ============================================================

action_names = {
    0: "a0 - Truyền thống",
    1: "a1 - Cân bằng",
    2: "a2 - Số hóa nhanh",
    3: "a3 - AI dẫn dắt",
    4: "a4 - Bao trùm"
}

state_level_names = {
    0: "low",
    1: "medium",
    2: "high"
}

class VietnamEconomyEnv(gym.Env):
    def __init__(self):
        super().__init__()

        self.action_space = spaces.Discrete(5)
        self.observation_space = spaces.MultiDiscrete([3, 3, 3, 3])

        self.T = 10
        self.budget = 1000

        self.allocation = {
            0: np.array([0.70, 0.10, 0.10, 0.10]),
            1: np.array([0.40, 0.25, 0.15, 0.20]),
            2: np.array([0.25, 0.45, 0.15, 0.15]),
            3: np.array([0.20, 0.20, 0.45, 0.15]),
            4: np.array([0.30, 0.20, 0.10, 0.40])
        }

        self.w = np.array([0.40, 0.25, 0.20, 0.15])

        self.alpha_K = 0.33
        self.alpha_L = 0.42
        self.alpha_D = 0.10
        self.alpha_AI = 0.08
        self.alpha_H = 0.07

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        self.t = 0

        # Trạng thái VN 2026 giả định:
        # GDP medium, Digital medium, AI low, Unemployment medium
        self.state = np.array([1, 1, 0, 1])

        self.K = 27500.0
        self.D = 20.3
        self.AI = 86.0
        self.H = 30.0
        self.L = 54.0
        self.A = 35.0

        self.prev_Y = self.production()

        return self.state.copy(), {}

    def production(self):
        Y = (
            self.A
            * (self.K ** self.alpha_K)
            * (self.L ** self.alpha_L)
            * (self.D ** self.alpha_D)
            * (self.AI ** self.alpha_AI)
            * (self.H ** self.alpha_H)
        )
        return Y

    def discretize_state(self, gdp_growth, digital_index, ai_capacity, unemployment_risk):
        if gdp_growth < 0.03:
            gdp_state = 0
        elif gdp_growth < 0.06:
            gdp_state = 1
        else:
            gdp_state = 2

        if digital_index < 35:
            d_state = 0
        elif digital_index < 70:
            d_state = 1
        else:
            d_state = 2

        if ai_capacity < 100:
            ai_state = 0
        elif ai_capacity < 180:
            ai_state = 1
        else:
            ai_state = 2

        if unemployment_risk < 0.04:
            u_state = 0
        elif unemployment_risk < 0.08:
            u_state = 1
        else:
            u_state = 2

        return np.array([gdp_state, d_state, ai_state, u_state])

    def step(self, action):
        allocation = self.allocation[action]

        invest_K = allocation[0] * self.budget
        invest_D = allocation[1] * self.budget
        invest_AI = allocation[2] * self.budget
        invest_H = allocation[3] * self.budget

        # Cập nhật trạng thái kinh tế
        self.K = 0.95 * self.K + invest_K
        self.D = 0.88 * self.D + invest_D / 100
        self.AI = 0.85 * self.AI + invest_AI / 20
        self.H = 0.98 * self.H + invest_H / 200

        # TFP tăng nhờ D, AI, H
        self.A = self.A * (1 + 0.0008*self.D + 0.0005*self.AI + 0.001*self.H)

        Y = self.production()
        gdp_growth = (Y - self.prev_Y) / self.prev_Y

        # Rủi ro thất nghiệp tăng khi AI cao hơn H, giảm khi H cao
        unemployment_risk = max(
            0.01,
            0.08
            + 0.0008 * invest_AI
            - 0.0012 * invest_H
            - 0.002 * self.H
        )

        # Cyber risk tăng theo AI, giảm theo H
        cyber_risk = max(
            0,
            0.03
            + 0.0006 * invest_AI
            - 0.0004 * invest_H
        )

        # Emission tăng theo K và AI, giảm nhẹ khi D/H tốt hơn
        emission = max(
            0,
            0.04
            + 0.0004 * invest_K
            + 0.0005 * invest_AI
            - 0.0002 * invest_D
        )

        # Chuẩn hóa reward để tránh quá lớn
        delta_gdp_score = gdp_growth * 100
        unemployment_score = unemployment_risk * 100
        cyber_score = cyber_risk * 100
        emission_score = emission * 100

        reward = (
            self.w[0] * delta_gdp_score
            - self.w[1] * unemployment_score
            - self.w[2] * cyber_score
            - self.w[3] * emission_score
        )

        self.state = self.discretize_state(
            gdp_growth=gdp_growth,
            digital_index=self.D,
            ai_capacity=self.AI,
            unemployment_risk=unemployment_risk
        )

        self.prev_Y = Y
        self.t += 1

        terminated = self.t >= self.T
        truncated = False

        info = {
            "Y": Y,
            "gdp_growth": gdp_growth,
            "D": self.D,
            "AI": self.AI,
            "H": self.H,
            "unemployment_risk": unemployment_risk,
            "cyber_risk": cyber_risk,
            "emission": emission,
            "reward": reward
        }

        return self.state.copy(), reward, terminated, truncated, info


# ============================================================
# 3. CÂU 11.3.1 — KIỂM TRA MÔI TRƯỜNG
# ============================================================

print("""
============================================================
3. CÂU 11.3.1 — KIỂM TRA MÔI TRƯỜNG GYM
============================================================
""")

env = VietnamEconomyEnv()
s, _ = env.reset()

print("Trạng thái ban đầu:", s)
print("Ý nghĩa trạng thái:",
      f"GDP={state_level_names[s[0]]},",
      f"D={state_level_names[s[1]]},",
      f"AI={state_level_names[s[2]]},",
      f"U={state_level_names[s[3]]}")

s2, r, done, truncated, info = env.step(1)
print("Sau khi chọn hành động a1 - Cân bằng:")
print("Trạng thái mới:", s2)
print("Reward:", r)
print("Info:", info)

# ============================================================
# 4. CÂU 11.3.2 — Q-LEARNING
# ============================================================

print("""
============================================================
4. CÂU 11.3.2 — HUẤN LUYỆN Q-LEARNING
============================================================
""")

env = VietnamEconomyEnv()

Q = np.zeros((3, 3, 3, 3, 5))

alpha = 0.10
gamma_discount = 0.95
n_episodes = 10000

episode_rewards = []
epsilon_history = []

for ep in range(n_episodes):
    s, _ = env.reset()
    total_reward = 0

    epsilon = max(0.05, 1.0 - ep / 5000)
    epsilon_history.append(epsilon)

    while True:
        if np.random.rand() < epsilon:
            a = env.action_space.sample()
        else:
            a = int(np.argmax(Q[tuple(s)]))

        s2, r, done, truncated, info = env.step(a)

        old_value = Q[tuple(s) + (a,)]
        next_max = Q[tuple(s2)].max()

        Q[tuple(s) + (a,)] = old_value + alpha * (
            r + gamma_discount * next_max - old_value
        )

        s = s2
        total_reward += r

        if done or truncated:
            break

    episode_rewards.append(total_reward)

print("Training hoàn tất.")
print("Reward trung bình 100 episode cuối:", np.mean(episode_rewards[-100:]))

# Learning curve
reward_series = pd.Series(episode_rewards)
rolling_reward = reward_series.rolling(window=100).mean()

plt.figure(figsize=(12,6))
plt.plot(episode_rewards, alpha=0.25, label="Episode reward")
plt.plot(rolling_reward, linewidth=3, label="Rolling mean 100 episodes")
plt.title("Learning curve của Q-learning")
plt.xlabel("Episode")
plt.ylabel("Total reward")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,5))
plt.plot(epsilon_history)
plt.title("Epsilon decay")
plt.xlabel("Episode")
plt.ylabel("Epsilon")
plt.grid(True)
plt.show()

# ============================================================
# 5. CÂU 11.3.3 — TRÍCH XUẤT CHÍNH SÁCH PI*
# ============================================================

print("""
============================================================
5. CÂU 11.3.3 — TRÍCH XUẤT CHÍNH SÁCH PI*
============================================================
""")

policy = np.argmax(Q, axis=4)

test_states = {
    "VN 2026 thực tế": np.array([1, 1, 0, 1]),
    "GDP thấp, D thấp, AI thấp, U cao": np.array([0, 0, 0, 2]),
    "GDP cao, D cao, AI cao, U thấp": np.array([2, 2, 2, 0]),
    "GDP thấp, D cao, AI cao, U cao": np.array([0, 2, 2, 2]),
    "GDP trung bình, D thấp, AI thấp, U trung bình": np.array([1, 0, 0, 1])
}

policy_rows = []

for name, state in test_states.items():
    action = int(policy[tuple(state)])
    q_values = Q[tuple(state)]

    policy_rows.append({
        "Trạng thái": name,
        "GDP": state_level_names[state[0]],
        "Digital": state_level_names[state[1]],
        "AI": state_level_names[state[2]],
        "Unemployment": state_level_names[state[3]],
        "Hành động chọn": action_names[action],
        "Q tốt nhất": q_values[action]
    })

policy_df = pd.DataFrame(policy_rows)
display(policy_df)

# Đếm tần suất hành động trong toàn bộ 81 trạng thái
action_counts = pd.Series(policy.flatten()).value_counts().sort_index()

action_count_df = pd.DataFrame({
    "Hành động": [action_names[i] for i in action_counts.index],
    "Số trạng thái được chọn": action_counts.values
})

display(action_count_df)

plt.figure(figsize=(10,5))
plt.bar(action_count_df["Hành động"], action_count_df["Số trạng thái được chọn"])
plt.title("Tần suất hành động được chính sách pi* chọn trên 81 trạng thái")
plt.ylabel("Số trạng thái")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 6. CÂU 11.3.4 — SO SÁNH VỚI RULE-BASED POLICIES
# ============================================================

print("""
============================================================
6. CÂU 11.3.4 — SO SÁNH PI* VỚI 3 CHÍNH SÁCH RULE-BASED
============================================================
""")

def run_policy(policy_type="q", fixed_action=None, n_eval=500):
    rewards = []

    for _ in range(n_eval):
        s, _ = env.reset()
        total_reward = 0

        while True:
            if policy_type == "q":
                a = int(np.argmax(Q[tuple(s)]))
            elif policy_type == "fixed":
                a = fixed_action
            elif policy_type == "random":
                a = env.action_space.sample()
            else:
                raise ValueError("policy_type không hợp lệ")

            s, r, done, truncated, info = env.step(a)
            total_reward += r

            if done or truncated:
                break

        rewards.append(total_reward)

    return np.array(rewards)

q_rewards = run_policy(policy_type="q", n_eval=500)
a1_rewards = run_policy(policy_type="fixed", fixed_action=1, n_eval=500)
a3_rewards = run_policy(policy_type="fixed", fixed_action=3, n_eval=500)
random_rewards = run_policy(policy_type="random", n_eval=500)

comparison_df = pd.DataFrame({
    "Chính sách": [
        "Q-learning pi*",
        "Rule-based: luôn a1 Cân bằng",
        "Rule-based: luôn a3 AI dẫn dắt",
        "Random"
    ],
    "Reward trung bình": [
        q_rewards.mean(),
        a1_rewards.mean(),
        a3_rewards.mean(),
        random_rewards.mean()
    ],
    "Độ lệch chuẩn": [
        q_rewards.std(),
        a1_rewards.std(),
        a3_rewards.std(),
        random_rewards.std()
    ],
    "Reward thấp nhất": [
        q_rewards.min(),
        a1_rewards.min(),
        a3_rewards.min(),
        random_rewards.min()
    ],
    "Reward cao nhất": [
        q_rewards.max(),
        a1_rewards.max(),
        a3_rewards.max(),
        random_rewards.max()
    ]
})

display(comparison_df.round(4))

plt.figure(figsize=(10,5))
plt.bar(comparison_df["Chính sách"], comparison_df["Reward trung bình"])
plt.title("So sánh reward trung bình giữa các chính sách")
plt.ylabel("Reward trung bình")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(10,5))
plt.boxplot(
    [q_rewards, a1_rewards, a3_rewards, random_rewards],
    labels=["Q-learning", "Always a1", "Always a3", "Random"]
)
plt.title("Phân phối reward của các chính sách")
plt.ylabel("Total reward")
plt.grid(axis="y")
plt.show()

# ============================================================
# 7. MÔ PHỎNG MỘT EPISODE THEO PI*
# ============================================================

print("""
============================================================
7. MÔ PHỎNG MỘT EPISODE THEO CHÍNH SÁCH PI*
============================================================
""")

s, _ = env.reset()
trajectory = []

for t in range(env.T):
    a = int(np.argmax(Q[tuple(s)]))
    s2, r, done, truncated, info = env.step(a)

    trajectory.append({
        "Năm": 2026 + t,
        "State trước": tuple(s),
        "Hành động": action_names[a],
        "Reward": r,
        "GDP growth": info["gdp_growth"],
        "Digital D": info["D"],
        "AI capacity": info["AI"],
        "H": info["H"],
        "Unemployment risk": info["unemployment_risk"],
        "Cyber risk": info["cyber_risk"],
        "Emission": info["emission"],
        "State sau": tuple(s2)
    })

    s = s2

    if done:
        break

trajectory_df = pd.DataFrame(trajectory)
display(trajectory_df.round(4))

plt.figure(figsize=(12,6))
plt.plot(trajectory_df["Năm"], trajectory_df["Reward"], marker="o", linewidth=3)
plt.title("Reward theo năm trong một episode dùng pi*")
plt.xlabel("Năm")
plt.ylabel("Reward")
plt.grid(True)
plt.show()

plt.figure(figsize=(12,6))
plt.plot(trajectory_df["Năm"], trajectory_df["Digital D"], marker="o", label="Digital D")
plt.plot(trajectory_df["Năm"], trajectory_df["AI capacity"], marker="s", label="AI capacity")
plt.plot(trajectory_df["Năm"], trajectory_df["H"], marker="^", label="Human capital H")
plt.title("Diễn biến D, AI, H theo chính sách pi*")
plt.xlabel("Năm")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# 8. CÂU 11.3.5 — MỞ RỘNG DQN OPTIONAL
# ============================================================

print("""
============================================================
8. CÂU 11.3.5 — MỞ RỘNG DQN OPTIONAL
============================================================

Phần này là mở rộng. Nếu Colab không đủ thời gian hoặc không cài được stable-baselines3,
có thể chỉ trình bày ý tưởng trong báo cáo.
""")

print("""
Gợi ý cài DQN:

!pip install stable-baselines3

from stable_baselines3 import DQN

env = VietnamEconomyEnv()

model = DQN(
    "MlpPolicy",
    env,
    learning_rate=1e-3,
    buffer_size=50000,
    learning_starts=1000,
    batch_size=32,
    gamma=0.95,
    exploration_fraction=0.3,
    exploration_final_eps=0.05,
    policy_kwargs=dict(net_arch=[64, 64]),
    verbose=1
)

model.learn(total_timesteps=50000)

Sau đó so sánh reward trung bình của DQN với Q-learning tabular.
DQN có thể cải thiện khi trạng thái liên tục hoặc không gian trạng thái lớn hơn,
nhưng với bài toán tabular 81 trạng thái, Q-learning đã đủ minh họa.
""")

# ============================================================
# 9. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
9. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

state_bad = np.array([0, 0, 0, 2])
action_bad = int(policy[tuple(state_bad)])

state_good = np.array([2, 2, 2, 0])
action_good = int(policy[tuple(state_good)])

print(f"""
1. Khi GDP thấp, D thấp, AI thấp, thất nghiệp cao, pi*(s) chọn gì?

Ở trạng thái [GDP low, D low, AI low, U high], chính sách học được chọn:

{action_names[action_bad]}

Nếu agent chọn hành động bao trùm hoặc cân bằng, điều này phù hợp với logic
ổn định xã hội và phục hồi nền tảng. Nếu agent chọn số hóa nhanh, đó có thể
được hiểu là chiến lược quick win để nâng năng lực số và kích thích tăng trưởng.

2. Khi GDP cao, AI cao, thất nghiệp thấp, pi*(s) chọn gì?

Ở trạng thái [GDP high, D high, AI high, U low], chính sách học được chọn:

{action_names[action_good]}

Nếu agent chọn cân bằng hoặc bao trùm, điều này phù hợp với chiến lược consolidation:
khi nền kinh tế đã tăng trưởng tốt, chính sách nên củng cố nhân lực, giảm rủi ro
và tránh đầu tư quá nóng vào AI.

3. AI không thay thế quyết định chính trị - xã hội

Q-learning chỉ là công cụ mô phỏng. Nó có thể đề xuất hành động có reward cao
theo hàm mục tiêu đã định nghĩa, nhưng hàm mục tiêu đó tự nó đã chứa lựa chọn
giá trị chính trị: tăng trưởng quan trọng bao nhiêu, thất nghiệp quan trọng bao nhiêu,
an ninh dữ liệu và môi trường được đánh đổi thế nào.

Do đó, pi* nên được tích hợp vào quy trình hoạch định chính sách như sau:

- dùng như công cụ mô phỏng kịch bản;
- công khai giả định về reward và trọng số;
- cho chuyên gia kinh tế, lao động, công nghệ và xã hội phản biện;
- kiểm tra tác động phân phối lên vùng, ngành và nhóm dễ tổn thương;
- để Chính phủ và Quốc hội quyết định cuối cùng, không để thuật toán tự động quyết định.
""")

# ============================================================
# 10. KẾT LUẬN
# ============================================================

print("""
============================================================
10. KẾT LUẬN
============================================================

Bài 11 đã xây dựng mô hình học tăng cường tabular Q-learning cho bài toán
phân bổ ngân sách thích nghi trong nền kinh tế Việt Nam.

Môi trường được mô hình hóa như một MDP với 81 trạng thái và 5 hành động chính sách.
Q-learning học chính sách tối ưu qua 10.000 episode, sau đó được so sánh với
các chính sách rule-based như luôn chọn cân bằng, luôn chọn AI dẫn dắt và chọn ngẫu nhiên.

Kết quả minh họa rằng chính sách thích nghi theo trạng thái có thể đạt phần thưởng
cao hơn chính sách cố định trong một số trường hợp. Tuy nhiên, mô hình cũng nhấn mạnh
rằng AI chỉ hỗ trợ phân tích ra quyết định, không thay thế trách nhiệm chính trị,
xã hội và thể chế trong hoạch định chính sách công.
""")

