# -*- coding: utf-8 -*-
"""Bài 6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CHwZRkzH50m-GqzTbzHNH56JG-HfHwF2
"""

# ============================================================
# BÀI 6 — TOPSIS XẾP HẠNG 6 VÙNG KINH TẾ VIỆT NAM
# THEO MỨC ĐỘ ƯU TIÊN ĐẦU TƯ AI
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    import seaborn as sns
except ModuleNotFoundError:
    !pip install seaborn
    import seaborn as sns

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Theo Chiến lược quốc gia về nghiên cứu, phát triển và ứng dụng AI đến năm 2030,
Việt Nam đặt mục tiêu trở thành trung tâm AI của khu vực ASEAN.

Tuy nhiên, nguồn lực đầu tư cho AI là có hạn. Vì vậy, cần lựa chọn vùng nào
nên được ưu tiên triển khai trung tâm AI, sandbox dữ liệu và hạ tầng AI trước.

Bài 6 sử dụng phương pháp TOPSIS — một kỹ thuật ra quyết định đa tiêu chí —
để xếp hạng 6 vùng kinh tế - xã hội Việt Nam theo mức độ ưu tiên đầu tư AI.
""")

# ============================================================
# 1. LÝ THUYẾT TOPSIS
# ============================================================

print("""
============================================================
1. LÝ THUYẾT TOPSIS
============================================================

TOPSIS là phương pháp xếp hạng các phương án dựa trên khoảng cách tới:

- Phương án lý tưởng dương A*: tốt nhất trên tất cả tiêu chí.
- Phương án lý tưởng âm A-: kém nhất trên tất cả tiêu chí.

Quy trình:

Bước 1. Chuẩn hóa vector ma trận quyết định:

r_ij = x_ij / sqrt(sum_i x_ij^2)

Bước 2. Nhân trọng số:

v_ij = w_j * r_ij

Bước 3. Xác định A* và A-:
- Với tiêu chí lợi ích: A* là max, A- là min.
- Với tiêu chí chi phí: A* là min, A- là max.

Bước 4. Tính khoảng cách Euclide:

S_i* = sqrt(sum_j (v_ij - v_j*)^2)
S_i- = sqrt(sum_j (v_ij - v_j-)^2)

Bước 5. Tính hệ số gần gũi:

C_i* = S_i- / (S_i* + S_i-)

C_i* càng lớn thì vùng càng gần phương án lý tưởng và càng được ưu tiên.
""")

# ============================================================
# 2. DỮ LIỆU ĐẦU VÀO
# ============================================================

print("""
============================================================
2. DỮ LIỆU ĐẦU VÀO
============================================================

Dữ liệu gồm 6 vùng kinh tế - xã hội Việt Nam với 8 tiêu chí:

1. GRDP/người
2. FDI
3. Digital Index
4. AI Readiness
5. Lao động qua đào tạo
6. R&D/GRDP
7. Internet penetration
8. Gini

Trong đó, 7 tiêu chí đầu là tiêu chí lợi ích.
Gini là tiêu chí chi phí vì chỉ số bất bình đẳng càng thấp càng tốt.
""")

try:
    df = pd.read_csv("vietnam_regions_2024.csv")
except FileNotFoundError:
    print("Không tìm thấy vietnam_regions_2024.csv. Sử dụng dữ liệu mặc định theo đề bài.")

    df = pd.DataFrame({
        "region_name_vi": [
            "Trung du miền núi phía Bắc",
            "Đồng bằng sông Hồng",
            "Bắc Trung Bộ + DH Trung Bộ",
            "Tây Nguyên",
            "Đông Nam Bộ",
            "Đồng bằng sông Cửu Long"
        ],
        "grdp_per_capita_million_VND": [57.0, 152.3, 87.5, 68.9, 158.9, 80.5],
        "fdi_registered_billion_USD": [3.5, 20.0, 8.2, 0.8, 18.5, 2.1],
        "digital_index_0_100": [38, 78, 55, 32, 82, 48],
        "ai_readiness_0_100": [22, 68, 40, 18, 75, 30],
        "trained_labor_pct": [21.5, 36.8, 27.5, 18.2, 42.5, 16.8],
        "rd_intensity_pct": [0.18, 0.85, 0.32, 0.15, 0.78, 0.22],
        "internet_penetration_pct": [72, 92, 84, 68, 94, 78],
        "gini_coef": [0.405, 0.358, 0.372, 0.412, 0.385, 0.392]
    })

display(df)

criteria = [
    "grdp_per_capita_million_VND",
    "fdi_registered_billion_USD",
    "digital_index_0_100",
    "ai_readiness_0_100",
    "trained_labor_pct",
    "rd_intensity_pct",
    "internet_penetration_pct",
    "gini_coef"
]

criteria_vi = [
    "GRDP/người",
    "FDI",
    "Digital Index",
    "AI Readiness",
    "LĐ qua đào tạo",
    "R&D/GRDP",
    "Internet",
    "Gini"
]

is_benefit = np.array([True, True, True, True, True, True, True, False])

X = df[criteria].values.astype(float)

plt.figure(figsize=(11,6))
sns.heatmap(
    df.set_index("region_name_vi")[criteria],
    annot=True,
    fmt=".2f",
    cmap="YlGnBu"
)
plt.title("Heatmap dữ liệu đầu vào theo vùng")
plt.xlabel("Tiêu chí")
plt.ylabel("Vùng")
plt.show()

# ============================================================
# 3. HÀM TOPSIS
# ============================================================

def topsis(X, weights, is_benefit):
    """
    Tính TOPSIS từ đầu bằng numpy.
    """

    # Chuẩn hóa vector
    R = X / np.sqrt((X ** 2).sum(axis=0))

    # Ma trận chuẩn hóa có trọng số
    V = R * weights

    # Ideal và anti-ideal
    A_star = np.where(is_benefit, V.max(axis=0), V.min(axis=0))
    A_neg = np.where(is_benefit, V.min(axis=0), V.max(axis=0))

    # Khoảng cách
    S_star = np.sqrt(((V - A_star) ** 2).sum(axis=1))
    S_neg = np.sqrt(((V - A_neg) ** 2).sum(axis=1))

    # Hệ số gần gũi
    C_star = S_neg / (S_star + S_neg)

    return R, V, A_star, A_neg, S_star, S_neg, C_star

# ============================================================
# 4. CÂU 6.4.1 — TOPSIS VỚI TRỌNG SỐ CHUYÊN GIA
# ============================================================

print("""
============================================================
4. CÂU 6.4.1 — TOPSIS VỚI TRỌNG SỐ CHUYÊN GIA
============================================================
""")

w_expert = np.array([0.10, 0.10, 0.15, 0.20, 0.15, 0.15, 0.05, 0.10])

weight_expert_df = pd.DataFrame({
    "Tiêu chí": criteria_vi,
    "Trọng số chuyên gia": w_expert,
    "Loại tiêu chí": ["Lợi ích" if b else "Chi phí" for b in is_benefit]
})

display(weight_expert_df)

R, V, A_star, A_neg, S_star, S_neg, C_star = topsis(X, w_expert, is_benefit)

topsis_expert_df = df[["region_name_vi"]].copy()
topsis_expert_df["S_plus"] = S_star
topsis_expert_df["S_minus"] = S_neg
topsis_expert_df["TOPSIS_score"] = C_star
topsis_expert_df["Rank_expert"] = topsis_expert_df["TOPSIS_score"].rank(
    ascending=False,
    method="min"
).astype(int)

topsis_expert_rank = topsis_expert_df.sort_values("TOPSIS_score", ascending=False).reset_index(drop=True)

display(topsis_expert_rank.round(4))

plt.figure(figsize=(10,5))
plt.barh(topsis_expert_rank["region_name_vi"], topsis_expert_rank["TOPSIS_score"])
plt.gca().invert_yaxis()
plt.title("Xếp hạng TOPSIS theo trọng số chuyên gia")
plt.xlabel("TOPSIS score C_i*")
plt.ylabel("Vùng")
plt.grid(axis="x")
plt.show()

top3_expert = topsis_expert_rank.head(3)["region_name_vi"].tolist()

print(f"""
Top-3 vùng theo TOPSIS với trọng số chuyên gia:

1. {top3_expert[0]}
2. {top3_expert[1]}
3. {top3_expert[2]}
""")

# ============================================================
# 5. MA TRẬN CHUẨN HÓA VÀ MA TRẬN TRỌNG SỐ
# ============================================================

print("""
============================================================
5. MA TRẬN CHUẨN HÓA VÀ MA TRẬN CHUẨN HÓA CÓ TRỌNG SỐ
============================================================
""")

R_df = pd.DataFrame(R, columns=criteria_vi, index=df["region_name_vi"])
V_df = pd.DataFrame(V, columns=criteria_vi, index=df["region_name_vi"])

print("Ma trận chuẩn hóa vector R:")
display(R_df.round(4))

print("Ma trận chuẩn hóa có trọng số V:")
display(V_df.round(4))

plt.figure(figsize=(11,6))
sns.heatmap(R_df, annot=True, fmt=".2f", cmap="Blues")
plt.title("Heatmap ma trận chuẩn hóa vector R")
plt.xlabel("Tiêu chí")
plt.ylabel("Vùng")
plt.show()

plt.figure(figsize=(11,6))
sns.heatmap(V_df, annot=True, fmt=".3f", cmap="YlOrRd")
plt.title("Heatmap ma trận chuẩn hóa có trọng số V")
plt.xlabel("Tiêu chí")
plt.ylabel("Vùng")
plt.show()

# ============================================================
# 6. CÂU 6.4.2 — TRỌNG SỐ ENTROPY
# ============================================================

print("""
============================================================
6. CÂU 6.4.2 — TOPSIS VỚI TRỌNG SỐ ENTROPY
============================================================

Entropy weight là phương pháp xác định trọng số khách quan.
Tiêu chí nào có mức phân tán thông tin lớn hơn sẽ được gán trọng số cao hơn.
""")

def entropy_weights(X_raw):
    """
    Tính trọng số entropy.
    Với tiêu chí chi phí như Gini, đổi hướng trước bằng nghịch đảo min-max.
    """

    X_adj = X_raw.copy().astype(float)

    # Chuyển tiêu chí chi phí thành tiêu chí lợi ích bằng đảo hướng min-max
    for j, benefit in enumerate(is_benefit):
        if not benefit:
            col = X_adj[:, j]
            X_adj[:, j] = col.max() - col + 1e-12

    # Tránh chia 0
    P = X_adj / (X_adj.sum(axis=0) + 1e-12)

    k = 1.0 / np.log(X_adj.shape[0])
    E = -k * np.nansum(P * np.log(P + 1e-12), axis=0)
    d = 1 - E
    w = d / d.sum()

    return w, E, d

w_entropy, entropy_E, entropy_d = entropy_weights(X)

entropy_weight_df = pd.DataFrame({
    "Tiêu chí": criteria_vi,
    "Entropy E": entropy_E,
    "Độ phân tán d = 1-E": entropy_d,
    "Trọng số Entropy": w_entropy
})

display(entropy_weight_df.round(4))

R_e, V_e, A_star_e, A_neg_e, S_star_e, S_neg_e, C_star_e = topsis(X, w_entropy, is_benefit)

topsis_entropy_df = df[["region_name_vi"]].copy()
topsis_entropy_df["TOPSIS_entropy_score"] = C_star_e
topsis_entropy_df["Rank_entropy"] = topsis_entropy_df["TOPSIS_entropy_score"].rank(
    ascending=False,
    method="min"
).astype(int)

topsis_entropy_rank = topsis_entropy_df.sort_values("TOPSIS_entropy_score", ascending=False).reset_index(drop=True)

display(topsis_entropy_rank.round(4))

# So sánh expert và entropy
compare_topsis_df = topsis_expert_df.merge(topsis_entropy_df, on="region_name_vi")
compare_topsis_df["Rank_change"] = compare_topsis_df["Rank_entropy"] - compare_topsis_df["Rank_expert"]

display(compare_topsis_df.sort_values("Rank_expert").round(4))

plt.figure(figsize=(10,5))
x_pos = np.arange(len(criteria_vi))
plt.bar(x_pos - 0.2, w_expert, width=0.4, label="Chuyên gia")
plt.bar(x_pos + 0.2, w_entropy, width=0.4, label="Entropy")
plt.xticks(x_pos, criteria_vi, rotation=30, ha="right")
plt.title("So sánh trọng số chuyên gia và trọng số Entropy")
plt.ylabel("Trọng số")
plt.legend()
plt.grid(axis="y")
plt.show()

compare_plot = compare_topsis_df.set_index("region_name_vi")[["TOPSIS_score", "TOPSIS_entropy_score"]]
compare_plot.plot(kind="bar", figsize=(11,5))
plt.title("So sánh điểm TOPSIS: trọng số chuyên gia vs Entropy")
plt.ylabel("TOPSIS score")
plt.xlabel("Vùng")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

largest_rank_change_region = compare_topsis_df.iloc[
    compare_topsis_df["Rank_change"].abs().argmax()
]["region_name_vi"]

print(f"""
Vùng có thay đổi thứ hạng lớn nhất khi chuyển từ trọng số chuyên gia sang Entropy là:
{largest_rank_change_region}
""")

# ============================================================
# 7. CÂU 6.4.3 — PHÂN TÍCH ĐỘ NHẠY THEO TRỌNG SỐ AI READINESS
# ============================================================

print("""
============================================================
7. CÂU 6.4.3 — PHÂN TÍCH ĐỘ NHẠY THEO TRỌNG SỐ AI READINESS
============================================================

Thay đổi trọng số AI Readiness từ 0.10 đến 0.40.
Các trọng số còn lại được chuẩn hóa lại sao cho tổng trọng số bằng 1.
""")

ai_weights = np.arange(0.10, 0.401, 0.05)
ai_index = criteria_vi.index("AI Readiness")

sensitivity_rows = []
top3_by_ai_weight = {}

for ai_w in ai_weights:
    w_temp = w_expert.copy()

    other_idx = [i for i in range(len(w_temp)) if i != ai_index]
    other_sum = w_temp[other_idx].sum()

    w_temp[ai_index] = ai_w
    w_temp[other_idx] = w_temp[other_idx] / other_sum * (1 - ai_w)

    _, _, _, _, _, _, C_temp = topsis(X, w_temp, is_benefit)

    temp_df = pd.DataFrame({
        "Vùng": df["region_name_vi"],
        "AI_weight": round(ai_w, 2),
        "TOPSIS_score": C_temp
    }).sort_values("TOPSIS_score", ascending=False).reset_index(drop=True)

    temp_df["Rank"] = temp_df.index + 1

    top3_by_ai_weight[round(ai_w, 2)] = temp_df.head(3)["Vùng"].tolist()

    sensitivity_rows.append(temp_df)

sensitivity_df = pd.concat(sensitivity_rows, ignore_index=True)

display(sensitivity_df.head(20).round(4))

score_heatmap = sensitivity_df.pivot(index="Vùng", columns="AI_weight", values="TOPSIS_score")
score_heatmap = score_heatmap.loc[topsis_expert_rank["region_name_vi"]]

plt.figure(figsize=(11,6))
sns.heatmap(score_heatmap, annot=True, fmt=".3f", cmap="YlOrRd")
plt.title("Heatmap TOPSIS score khi thay đổi trọng số AI Readiness")
plt.xlabel("Trọng số AI Readiness")
plt.ylabel("Vùng")
plt.show()

rank_heatmap = sensitivity_df.pivot(index="Vùng", columns="AI_weight", values="Rank")
rank_heatmap = rank_heatmap.loc[topsis_expert_rank["region_name_vi"]]

plt.figure(figsize=(11,6))
sns.heatmap(rank_heatmap, annot=True, fmt=".0f", cmap="viridis_r")
plt.title("Heatmap thứ hạng khi thay đổi trọng số AI Readiness")
plt.xlabel("Trọng số AI Readiness")
plt.ylabel("Vùng")
plt.show()

print("Top-3 theo từng mức trọng số AI Readiness:")
for ai_w, top3 in top3_by_ai_weight.items():
    print(f"AI weight = {ai_w:.2f}: {top3}")

top3_sets = [tuple(v) for v in top3_by_ai_weight.values()]
top3_stable = len(set(top3_sets)) == 1

if top3_stable:
    print("""
Nhận xét:
Top-3 ổn định khi thay đổi trọng số AI Readiness.
Điều này cho thấy kết quả xếp hạng có độ vững cao.
""")
else:
    print("""
Nhận xét:
Top-3 có thay đổi khi trọng số AI Readiness thay đổi.
Điều này cho thấy ưu tiên đầu tư AI nhạy cảm với cách xác định trọng số chính sách.
""")

# ============================================================
# 8. CÂU 6.4.4 — MỞ RỘNG AHP ĐƠN GIẢN
# ============================================================

print("""
============================================================
8. CÂU 6.4.4 — MỞ RỘNG: AHP ĐƠN GIẢN
============================================================

AHP được dùng để tạo một bộ trọng số chủ quan dựa trên ma trận so sánh cặp.
Ở đây ta xây dựng một ma trận AHP đơn giản dựa trên mức độ quan trọng tương đối
giữa các tiêu chí đối với đầu tư AI.
""")

# Ma trận so sánh cặp AHP đơn giản, 8x8
# Thứ tự: GRDP, FDI, Digital, AI, Labor, R&D, Internet, Gini
AHP = np.array([
    [1,   1,   1/2, 1/3, 1/2, 1/2, 1,   2],
    [1,   1,   1/2, 1/3, 1/2, 1/2, 1,   2],
    [2,   2,   1,   1/2, 1,   1,   2,   3],
    [3,   3,   2,   1,   2,   2,   3,   4],
    [2,   2,   1,   1/2, 1,   1,   2,   3],
    [2,   2,   1,   1/2, 1,   1,   2,   3],
    [1,   1,   1/2, 1/3, 1/2, 1/2, 1,   2],
    [1/2, 1/2, 1/3, 1/4, 1/3, 1/3, 1/2, 1]
], dtype=float)

# Tính vector riêng chính
eigvals, eigvecs = np.linalg.eig(AHP)
max_idx = np.argmax(eigvals.real)
w_ahp = eigvecs[:, max_idx].real
w_ahp = w_ahp / w_ahp.sum()

# Kiểm tra consistency ratio
n = AHP.shape[0]
lambda_max = eigvals[max_idx].real
CI = (lambda_max - n) / (n - 1)

# Random Index RI cho n=8 ~ 1.41
RI = 1.41
CR = CI / RI

ahp_weight_df = pd.DataFrame({
    "Tiêu chí": criteria_vi,
    "Trọng số AHP": w_ahp
})

display(ahp_weight_df.round(4))

print(f"Lambda max = {lambda_max:.4f}")
print(f"CI = {CI:.4f}")
print(f"CR = {CR:.4f}")

if CR < 0.10:
    print("Ma trận AHP có mức nhất quán chấp nhận được.")
else:
    print("CR > 0.10, ma trận AHP chỉ nên dùng minh họa, cần hiệu chỉnh nếu dùng nghiêm ngặt.")

_, _, _, _, _, _, C_ahp = topsis(X, w_ahp, is_benefit)

topsis_ahp_df = df[["region_name_vi"]].copy()
topsis_ahp_df["TOPSIS_AHP_score"] = C_ahp
topsis_ahp_df["Rank_AHP"] = topsis_ahp_df["TOPSIS_AHP_score"].rank(
    ascending=False,
    method="min"
).astype(int)

display(topsis_ahp_df.sort_values("TOPSIS_AHP_score", ascending=False).round(4))

compare_all_df = compare_topsis_df.merge(topsis_ahp_df, on="region_name_vi")

display(compare_all_df.sort_values("Rank_expert").round(4))

compare_all_plot = compare_all_df.set_index("region_name_vi")[
    ["TOPSIS_score", "TOPSIS_entropy_score", "TOPSIS_AHP_score"]
]

compare_all_plot.plot(kind="bar", figsize=(12,6))
plt.title("So sánh TOPSIS theo trọng số chuyên gia, Entropy và AHP")
plt.ylabel("TOPSIS score")
plt.xlabel("Vùng")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 9. BIỂU ĐỒ MỞ RỘNG — RADAR TOP 3 VÀ AI-GINI MAP
# ============================================================

print("""
============================================================
9. BIỂU ĐỒ MỞ RỘNG — RADAR TOP 3 VÀ BẢN ĐỒ AI-GINI
============================================================
""")

# Min-max để radar dễ đọc
def minmax_norm(col):
    return (col - col.min()) / (col.max() - col.min())

radar_data = df.copy()

for c in criteria:
    if c == "gini_coef":
        radar_data[c + "_norm"] = (df[c].max() - df[c]) / (df[c].max() - df[c].min())
    else:
        radar_data[c + "_norm"] = minmax_norm(df[c])

top3_regions = top3_expert

radar_cols = [c + "_norm" for c in criteria]
radar_labels = criteria_vi

angles = np.linspace(0, 2*np.pi, len(radar_labels), endpoint=False).tolist()
angles += angles[:1]

plt.figure(figsize=(8,8))
ax = plt.subplot(111, polar=True)

for region in top3_regions:
    row = radar_data[radar_data["region_name_vi"] == region].iloc[0]
    values = row[radar_cols].values.flatten().tolist()
    values += values[:1]
    ax.plot(angles, values, linewidth=2, label=region)
    ax.fill(angles, values, alpha=0.08)

ax.set_xticks(angles[:-1])
ax.set_xticklabels(radar_labels)
ax.set_title("Radar chart hồ sơ tiêu chí của Top 3 vùng")
ax.legend(loc="upper right", bbox_to_anchor=(1.35, 1.1))
plt.show()

plt.figure(figsize=(10,6))
plt.scatter(
    df["ai_readiness_0_100"],
    df["gini_coef"],
    s=df["grdp_per_capita_million_VND"] * 8,
    alpha=0.7
)

for i, row in df.iterrows():
    plt.text(
        row["ai_readiness_0_100"] + 0.5,
        row["gini_coef"] + 0.001,
        row["region_name_vi"],
        fontsize=9
    )

plt.title("Bản đồ AI Readiness - Gini")
plt.xlabel("AI Readiness")
plt.ylabel("Gini, thấp hơn là tốt hơn")
plt.grid(True)
plt.show()

# ============================================================
# 10. MA TRẬN TƯƠNG QUAN
# ============================================================

print("""
============================================================
10. MA TRẬN TƯƠNG QUAN GIỮA CÁC TIÊU CHÍ
============================================================
""")

corr_df = df[criteria].corr()

plt.figure(figsize=(10,7))
sns.heatmap(corr_df, annot=True, fmt=".2f", cmap="coolwarm", center=0)
plt.title("Ma trận tương quan giữa các tiêu chí TOPSIS")
plt.show()

ai_internet_corr = corr_df.loc["ai_readiness_0_100", "internet_penetration_pct"]

print(f"""
Tương quan giữa AI Readiness và Internet penetration là {ai_internet_corr:.4f}.
Nếu tương quan cao, hai tiêu chí có thể đang đo lường một phần năng lực số giống nhau,
làm tăng trọng số thực tế của yếu tố hạ tầng số trong mô hình TOPSIS.
""")

# ============================================================
# 11. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
11. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

top_region_expert = top3_expert[0]
top3_for_centers = top3_expert

print(f"""
1. Vùng nào dẫn đầu theo TOPSIS với trọng số chuyên gia?

Vùng dẫn đầu là: {top_region_expert}

Điều này cho thấy vùng này có mức độ gần với phương án lý tưởng cao nhất,
xét trên các tiêu chí GRDP/người, FDI, Digital Index, AI Readiness,
lao động qua đào tạo, R&D, Internet và Gini.

Tuy nhiên, việc chọn trung tâm AI quốc gia đầu tiên không nên chỉ dựa trên TOPSIS.
Cần xem thêm các yếu tố địa - chính trị, năng lực trường đại học, cụm doanh nghiệp,
an ninh dữ liệu, hạ tầng điện toán và khả năng liên kết vùng.

2. Khi dùng trọng số Entropy, vùng nào thay đổi nhiều nhất?

Vùng thay đổi thứ hạng lớn nhất là: {largest_rank_change_region}

Nguyên nhân là Entropy weight không dựa trên đánh giá chủ quan của chuyên gia,
mà dựa trên mức phân tán dữ liệu. Tiêu chí nào có độ biến thiên lớn hơn giữa các vùng
sẽ có trọng số cao hơn. Vì vậy, các vùng mạnh ở tiêu chí có độ phân tán cao có thể tăng hạng.

3. TOPSIS giả định độc lập tuyến tính giữa các tiêu chí có vấn đề gì?

Trong thực tế, AI Readiness, Digital Index và Internet penetration có thể tương quan cao.
Nếu đưa cả ba tiêu chí vào mô hình mà không điều chỉnh, năng lực số có thể bị đếm lặp.
Điều này làm kết quả nghiêng về các vùng đã phát triển số mạnh.

Có thể xử lý bằng:
- kiểm tra tương quan,
- loại bớt tiêu chí trùng lặp,
- dùng PCA để giảm chiều,
- gom các tiêu chí số thành một chỉ số tổng hợp,
- hoặc dùng trọng số điều chỉnh sau tham vấn chuyên gia.

4. Nếu chọn 3 trung tâm AI lớn, nên chọn vùng nào?

Dựa trên TOPSIS trọng số chuyên gia, ba vùng đề xuất là:

1. {top3_for_centers[0]}
2. {top3_for_centers[1]}
3. {top3_for_centers[2]}

Tuy nhiên, cần cân nhắc thêm tiêu chí địa - chính trị và cân bằng vùng miền.
Nếu chỉ chọn theo năng lực sẵn có, các vùng phát triển hơn sẽ chiếm ưu thế.
Nếu mục tiêu là phát triển bao trùm, có thể cần một trung tâm đặt tại vùng đang tụt hậu
nhưng có tiềm năng chiến lược.
""")

# ============================================================
# 12. KẾT LUẬN
# ============================================================

print("""
============================================================
12. KẾT LUẬN
============================================================

Bài 6 đã áp dụng phương pháp TOPSIS để xếp hạng 6 vùng kinh tế - xã hội Việt Nam
theo mức độ ưu tiên đầu tư AI.

Kết quả với trọng số chuyên gia cho thấy các vùng có GRDP/người cao, FDI lớn,
Digital Index tốt, AI Readiness cao, lao động qua đào tạo và R&D mạnh thường
được xếp hạng cao hơn.

Khi sử dụng trọng số Entropy, kết quả có thể thay đổi do trọng số được xác định
khách quan dựa trên mức phân tán dữ liệu. Phân tích độ nhạy theo trọng số AI Readiness
cho thấy thứ hạng có thể ổn định hoặc thay đổi tùy mức độ phụ thuộc của mô hình
vào tiêu chí AI.

Mở rộng AHP cho thấy có thể kết hợp đánh giá chuyên gia vào quá trình xác định trọng số.
Tuy nhiên, lựa chọn vùng đầu tư AI không nên chỉ là quyết định kỹ thuật, mà cần kết hợp
phân tích định lượng với cân nhắc chính sách, liên kết vùng, an ninh dữ liệu và mục tiêu
phát triển bao trùm.
""")

