# -*- coding: utf-8 -*-
"""Bài 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PFy1DAdbSRzHqfvSQA6t5rqbP0uiwYnH
"""

# ============================================================
# BÀI 9 — TÁC ĐỘNG AI TỚI THỊ TRƯỜNG LAO ĐỘNG VIỆT NAM
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    import cvxpy as cp
except ModuleNotFoundError:
    !pip install cvxpy
    import cvxpy as cp

try:
    import plotly.graph_objects as go
except ModuleNotFoundError:
    !pip install plotly
    import plotly.graph_objects as go

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

AI và tự động hóa có thể làm thay đổi mạnh cấu trúc việc làm tại Việt Nam.
Một số công việc bị thay thế hoặc tái cấu trúc, đặc biệt trong các ngành
chế biến chế tạo, bán buôn-bán lẻ và logistics. Tuy nhiên, AI cũng có thể
tạo ra việc làm mới như kỹ sư AI, chuyên gia dữ liệu, người vận hành robot
và các vị trí quản trị công nghệ.

Bài toán đặt ra là:
Chính phủ cần phân bổ bao nhiêu ngân sách vào AI và đào tạo lại lao động
để bảo đảm không ngành nào bị mất việc làm ròng.
""")

# ============================================================
# 1. MÔ HÌNH TOÁN HỌC
# ============================================================

print("""
============================================================
1. MÔ HÌNH TOÁN HỌC
============================================================

Với mỗi ngành i:

NetJob_i = NewJob_AI_i + UpgradeJob_i - DisplacedJob_i

Trong đó:

NewJob_i = a1_i * x_AI_i

UpgradeJob_i = b1_i * x_H_i

DisplacedJob_i = c1_i * x_AI_i * risk_i

RetrainingCapacity_i = d1_i * x_H_i

Ràng buộc quan trọng:

DisplacedJob_i <= RetrainingCapacity_i

Ràng buộc này thể hiện nguyên tắc:
Tốc độ tự động hóa không nên vượt quá năng lực đào tạo lại.

Bài toán tối ưu:

Max Σ_i NetJob_i

s.t.
Σ_i (x_AI_i + x_H_i) <= 30000
NetJob_i >= 0
DisplacedJob_i <= RetrainingCapacity_i
x_AI_i, x_H_i >= 0
""")

# ============================================================
# 2. DỮ LIỆU ĐẦU VÀO
# ============================================================

print("""
============================================================
2. DỮ LIỆU ĐẦU VÀO
============================================================
""")

sectors = [
    "Nông-Lâm-Thủy sản",
    "CN chế biến chế tạo",
    "Xây dựng",
    "Bán buôn-bán lẻ",
    "Tài chính-Ngân hàng",
    "Logistics-Vận tải",
    "CNTT-Truyền thông",
    "Giáo dục-Đào tạo"
]

labor_million = np.array([13.20, 11.50, 4.80, 7.80, 0.55, 1.95, 0.62, 2.15])
risk = np.array([18, 42, 25, 38, 52, 35, 28, 22]) / 100

a1 = np.array([8.5, 32.5, 12.8, 22.4, 45.8, 28.5, 62.5, 18.5])
b1 = np.array([45.0, 28.0, 35.0, 32.0, 22.0, 30.0, 20.0, 55.0])
c1 = np.array([5.2, 62.4, 18.5, 48.2, 72.5, 42.8, 32.5, 12.5])
d1 = np.array([50.0, 32.0, 42.0, 38.0, 26.0, 36.0, 24.0, 62.0])

N = len(sectors)
budget = 30000

data_df = pd.DataFrame({
    "Ngành": sectors,
    "Lao động (triệu)": labor_million,
    "Risk": risk,
    "a1 NewJob/AI": a1,
    "b1 Upgrade/H": b1,
    "c1 Displaced/AI": c1,
    "d1 RetrainCap/H": d1
})

display(data_df)

plt.figure(figsize=(12,5))
plt.bar(data_df["Ngành"], data_df["Risk"] * 100)
plt.title("Rủi ro tự động hóa theo ngành")
plt.ylabel("Risk (%)")
plt.xticks(rotation=30, ha="right")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(12,5))
plt.bar(data_df["Ngành"], data_df["Lao động (triệu)"])
plt.title("Quy mô lao động theo ngành")
plt.ylabel("Triệu lao động")
plt.xticks(rotation=30, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 3. HÀM GIẢI MÔ HÌNH BẰNG CVXPY
# ============================================================

def solve_labor_model(add_displacement_cap=False):
    x_AI = cp.Variable(N, nonneg=True)
    x_H = cp.Variable(N, nonneg=True)

    NewJob = cp.multiply(a1, x_AI)
    UpgradeJob = cp.multiply(b1, x_H)
    DisplacedJob = cp.multiply(cp.multiply(c1, risk), x_AI)
    RetrainCap = cp.multiply(d1, x_H)

    NetJob = NewJob + UpgradeJob - DisplacedJob

    constraints = [
        cp.sum(x_AI + x_H) <= budget,
        NetJob >= 0,
        DisplacedJob <= RetrainCap
    ]

    if add_displacement_cap:
        # Lao động tính theo triệu người, đổi sang số việc làm.
        # 1 triệu lao động = 1,000,000 việc làm.
        labor_jobs = labor_million * 1_000_000
        constraints.append(DisplacedJob <= 0.05 * labor_jobs)

    prob = cp.Problem(cp.Maximize(cp.sum(NetJob)), constraints)

    try:
        prob.solve(solver=cp.CLARABEL)
    except:
        prob.solve(solver=cp.SCS)

    if prob.status not in ["optimal", "optimal_inaccurate"]:
        return None, prob.status

    result = pd.DataFrame({
        "Ngành": sectors,
        "x_AI": x_AI.value,
        "x_H": x_H.value,
        "NewJob": NewJob.value,
        "UpgradeJob": UpgradeJob.value,
        "DisplacedJob": DisplacedJob.value,
        "RetrainingCapacity": RetrainCap.value,
        "NetJob": NetJob.value
    })

    summary = {
        "status": prob.status,
        "objective": prob.value,
        "result": result,
        "total_budget_used": result["x_AI"].sum() + result["x_H"].sum()
    }

    return summary, prob.status

# ============================================================
# 4. CÂU 9.4.1 — GIẢI MÔ HÌNH CƠ SỞ
# ============================================================

print("""
============================================================
4. CÂU 9.4.1 — GIẢI MÔ HÌNH CƠ SỞ
============================================================
""")

base_summary, base_status = solve_labor_model(add_displacement_cap=False)

print("Trạng thái nghiệm:", base_status)

if base_status not in ["optimal", "optimal_inaccurate"]:
    raise ValueError("Mô hình cơ sở không tối ưu hoặc không khả thi.")

base_result = base_summary["result"]

print(f"Tổng NetJob tối ưu = {base_summary['objective']:,.4f}")
print(f"Tổng ngân sách sử dụng = {base_summary['total_budget_used']:,.4f}")

display(base_result.round(4))

plt.figure(figsize=(13,6))
plt.bar(base_result["Ngành"], base_result["x_AI"], label="Đầu tư AI")
plt.bar(base_result["Ngành"], base_result["x_H"], bottom=base_result["x_AI"], label="Đào tạo lại H")
plt.title("Phân bổ ngân sách tối ưu theo ngành")
plt.ylabel("Tỷ VND")
plt.xticks(rotation=30, ha="right")
plt.legend()
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(13,6))
plt.bar(base_result["Ngành"], base_result["NetJob"])
plt.title("NetJob ròng theo ngành")
plt.ylabel("Việc làm ròng")
plt.xticks(rotation=30, ha="right")
plt.grid(axis="y")
plt.show()

# Biểu đồ thành phần việc làm
job_component_df = base_result.set_index("Ngành")[["NewJob", "UpgradeJob", "DisplacedJob"]].copy()
job_component_df["DisplacedJob"] = -job_component_df["DisplacedJob"]

job_component_df.plot(kind="bar", stacked=True, figsize=(13,6))
plt.title("Thành phần tạo việc làm và mất việc theo ngành")
plt.ylabel("Số việc làm")
plt.xticks(rotation=30, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 5. CÂU 9.4.2 — NGƯỠNG ĐÀO TẠO TỐI THIỂU NGÀNH CHẾ BIẾN CHẾ TẠO
# ============================================================

print("""
============================================================
5. CÂU 9.4.2 — NGƯỠNG ĐẦU TƯ ĐÀO TẠO TỐI THIỂU CHO NGÀNH 2
============================================================
""")

idx_manufacturing = 1

# Nếu ngành 2 đầu tư AI tối đa theo ngân sách 30.000
x_AI_max = budget

# Điều kiện NetJob_2 >= 0:
# a1*x_AI + b1*x_H - c1*risk*x_AI >= 0
# => b1*x_H >= (c1*risk - a1)*x_AI
# => x_H >= ((c1*risk - a1)/b1)*x_AI

threshold_coef = (c1[idx_manufacturing] * risk[idx_manufacturing] - a1[idx_manufacturing]) / b1[idx_manufacturing]
x_H_threshold_netjob = max(0, threshold_coef * x_AI_max)

# Điều kiện Displaced <= RetrainCap:
# c1*risk*x_AI <= d1*x_H
# => x_H >= c1*risk*x_AI/d1

x_H_threshold_retrain = (
    c1[idx_manufacturing] * risk[idx_manufacturing] * x_AI_max / d1[idx_manufacturing]
)

x_H_threshold_required = max(x_H_threshold_netjob, x_H_threshold_retrain)

threshold_df = pd.DataFrame({
    "Chỉ tiêu": [
        "x_AI tối đa giả định",
        "Ngưỡng x_H để NetJob_2 >= 0",
        "Ngưỡng x_H để Displaced <= RetrainCap",
        "Ngưỡng x_H bắt buộc lớn nhất"
    ],
    "Giá trị": [
        x_AI_max,
        x_H_threshold_netjob,
        x_H_threshold_retrain,
        x_H_threshold_required
    ]
})

display(threshold_df.round(4))

print(f"""
Diễn giải:
Nếu đầu tư AI tối đa {x_AI_max:,.0f} tỷ VND vào ngành chế biến chế tạo,
ngưỡng đào tạo lại cần thiết là khoảng {x_H_threshold_required:,.2f} tỷ VND.

Trong trường hợp này, ràng buộc quyết định thường là:
DisplacedJob <= RetrainingCapacity,
vì tự động hóa không được vượt quá khả năng đào tạo lại lao động.
""")

# ============================================================
# 6. CÂU 9.4.3 — MÔ PHỎNG NHÓM DỄ BỊ TỔN THƯƠNG
# ============================================================

print("""
============================================================
6. CÂU 9.4.3 — MÔ PHỎNG NHÓM DỄ BỊ TỔN THƯƠNG
============================================================

Nhóm dễ bị tổn thương gồm lao động phổ thông trong các ngành:
1. Nông-Lâm-Thủy sản
3. Xây dựng
4. Bán buôn-bán lẻ
""")

vulnerable_indices = [0, 2, 3]
vulnerable_df = base_result.iloc[vulnerable_indices].copy()

display(vulnerable_df.round(4))

# Swimming lane / Sankey đơn giản:
# Lao động có nguy cơ -> Đào tạo lại -> Nâng cấp việc làm / Việc làm mới
labels = []
source = []
target = []
value = []

for _, row in vulnerable_df.iterrows():
    sector = row["Ngành"]

    risk_node = f"{sector}: nguy cơ dịch chuyển"
    retrain_node = f"{sector}: đào tạo lại"
    upgrade_node = f"{sector}: việc làm nâng cấp"
    new_node = f"{sector}: việc làm mới AI"

    labels.extend([risk_node, retrain_node, upgrade_node, new_node])

# Xóa trùng labels
labels = list(dict.fromkeys(labels))
label_idx = {label: i for i, label in enumerate(labels)}

for _, row in vulnerable_df.iterrows():
    sector = row["Ngành"]

    risk_node = f"{sector}: nguy cơ dịch chuyển"
    retrain_node = f"{sector}: đào tạo lại"
    upgrade_node = f"{sector}: việc làm nâng cấp"
    new_node = f"{sector}: việc làm mới AI"

    displaced = max(row["DisplacedJob"], 0)
    retrain = min(row["RetrainingCapacity"], displaced)
    upgrade = max(row["UpgradeJob"], 0)
    newjob = max(row["NewJob"], 0)

    source += [label_idx[risk_node], label_idx[retrain_node], label_idx[retrain_node]]
    target += [label_idx[retrain_node], label_idx[upgrade_node], label_idx[new_node]]
    value += [displaced, upgrade, newjob]

fig = go.Figure(data=[go.Sankey(
    node=dict(
        pad=15,
        thickness=15,
        line=dict(color="black", width=0.5),
        label=labels
    ),
    link=dict(
        source=source,
        target=target,
        value=value
    )
)])

fig.update_layout(
    title_text="Sankey / swimming lane: luồng dịch chuyển lao động nhóm dễ tổn thương",
    font_size=10
)

fig.show()

# Nếu plotly không hiển thị, vẽ bảng tóm tắt
vulnerable_flow_df = vulnerable_df[[
    "Ngành",
    "NewJob",
    "UpgradeJob",
    "DisplacedJob",
    "RetrainingCapacity",
    "NetJob"
]]

display(vulnerable_flow_df.round(4))

# ============================================================
# 7. CÂU 9.4.4 — RÀNG BUỘC KHÔNG NGÀNH NÀO MẤT QUÁ 5% LAO ĐỘNG
# ============================================================

print("""
============================================================
7. CÂU 9.4.4 — THÊM RÀNG BUỘC DISPLACED <= 5% LAO ĐỘNG
============================================================
""")

cap_summary, cap_status = solve_labor_model(add_displacement_cap=True)

print("Trạng thái nghiệm:", cap_status)

if cap_status not in ["optimal", "optimal_inaccurate"]:
    print("""
Kết luận:
Bài toán không khả thi khi thêm ràng buộc không ngành nào mất quá 5% lao động.
Điều này cho thấy cần tăng ngân sách, giảm tốc độ đầu tư AI, hoặc tăng hiệu quả đào tạo lại.
""")
else:
    cap_result = cap_summary["result"]

    print(f"Tổng NetJob với ràng buộc 5% = {cap_summary['objective']:,.4f}")
    print(f"Tổng ngân sách sử dụng = {cap_summary['total_budget_used']:,.4f}")

    display(cap_result.round(4))

    compare_cap_df = pd.DataFrame({
        "Ngành": sectors,
        "NetJob cơ sở": base_result["NetJob"],
        "NetJob với cap 5%": cap_result["NetJob"],
        "Displaced cơ sở": base_result["DisplacedJob"],
        "Displaced với cap 5%": cap_result["DisplacedJob"],
        "Giới hạn 5% lao động": labor_million * 1_000_000 * 0.05
    })

    display(compare_cap_df.round(4))

    compare_cap_df.set_index("Ngành")[["Displaced cơ sở", "Displaced với cap 5%", "Giới hạn 5% lao động"]].plot(
        kind="bar",
        figsize=(13,6)
    )
    plt.title("So sánh DisplacedJob trước và sau ràng buộc 5% lao động")
    plt.ylabel("Số việc làm")
    plt.xticks(rotation=30, ha="right")
    plt.grid(axis="y")
    plt.show()

# ============================================================
# 8. MỞ RỘNG — PHÂN TÍCH HIỆU QUẢ BIÊN
# ============================================================

print("""
============================================================
8. MỞ RỘNG — PHÂN TÍCH HIỆU QUẢ BIÊN CỦA AI VÀ ĐÀO TẠO
============================================================
""")

net_ai_coef = a1 - c1 * risk

efficiency_df = pd.DataFrame({
    "Ngành": sectors,
    "NetJob biên từ AI": net_ai_coef,
    "UpgradeJob biên từ H": b1,
    "RetrainingCapacity biên từ H": d1,
    "Risk": risk
})

display(efficiency_df.round(4))

plt.figure(figsize=(13,6))
x = np.arange(N)
plt.bar(x - 0.2, efficiency_df["NetJob biên từ AI"], width=0.4, label="NetJob biên từ AI")
plt.bar(x + 0.2, efficiency_df["UpgradeJob biên từ H"], width=0.4, label="UpgradeJob biên từ H")
plt.xticks(x, sectors, rotation=30, ha="right")
plt.title("So sánh hiệu quả biên của đầu tư AI và đào tạo H")
plt.ylabel("Việc làm/tỷ VND")
plt.legend()
plt.grid(axis="y")
plt.show()

# ============================================================
# 9. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
9. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

most_training_sector = base_result.sort_values("x_H", ascending=False).iloc[0]["Ngành"]
bank_idx = sectors.index("Tài chính-Ngân hàng")
agri_idx = sectors.index("Nông-Lâm-Thủy sản")

bank_row = base_result.iloc[bank_idx]
agri_row = base_result.iloc[agri_idx]

print(f"""
1. Ngành nào cần đầu tư đào tạo lại nhiều nhất?

Theo nghiệm tối ưu, ngành cần đầu tư đào tạo lại nhiều nhất là:

{most_training_sector}

Điều này phản ánh ngành đó có rủi ro dịch chuyển việc làm lớn, hoặc cần nhiều đào tạo lại
để bảo đảm DisplacedJob không vượt quá RetrainingCapacity.

2. Ngành Tài chính-Ngân hàng có rủi ro 52% nhưng hệ số tạo việc làm AI cao

Tài chính-Ngân hàng có rủi ro tự động hóa cao, nhưng cũng có hệ số tạo việc làm mới từ AI cao.
Kết quả mô hình cho ngành này:

- x_AI = {bank_row["x_AI"]:,.2f}
- x_H = {bank_row["x_H"]:,.2f}
- NewJob = {bank_row["NewJob"]:,.2f}
- DisplacedJob = {bank_row["DisplacedJob"]:,.2f}
- NetJob = {bank_row["NetJob"]:,.2f}

Mô hình khuyến nghị không nên né tránh AI trong tài chính-ngân hàng,
mà cần đi kèm đầu tư đào tạo lại và nâng cấp kỹ năng để chuyển lao động sang
các vị trí phân tích dữ liệu, quản trị rủi ro, an ninh mạng và vận hành hệ thống AI.

3. Có nên đầu tư AI vào Nông-Lâm-Thủy sản không?

Nông-Lâm-Thủy sản có hệ số tạo việc làm AI thấp hơn nhiều ngành khác,
nhưng quy mô lao động rất lớn. Kết quả mô hình cho ngành này:

- x_AI = {agri_row["x_AI"]:,.2f}
- x_H = {agri_row["x_H"]:,.2f}
- NetJob = {agri_row["NetJob"]:,.2f}

Nếu mô hình phân bổ ít AI cho nông nghiệp, điều đó cho thấy đầu tư AI trực tiếp
không phải cách tạo việc làm hiệu quả nhất trong ngắn hạn. Tuy nhiên, về chính sách,
vẫn cần đầu tư AI có chọn lọc vào nông nghiệp thông minh, dự báo khí hậu, truy xuất nguồn gốc
và logistics nông sản, kèm theo đào tạo kỹ năng số cho lao động nông thôn.

4. Ràng buộc nào biểu diễn nguyên tắc tốc độ tự động hóa không vượt quá năng lực đào tạo lại?

Ràng buộc đó là:

DisplacedJob_i <= RetrainingCapacity_i

Nghĩa là số việc làm bị dịch chuyển do tự động hóa trong ngành i không được vượt quá
khả năng đào tạo lại của ngành đó.

5. Đề xuất bổ sung ràng buộc an sinh xã hội

Có thể thêm các ràng buộc:
- DisplacedJob_i <= 5% tổng lao động ngành i
- x_H_i >= một mức tối thiểu cho các ngành đông lao động
- NetJob_i >= 0 cho từng ngành
- ưu tiên đào tạo lại cho lao động phổ thông, lao động nữ và lao động ở vùng khó khăn
- giới hạn tốc độ tăng x_AI ở ngành có rủi ro cao nếu năng lực đào tạo chưa đủ
""")

# ============================================================
# 10. KẾT LUẬN
# ============================================================

print("""
============================================================
10. KẾT LUẬN
============================================================

Bài 9 đã xây dựng mô hình tuyến tính để phân tích tác động của AI và tự động hóa
đến thị trường lao động Việt Nam.

Mô hình cho thấy AI vừa có khả năng tạo việc làm mới, vừa có thể làm dịch chuyển
một bộ phận lao động hiện hữu. Do đó, chính sách AI không thể tách rời chính sách
đào tạo lại và nâng cấp kỹ năng.

Ràng buộc DisplacedJob <= RetrainingCapacity thể hiện nguyên tắc quan trọng:
tốc độ tự động hóa không nên vượt quá năng lực đào tạo lại của nền kinh tế.

Kết quả mô phỏng nhóm dễ bị tổn thương và ràng buộc mất việc tối đa 5% lao động
cho thấy cần thiết kế chính sách lao động theo ngành, thay vì áp dụng một chính sách
chung cho toàn bộ nền kinh tế.

Về mặt chính sách, Việt Nam cần kết hợp đầu tư AI với:
- đào tạo lại lao động,
- nâng cấp kỹ năng số,
- hỗ trợ nhóm dễ bị tổn thương,
- bảo hiểm thất nghiệp chủ động,
- và cơ chế chuyển đổi nghề nghiệp theo ngành.
""")

