# -*- coding: utf-8 -*-
"""Bài 10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eDkRFFst0g0Nh2KyJxVah_iB7tzHeVbK
"""

# ============================================================
# BÀI 10 — QUY HOẠCH NGẪU NHIÊN HAI GIAI ĐOẠN DƯỚI BẤT ĐỊNH
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    import pyomo.environ as pyo
except ModuleNotFoundError:
    !pip install pyomo
    import pyomo.environ as pyo

# Cài CBC/GLPK cho Colab nếu cần
# Nếu dòng apt-get không chạy trong môi trường của bạn, có thể bỏ qua và dùng scipy fallback ở cuối.
import shutil
if shutil.which("cbc") is None and shutil.which("glpsol") is None:
    !apt-get update -qq
    !apt-get install -y -qq coinor-cbc glpk-utils

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Việt Nam là nền kinh tế có độ mở thương mại cao, phụ thuộc lớn vào cầu xuất khẩu,
dòng vốn FDI và môi trường kinh tế toàn cầu.

Khi hoạch định chính sách đầu tư số giai đoạn 2026–2030, Chính phủ phải ra quyết định
phân bổ ngân sách ban đầu khi chưa biết chắc kịch bản tương lai sẽ xảy ra.

Bài toán này sử dụng quy hoạch ngẫu nhiên hai giai đoạn:

- Giai đoạn 1: quyết định here-and-now, tức phân bổ ngân sách ban đầu.
- Giai đoạn 2: quyết định wait-and-see, tức điều chỉnh ngân sách sau khi biết kịch bản.

Mục tiêu là tối đa hóa GDP gain kỳ vọng dưới bất định.
""")

# ============================================================
# 1. MÔ HÌNH TOÁN HỌC
# ============================================================

print("""
============================================================
1. MÔ HÌNH TOÁN HỌC
============================================================

Tập hạng mục đầu tư:

J = {I, D, AI, H}

Trong đó:
I  : hạ tầng số
D  : chuyển đổi số
AI : trí tuệ nhân tạo
H  : nhân lực số

Giai đoạn 1:
x_j >= 0 là ngân sách phân bổ ban đầu cho hạng mục j.

Ràng buộc:
Σ_j x_j <= 65.000

Giai đoạn 2:
y_sj >= 0 là ngân sách điều chỉnh cho hạng mục j trong kịch bản s.

Ràng buộc:
Σ_j y_sj <= 15.000 với mọi s

Ràng buộc năng lực AI:
y_s,AI <= 0.5*x_H

Hàm mục tiêu stochastic programming:

Max Σ_j beta_j*x_j + Σ_s p_s * Σ_j beta_sj*y_sj

Mô hình này cho phép quyết định ban đầu vừa tạo lợi ích trực tiếp,
vừa giữ khả năng thích ứng theo từng kịch bản tương lai.
""")

# ============================================================
# 2. DỮ LIỆU KỊCH BẢN VÀ HỆ SỐ
# ============================================================

print("""
============================================================
2. DỮ LIỆU KỊCH BẢN VÀ HỆ SỐ
============================================================
""")

J = ["I", "D", "AI", "H"]
J_name = {
    "I": "Hạ tầng số",
    "D": "Chuyển đổi số",
    "AI": "Trí tuệ nhân tạo",
    "H": "Nhân lực số"
}

S = ["s1", "s2", "s3", "s4"]
S_name = {
    "s1": "Lạc quan",
    "s2": "Cơ sở",
    "s3": "Bi quan",
    "s4": "Khủng hoảng"
}

prob = {
    "s1": 0.30,
    "s2": 0.45,
    "s3": 0.20,
    "s4": 0.05
}

scenario_df = pd.DataFrame({
    "Kịch bản": [S_name[s] for s in S],
    "Tăng trưởng TG (%)": [3.5, 2.8, 1.5, 0.2],
    "FDI VN (tỷ USD/năm)": [32.0, 27.0, 20.0, 12.0],
    "Xuất khẩu VN tăng (%)": [12.0, 8.0, 3.0, -5.0],
    "Xác suất": [prob[s] for s in S]
})

display(scenario_df)

beta = {
    "I": 1.00,
    "D": 1.10,
    "AI": 1.25,
    "H": 0.95
}

beta_s = {
    ("s1","I"):1.25, ("s1","D"):1.35, ("s1","AI"):1.55, ("s1","H"):1.05,
    ("s2","I"):1.00, ("s2","D"):1.10, ("s2","AI"):1.25, ("s2","H"):0.95,
    ("s3","I"):0.75, ("s3","D"):0.85, ("s3","AI"):0.90, ("s3","H"):1.00,
    ("s4","I"):0.40, ("s4","D"):0.50, ("s4","AI"):0.55, ("s4","H"):1.10
}

beta_s_df = pd.DataFrame(
    [[S_name[s]] + [beta_s[(s,j)] for j in J] for s in S],
    columns=["Kịch bản"] + [J_name[j] for j in J]
)

display(beta_s_df)

plt.figure(figsize=(9,5))
for j in J:
    plt.plot([S_name[s] for s in S], [beta_s[(s,j)] for s in S], marker="o", linewidth=2, label=J_name[j])
plt.title("Hệ số beta theo kịch bản")
plt.xlabel("Kịch bản")
plt.ylabel("Beta")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# 3. HÀM CHỌN SOLVER
# ============================================================

def get_solver():
    if shutil.which("cbc") is not None:
        return pyo.SolverFactory("cbc")
    elif shutil.which("glpsol") is not None:
        return pyo.SolverFactory("glpk")
    else:
        return None

solver = get_solver()

if solver is None:
    print("Không tìm thấy CBC/GLPK. Hãy kiểm tra cài đặt solver.")
else:
    print("Solver đang dùng:", solver.name)

# ============================================================
# 4. HÀM GIẢI MÔ HÌNH STOCHASTIC PROGRAMMING
# ============================================================

def solve_sp_model(scenario_prob=prob, beta_s_input=beta_s, fixed_x=None):
    """
    Giải mô hình stochastic two-stage.

    scenario_prob: xác suất từng kịch bản.
    beta_s_input: hệ số beta theo kịch bản.
    fixed_x: nếu không None, cố định x theo dictionary.
    """

    m = pyo.ConcreteModel()

    m.J = pyo.Set(initialize=J)
    m.S = pyo.Set(initialize=S)

    m.p = pyo.Param(m.S, initialize=scenario_prob)
    m.beta = pyo.Param(m.J, initialize=beta)
    m.beta_s = pyo.Param(m.S, m.J, initialize=beta_s_input)

    m.x = pyo.Var(m.J, within=pyo.NonNegativeReals)
    m.y = pyo.Var(m.S, m.J, within=pyo.NonNegativeReals)

    # Ngân sách giai đoạn 1
    m.budget1 = pyo.Constraint(expr=sum(m.x[j] for j in m.J) <= 65000)

    # Ngân sách giai đoạn 2
    def budget2_rule(m, s):
        return sum(m.y[s,j] for j in m.J) <= 15000

    m.budget2 = pyo.Constraint(m.S, rule=budget2_rule)

    # Năng lực AI phụ thuộc đầu tư H giai đoạn 1
    def ai_capacity_rule(m, s):
        return m.y[s, "AI"] <= 0.5 * m.x["H"]

    m.ai_capacity = pyo.Constraint(m.S, rule=ai_capacity_rule)

    # Nếu fixed_x được đưa vào, cố định quyết định first-stage
    if fixed_x is not None:
        def fixed_x_rule(m, j):
            return m.x[j] == fixed_x[j]
        m.fixed_x_constraint = pyo.Constraint(m.J, rule=fixed_x_rule)

    # Objective
    def obj_rule(m):
        first = sum(m.beta[j] * m.x[j] for j in m.J)
        second = sum(
            m.p[s] * sum(m.beta_s[s,j] * m.y[s,j] for j in m.J)
            for s in m.S
        )
        return first + second

    m.obj = pyo.Objective(rule=obj_rule, sense=pyo.maximize)

    result = solver.solve(m, tee=False)

    status = str(result.solver.termination_condition)

    if status.lower() not in ["optimal", "feasible"]:
        return None, status

    x_sol = {j: pyo.value(m.x[j]) for j in J}
    y_sol = {(s,j): pyo.value(m.y[s,j]) for s in S for j in J}
    obj_val = pyo.value(m.obj)

    return {
        "model": m,
        "x": x_sol,
        "y": y_sol,
        "objective": obj_val,
        "status": status
    }, status

# ============================================================
# 5. CÂU 10.5.1 — GIẢI MÔ HÌNH SP
# ============================================================

print("""
============================================================
5. CÂU 10.5.1 — GIẢI MÔ HÌNH STOCHASTIC PROGRAMMING
============================================================
""")

sp_solution, sp_status = solve_sp_model()

print("Trạng thái SP:", sp_status)

if sp_solution is None:
    raise ValueError("Mô hình SP không giải được.")

sp_x_df = pd.DataFrame({
    "Hạng mục": [J_name[j] for j in J],
    "x_j first-stage": [sp_solution["x"][j] for j in J],
    "Beta cơ bản": [beta[j] for j in J]
})

display(sp_x_df.round(4))

print(f"Giá trị mục tiêu SP = {sp_solution['objective']:,.4f}")

sp_y_df = pd.DataFrame(
    [
        {
            "Kịch bản": S_name[s],
            "Hạng mục": J_name[j],
            "y_sj second-stage": sp_solution["y"][(s,j)]
        }
        for s in S for j in J
    ]
)

display(sp_y_df.pivot(index="Kịch bản", columns="Hạng mục", values="y_sj second-stage").round(4))

plt.figure(figsize=(9,5))
plt.bar(sp_x_df["Hạng mục"], sp_x_df["x_j first-stage"])
plt.title("Quyết định first-stage tối ưu của mô hình SP")
plt.ylabel("Nghìn tỷ VND")
plt.grid(axis="y")
plt.show()

sp_y_pivot = sp_y_df.pivot(index="Kịch bản", columns="Hạng mục", values="y_sj second-stage")
sp_y_pivot.plot(kind="bar", stacked=True, figsize=(10,5))
plt.title("Quyết định second-stage theo từng kịch bản")
plt.ylabel("Nghìn tỷ VND")
plt.xticks(rotation=0)
plt.grid(axis="y")
plt.show()

# ============================================================
# 6. CÂU 10.5.2 — DETERMINISTIC THEO TỪNG KỊCH BẢN
# ============================================================

print("""
============================================================
6. CÂU 10.5.2 — GIẢI BÀI TOÁN XÁC ĐỊNH THEO TỪNG KỊCH BẢN
============================================================
""")

def solve_deterministic_for_scenario(scenario):
    """
    Giải mô hình nếu biết chắc kịch bản scenario xảy ra.
    Khi đó xác suất của scenario = 1, các scenario khác = 0.
    """

    scenario_prob = {s: 1.0 if s == scenario else 0.0 for s in S}
    sol, status = solve_sp_model(scenario_prob=scenario_prob)
    return sol, status

det_rows = []
det_solutions = {}

for s in S:
    sol_s, status_s = solve_deterministic_for_scenario(s)
    det_solutions[s] = sol_s

    row = {
        "Kịch bản": S_name[s],
        "Status": status_s,
        "Objective": sol_s["objective"] if sol_s else np.nan
    }

    for j in J:
        row[f"x_{j}"] = sol_s["x"][j] if sol_s else np.nan

    det_rows.append(row)

det_df = pd.DataFrame(det_rows)

display(det_df.round(4))

det_df.set_index("Kịch bản")[[f"x_{j}" for j in J]].plot(kind="bar", figsize=(10,5))
plt.title("So sánh quyết định first-stage nếu biết trước từng kịch bản")
plt.ylabel("Nghìn tỷ VND")
plt.xticks(rotation=0)
plt.grid(axis="y")
plt.show()

# ============================================================
# 7. LỜI GIẢI EXPECTED VALUE EV
# ============================================================

print("""
============================================================
7. LỜI GIẢI KỲ VỌNG EV — EXPECTED VALUE SOLUTION
============================================================

Tính beta trung bình theo xác suất rồi giải bài toán xác định với kịch bản trung bình.
""")

beta_ev = {}

for j in J:
    beta_ev[j] = sum(prob[s] * beta_s[(s,j)] for s in S)

beta_ev_df = pd.DataFrame({
    "Hạng mục": [J_name[j] for j in J],
    "Beta cơ bản": [beta[j] for j in J],
    "Beta second-stage kỳ vọng": [beta_ev[j] for j in J]
})

display(beta_ev_df.round(4))

# Tạo beta_s_input giống nhau cho mọi kịch bản bằng beta_ev
beta_s_ev = {(s,j): beta_ev[j] for s in S for j in J}

ev_solution, ev_status = solve_sp_model(
    scenario_prob=prob,
    beta_s_input=beta_s_ev
)

print("Trạng thái EV:", ev_status)

ev_x = ev_solution["x"]

ev_x_df = pd.DataFrame({
    "Hạng mục": [J_name[j] for j in J],
    "x_EV": [ev_x[j] for j in J],
    "x_SP": [sp_solution["x"][j] for j in J]
})

display(ev_x_df.round(4))

ev_x_df.set_index("Hạng mục")[["x_EV", "x_SP"]].plot(kind="bar", figsize=(9,5))
plt.title("So sánh quyết định first-stage: EV và SP")
plt.ylabel("Nghìn tỷ VND")
plt.xticks(rotation=20)
plt.grid(axis="y")
plt.show()

# ============================================================
# 8. ĐÁNH GIÁ EEV, VSS VÀ EVPI
# ============================================================

print("""
============================================================
8. CÂU 10.5.3 — TÍNH EEV, VSS VÀ EVPI
============================================================
""")

# RP = recourse problem value = giá trị SP tối ưu
RP = sp_solution["objective"]

# EEV = giá trị kỳ vọng nếu dùng quyết định EV trong bài toán stochastic thật
eev_solution, eev_status = solve_sp_model(
    scenario_prob=prob,
    beta_s_input=beta_s,
    fixed_x=ev_x
)

EEV = eev_solution["objective"]

# VSS = RP - EEV đối với bài toán maximize
VSS = RP - EEV

# EVPI:
# WS = expected value của wait-and-see = sum p_s * optimal value if scenario known
WS = sum(prob[s] * det_solutions[s]["objective"] for s in S)

EVPI = WS - RP

metrics_df = pd.DataFrame({
    "Chỉ tiêu": [
        "RP/SP value",
        "EEV value",
        "VSS = RP - EEV",
        "WS value",
        "EVPI = WS - RP"
    ],
    "Giá trị": [RP, EEV, VSS, WS, EVPI]
})

display(metrics_df.round(4))

print(f"""
Diễn giải:

RP/SP value = {RP:,.4f}
là giá trị tối ưu khi giải bài toán stochastic programming.

EEV = {EEV:,.4f}
là giá trị đạt được nếu dùng lời giải expected value trong mô hình stochastic thật.

VSS = {VSS:,.4f}
đo lợi ích của việc xét bất định khi ra quyết định.

WS = {WS:,.4f}
là giá trị kỳ vọng nếu biết trước kịch bản nào sẽ xảy ra.

EVPI = {EVPI:,.4f}
đo giá trị tối đa của thông tin hoàn hảo.
""")

plt.figure(figsize=(9,5))
plt.bar(metrics_df["Chỉ tiêu"], metrics_df["Giá trị"])
plt.title("So sánh RP, EEV, VSS, WS và EVPI")
plt.ylabel("Giá trị mục tiêu")
plt.xticks(rotation=30, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 9. CÂU 10.5.4 — ROBUST OPTIMIZATION: MINIMAX REGRET
# ============================================================

print("""
============================================================
9. CÂU 10.5.4 — MỞ RỘNG ROBUST OPTIMIZATION: MINIMAX REGRET
============================================================

Robust regret chọn quyết định sao cho regret kịch bản xấu nhất là nhỏ nhất.
Ở đây ta mô hình hóa:

min R
s.t. R >= Opt_s - Value_s(x) với mọi s
""")

def solve_robust_regret():
    m = pyo.ConcreteModel()

    m.J = pyo.Set(initialize=J)
    m.S = pyo.Set(initialize=S)

    m.beta = pyo.Param(m.J, initialize=beta)
    m.beta_s = pyo.Param(m.S, m.J, initialize=beta_s)

    scenario_opt = {s: det_solutions[s]["objective"] for s in S}

    m.x = pyo.Var(m.J, within=pyo.NonNegativeReals)
    m.y = pyo.Var(m.S, m.J, within=pyo.NonNegativeReals)
    m.R = pyo.Var(within=pyo.NonNegativeReals)

    m.budget1 = pyo.Constraint(expr=sum(m.x[j] for j in m.J) <= 65000)

    def budget2_rule(m, s):
        return sum(m.y[s,j] for j in m.J) <= 15000

    m.budget2 = pyo.Constraint(m.S, rule=budget2_rule)

    def ai_capacity_rule(m, s):
        return m.y[s, "AI"] <= 0.5 * m.x["H"]

    m.ai_capacity = pyo.Constraint(m.S, rule=ai_capacity_rule)

    def value_s_expr(m, s):
        first = sum(m.beta[j] * m.x[j] for j in m.J)
        second = sum(m.beta_s[s,j] * m.y[s,j] for j in m.J)
        return first + second

    def regret_rule(m, s):
        return m.R >= scenario_opt[s] - value_s_expr(m, s)

    m.regret_constraints = pyo.Constraint(m.S, rule=regret_rule)

    m.obj = pyo.Objective(expr=m.R, sense=pyo.minimize)

    result = solver.solve(m, tee=False)
    status = str(result.solver.termination_condition)

    if status.lower() not in ["optimal", "feasible"]:
        return None, status

    x_sol = {j: pyo.value(m.x[j]) for j in J}
    y_sol = {(s,j): pyo.value(m.y[s,j]) for s in S for j in J}
    R_val = pyo.value(m.R)

    return {
        "model": m,
        "x": x_sol,
        "y": y_sol,
        "max_regret": R_val,
        "status": status
    }, status

robust_solution, robust_status = solve_robust_regret()

print("Trạng thái robust:", robust_status)

if robust_solution is not None:
    robust_x_df = pd.DataFrame({
        "Hạng mục": [J_name[j] for j in J],
        "x_SP": [sp_solution["x"][j] for j in J],
        "x_EV": [ev_x[j] for j in J],
        "x_RobustRegret": [robust_solution["x"][j] for j in J]
    })

    display(robust_x_df.round(4))

    robust_x_df.set_index("Hạng mục").plot(kind="bar", figsize=(10,5))
    plt.title("So sánh first-stage: SP, EV và Robust Regret")
    plt.ylabel("Nghìn tỷ VND")
    plt.xticks(rotation=20)
    plt.grid(axis="y")
    plt.show()

    print(f"Regret xấu nhất của lời giải robust = {robust_solution['max_regret']:,.4f}")

# ============================================================
# 10. SO SÁNH GIÁ TRỊ THEO TỪNG KỊCH BẢN CỦA SP, EV, ROBUST
# ============================================================

print("""
============================================================
10. SO SÁNH GIÁ TRỊ THEO TỪNG KỊCH BẢN
============================================================
""")

def evaluate_fixed_x_under_single_scenario(x_fixed, scenario):
    scenario_prob = {s: 1.0 if s == scenario else 0.0 for s in S}
    sol, status = solve_sp_model(
        scenario_prob=scenario_prob,
        beta_s_input=beta_s,
        fixed_x=x_fixed
    )
    return sol["objective"] if sol else np.nan

scenario_value_rows = []

for s in S:
    row = {
        "Kịch bản": S_name[s],
        "Optimal if known": det_solutions[s]["objective"],
        "SP decision": evaluate_fixed_x_under_single_scenario(sp_solution["x"], s),
        "EV decision": evaluate_fixed_x_under_single_scenario(ev_x, s)
    }

    if robust_solution is not None:
        row["Robust decision"] = evaluate_fixed_x_under_single_scenario(robust_solution["x"], s)

    scenario_value_rows.append(row)

scenario_value_df = pd.DataFrame(scenario_value_rows)

display(scenario_value_df.round(4))

scenario_value_df.set_index("Kịch bản").plot(kind="bar", figsize=(11,5))
plt.title("Giá trị đạt được theo từng kịch bản")
plt.ylabel("Giá trị mục tiêu")
plt.xticks(rotation=0)
plt.grid(axis="y")
plt.show()

# ============================================================
# 11. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
11. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

sp_H = sp_solution["x"]["H"]
ev_H = ev_x["H"]

direction_H = "nhiều hơn" if sp_H > ev_H else "ít hơn hoặc tương đương"

print(f"""
1. So với lời giải xác định EV, lời giải SP đầu tư H nhiều hơn hay ít hơn?

Trong kết quả hiện tại:

x_H của SP = {sp_H:,.4f}
x_H của EV = {ev_H:,.4f}

Do đó, SP đầu tư vào H {direction_H} so với EV.

Nếu SP đầu tư H nhiều hơn, điều này phản ánh vai trò của nhân lực số như một
hàng hóa bảo hiểm: trong kịch bản khủng hoảng, H có hệ số hiệu quả cao hơn
vì lao động qua đào tạo có khả năng thích ứng và chuyển đổi việc làm tốt hơn.

2. VSS dương nói lên điều gì?

VSS = {VSS:,.4f}

Nếu VSS dương, việc xét bất định khi ra quyết định tạo ra giá trị cao hơn
so với việc chỉ dùng một kịch bản kỳ vọng. Điều này cho thấy tư duy xác suất
có ý nghĩa trong hoạch định chính sách Việt Nam, đặc biệt trong bối cảnh nền kinh tế
phụ thuộc vào FDI, xuất khẩu và các cú sốc toàn cầu.

3. EVPI có ý nghĩa gì?

EVPI = {EVPI:,.4f}

EVPI đo giá trị tối đa của thông tin hoàn hảo. Nếu EVPI lớn, điều đó cho thấy
thông tin về kịch bản tương lai rất có giá trị và Chính phủ nên đầu tư vào
năng lực dự báo, dữ liệu, cảnh báo sớm và phân tích rủi ro.

4. Bài học từ COVID-19 và bão Yagi

Các cú sốc như COVID-19 và bão Yagi cho thấy chính sách công không nên chỉ tối ưu
cho kịch bản trung bình. Nếu chỉ tập trung vào hiệu quả ngắn hạn, Việt Nam có thể
dưới đầu tư vào các năng lực chống chịu như nhân lực số, dữ liệu, y tế số,
logistics số và an ninh mạng.

Mô hình gợi ý rằng nhân lực số không chỉ là yếu tố tăng trưởng, mà còn là
một dạng năng lực bảo hiểm xã hội trước bất định.
""")

# ============================================================
# 12. KẾT LUẬN
# ============================================================

print("""
============================================================
12. KẾT LUẬN
============================================================

Bài 10 đã xây dựng mô hình quy hoạch ngẫu nhiên hai giai đoạn để phân bổ ngân sách
đầu tư số trong bối cảnh bất định.

Mô hình phân biệt rõ:
- quyết định first-stage here-and-now,
- và quyết định second-stage wait-and-see theo từng kịch bản.

Kết quả SP được so sánh với lời giải expected value, lời giải xác định theo từng
kịch bản và mô hình robust regret. Các chỉ tiêu VSS và EVPI giúp lượng hóa giá trị
của việc xét bất định và giá trị của thông tin hoàn hảo.

Về mặt chính sách, mô hình cho thấy trong một nền kinh tế có độ mở cao như Việt Nam,
hoạch định ngân sách cần dựa trên phân tích kịch bản, không nên chỉ dựa vào một
dự báo trung bình duy nhất. Đầu tư vào nhân lực số, năng lực dữ liệu và khả năng
điều chỉnh chính sách có thể giúp nền kinh tế chống chịu tốt hơn trước các cú sốc.
""")

