# -*- coding: utf-8 -*-
"""Bài 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCcezFVbVWvgitOZ7SKQAs8RUqTv9bwt
"""

# ============================================================
# BÀI 7 — TỐI ƯU ĐA MỤC TIÊU PARETO VỚI NSGA-II
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    import seaborn as sns
except ModuleNotFoundError:
    !pip install seaborn
    import seaborn as sns

try:
    import pymoo
except ModuleNotFoundError:
    !pip install pymoo
    import pymoo

from pymoo.core.problem import ElementwiseProblem
from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.optimize import minimize

from pandas.plotting import parallel_coordinates
from mpl_toolkits.mplot3d import Axes3D

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Trong hoạch định chính sách phát triển kinh tế số và AI, không phải lúc nào
cũng tồn tại một nghiệm tối ưu duy nhất.

Việt Nam đồng thời theo đuổi nhiều mục tiêu:
1. Tăng trưởng GDP nhanh.
2. Bao trùm xã hội và giảm bất bình đẳng vùng.
3. Giảm phát thải và hướng tới net-zero.
4. Bảo đảm an ninh dữ liệu và chủ quyền số.

Các mục tiêu này có thể xung đột với nhau. Ví dụ:
- Tăng đầu tư AI và hạ tầng số có thể làm tăng GDP nhưng cũng tăng phát thải.
- Tập trung vốn vào vùng phát triển có thể tăng hiệu quả nhưng giảm bao trùm.
- Đầu tư AI có thể tăng rủi ro dữ liệu nếu thiếu nhân lực quản trị số.

Vì vậy, Bài 7 sử dụng NSGA-II để tìm tập nghiệm Pareto thay vì một nghiệm duy nhất.
""")

# ============================================================
# 1. MÔ HÌNH TOÁN HỌC
# ============================================================

print("""
============================================================
1. MÔ HÌNH TOÁN HỌC
============================================================

Biến quyết định:

x[j,r] >= 0

là ngân sách phân bổ cho hạng mục j tại vùng r.

Có 6 vùng và 4 hạng mục đầu tư:
I  : hạ tầng số
D  : chuyển đổi số doanh nghiệp / dữ liệu
AI : năng lực AI
H  : nhân lực số

Tổng số biến quyết định: 6 x 4 = 24.

Bốn mục tiêu:

1. Tối đa hóa tăng trưởng GDP:
max f1 = Σ_r Σ_j beta[j,r] * x[j,r]

Trong pymoo, bài toán được đưa về minimization nên dùng:
min -f1

2. Tối thiểu hóa bất bình đẳng vùng:
min f2 = MAD ngân sách vùng
MAD = mean(|budget_r - mean_budget|)

3. Tối thiểu hóa phát thải gián tiếp:
min f3 = Σ_r e_r * (x[I,r] + x[AI,r])

4. Tối thiểu hóa rủi ro an ninh dữ liệu ròng:
min f4 = Σ_r rho_r*x[AI,r] - Σ_r sigma_r*x[H,r]

Các ràng buộc kế thừa từ Bài 4:
- Tổng ngân sách <= 50.000
- Mỗi vùng nhận tối thiểu 5.000
- Mỗi vùng nhận tối đa 12.000
- Tổng đầu tư nhân lực số >= 12.000
""")

# ============================================================
# 2. DỮ LIỆU ĐẦU VÀO
# ============================================================

print("""
============================================================
2. DỮ LIỆU ĐẦU VÀO
============================================================
""")

regions = ["NMM", "RRD", "NCC", "CH", "SE", "MD"]

region_names = {
    "NMM": "Trung du miền núi phía Bắc",
    "RRD": "Đồng bằng sông Hồng",
    "NCC": "Bắc Trung Bộ + DH Trung Bộ",
    "CH": "Tây Nguyên",
    "SE": "Đông Nam Bộ",
    "MD": "Đồng bằng sông Cửu Long"
}

items = ["I", "D", "AI", "H"]

item_names = {
    "I": "Hạ tầng số",
    "D": "CĐS/Dữ liệu",
    "AI": "Năng lực AI",
    "H": "Nhân lực số"
}

beta = np.array([
    [1.15, 0.85, 0.55, 1.30],  # NMM
    [0.95, 1.25, 1.40, 1.05],  # RRD
    [1.05, 0.95, 0.85, 1.15],  # NCC
    [1.20, 0.75, 0.45, 1.35],  # CH
    [0.90, 1.30, 1.55, 1.00],  # SE
    [1.10, 0.85, 0.65, 1.25],  # MD
])

# Tham số bổ sung từ đề bài
e = np.array([0.42, 0.55, 0.48, 0.32, 0.62, 0.38])
rho = np.array([0.18, 0.45, 0.28, 0.12, 0.52, 0.22])
sigma = np.array([0.32, 0.28, 0.30, 0.35, 0.25, 0.30])

param_df = pd.DataFrame({
    "Vùng": [region_names[r] for r in regions],
    "e_r CO2/tỷ": e,
    "rho_r rủi ro AI": rho,
    "sigma_r giảm rủi ro H": sigma
})

display(param_df)

beta_df = pd.DataFrame(
    beta,
    index=[region_names[r] for r in regions],
    columns=[item_names[j] for j in items]
)

display(beta_df)

plt.figure(figsize=(10,5))
sns.heatmap(beta_df, annot=True, fmt=".2f", cmap="YlGnBu")
plt.title("Heatmap hệ số tác động GDP beta[j,r]")
plt.xlabel("Hạng mục")
plt.ylabel("Vùng")
plt.show()

# ============================================================
# 3. ĐỊNH NGHĨA BÀI TOÁN NSGA-II
# ============================================================

print("""
============================================================
3. CÀI ĐẶT BÀI TOÁN BẰNG PYMOO
============================================================
""")

class VietnamDigitalProblem(ElementwiseProblem):
    def __init__(self):
        super().__init__(
            n_var=24,
            n_obj=4,
            n_ieq_constr=14,
            xl=np.zeros(24),
            xu=np.ones(24) * 12000
        )

        self.beta = beta
        self.e = e
        self.rho = rho
        self.sigma = sigma

    def _evaluate(self, x, out, *args, **kwargs):
        X = x.reshape(6, 4)

        # Tổng ngân sách theo vùng
        region_sum = X.sum(axis=1)

        # f1: maximize GDP gain => minimize negative GDP gain
        gdp_gain = (self.beta * X).sum()
        f1 = -gdp_gain

        # f2: minimize inequality, dùng mean absolute deviation
        f2 = np.abs(region_sum - region_sum.mean()).mean()

        # f3: minimize emissions from infrastructure and AI
        f3 = (self.e * (X[:, 0] + X[:, 2])).sum()

        # f4: minimize net data security risk
        f4 = (self.rho * X[:, 2]).sum() - (self.sigma * X[:, 3]).sum()

        out["F"] = [f1, f2, f3, f4]

        # Ràng buộc dạng G <= 0
        G = []

        # C1 total budget <= 50000
        G.append(X.sum() - 50000)

        # C2 each region >= 5000 => 5000 - region_sum <= 0
        for i in range(6):
            G.append(5000 - region_sum[i])

        # C3 each region <= 12000
        for i in range(6):
            G.append(region_sum[i] - 12000)

        # C4 human capital >= 12000
        G.append(12000 - X[:, 3].sum())

        out["G"] = np.array(G)

# ============================================================
# 4. CÂU 7.4.1 — CHẠY NSGA-II
# ============================================================

print("""
============================================================
4. CÂU 7.4.1 — CHẠY NSGA-II
============================================================
""")

problem = VietnamDigitalProblem()

algorithm = NSGA2(
    pop_size=100
)

res = minimize(
    problem,
    algorithm,
    ("n_gen", 200),
    seed=42,
    verbose=True
)

X_pareto = res.X
F_pareto = res.F

print("Số nghiệm Pareto thu được:", len(F_pareto))

# Chuyển f1 về GDP gain dương để dễ đọc
pareto_df = pd.DataFrame({
    "GDP_gain": -F_pareto[:, 0],
    "Inequality_MAD": F_pareto[:, 1],
    "Emission": F_pareto[:, 2],
    "Data_risk": F_pareto[:, 3]
})

display(pareto_df.describe().round(4))

# ============================================================
# 5. CÂU 7.4.2 — VẼ PARETO 3D VÀ PARALLEL COORDINATES
# ============================================================

print("""
============================================================
5. CÂU 7.4.2 — TRỰC QUAN HÓA TẬP PARETO
============================================================
""")

fig = plt.figure(figsize=(10,7))
ax = fig.add_subplot(111, projection="3d")

sc = ax.scatter(
    pareto_df["GDP_gain"],
    pareto_df["Inequality_MAD"],
    pareto_df["Emission"],
    c=pareto_df["Data_risk"],
    cmap="viridis",
    s=40
)

ax.set_xlabel("GDP gain, càng cao càng tốt")
ax.set_ylabel("Inequality MAD, càng thấp càng tốt")
ax.set_zlabel("Emission, càng thấp càng tốt")
ax.set_title("Pareto front 3D: GDP - Bao trùm - Môi trường")
plt.colorbar(sc, label="Data risk")
plt.show()

# Chuẩn hóa để vẽ parallel coordinates
pareto_norm = pareto_df.copy()

for col in pareto_norm.columns:
    pareto_norm[col] = (pareto_norm[col] - pareto_norm[col].min()) / (
        pareto_norm[col].max() - pareto_norm[col].min() + 1e-12
    )

pareto_norm["Solution"] = "Pareto"

plt.figure(figsize=(12,6))
parallel_coordinates(
    pareto_norm[["Solution", "GDP_gain", "Inequality_MAD", "Emission", "Data_risk"]],
    "Solution",
    alpha=0.15
)
plt.title("Parallel coordinates của tập nghiệm Pareto")
plt.ylabel("Giá trị chuẩn hóa")
plt.grid(True)
plt.show()

# Các biểu đồ 2D mở rộng
plt.figure(figsize=(8,5))
plt.scatter(pareto_df["GDP_gain"], pareto_df["Inequality_MAD"], alpha=0.7)
plt.title("Đánh đổi giữa tăng trưởng và bao trùm")
plt.xlabel("GDP gain")
plt.ylabel("Inequality MAD")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(pareto_df["GDP_gain"], pareto_df["Emission"], alpha=0.7)
plt.title("Đánh đổi giữa tăng trưởng và phát thải")
plt.xlabel("GDP gain")
plt.ylabel("Emission")
plt.grid(True)
plt.show()

plt.figure(figsize=(8,5))
plt.scatter(pareto_df["GDP_gain"], pareto_df["Data_risk"], alpha=0.7)
plt.title("Đánh đổi giữa tăng trưởng và rủi ro dữ liệu")
plt.xlabel("GDP gain")
plt.ylabel("Data risk")
plt.grid(True)
plt.show()

# ============================================================
# 6. CÂU 7.4.3 — CHỌN NGHIỆM THỎA HIỆP BẰNG TOPSIS
# ============================================================

print("""
============================================================
6. CÂU 7.4.3 — CHỌN NGHIỆM THỎA HIỆP BẰNG TOPSIS
============================================================
""")

# TOPSIS trên tập Pareto
# Các tiêu chí:
# GDP_gain là benefit
# Inequality, Emission, Data_risk là cost

policy_weights = np.array([0.40, 0.25, 0.20, 0.15])
is_benefit = np.array([True, False, False, False])

Y = pareto_df[["GDP_gain", "Inequality_MAD", "Emission", "Data_risk"]].values.astype(float)

# Vector normalization
R = Y / np.sqrt((Y ** 2).sum(axis=0))

V = R * policy_weights

A_star = np.where(is_benefit, V.max(axis=0), V.min(axis=0))
A_neg = np.where(is_benefit, V.min(axis=0), V.max(axis=0))

S_star = np.sqrt(((V - A_star) ** 2).sum(axis=1))
S_neg = np.sqrt(((V - A_neg) ** 2).sum(axis=1))

C_star = S_neg / (S_star + S_neg)

pareto_df["TOPSIS_score"] = C_star
pareto_df["Solution_ID"] = np.arange(len(pareto_df))

best_idx = pareto_df["TOPSIS_score"].idxmax()

best_solution = X_pareto[best_idx].reshape(6,4)
best_objectives = pareto_df.loc[best_idx]

print("Nghiệm thỏa hiệp được chọn bởi TOPSIS:")
display(best_objectives.to_frame("Giá trị").round(4))

best_alloc_df = pd.DataFrame(
    best_solution,
    index=[region_names[r] for r in regions],
    columns=[item_names[j] for j in items]
)

print("Ma trận phân bổ ngân sách của nghiệm thỏa hiệp:")
display(best_alloc_df.round(2))

plt.figure(figsize=(12,6))
sns.heatmap(best_alloc_df, annot=True, fmt=".0f", cmap="Blues")
plt.title("Heatmap phân bổ ngân sách — nghiệm thỏa hiệp TOPSIS")
plt.xlabel("Hạng mục")
plt.ylabel("Vùng")
plt.show()

# Bar tổng ngân sách theo vùng
best_region_sum = best_alloc_df.sum(axis=1)
best_item_sum = best_alloc_df.sum(axis=0)

plt.figure(figsize=(11,5))
plt.bar(best_region_sum.index, best_region_sum.values)
plt.title("Tổng ngân sách theo vùng — nghiệm thỏa hiệp")
plt.ylabel("Tỷ VND")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(9,5))
plt.bar(best_item_sum.index, best_item_sum.values)
plt.title("Tổng ngân sách theo hạng mục — nghiệm thỏa hiệp")
plt.ylabel("Tỷ VND")
plt.grid(axis="y")
plt.show()

# Highlight nghiệm compromise trong scatter
fig = plt.figure(figsize=(10,7))
ax = fig.add_subplot(111, projection="3d")

ax.scatter(
    pareto_df["GDP_gain"],
    pareto_df["Inequality_MAD"],
    pareto_df["Emission"],
    alpha=0.5,
    label="Pareto solutions"
)

ax.scatter(
    best_objectives["GDP_gain"],
    best_objectives["Inequality_MAD"],
    best_objectives["Emission"],
    s=180,
    marker="*",
    label="TOPSIS compromise"
)

ax.set_xlabel("GDP gain")
ax.set_ylabel("Inequality MAD")
ax.set_zlabel("Emission")
ax.set_title("Nghiệm thỏa hiệp TOPSIS trên Pareto front")
ax.legend()
plt.show()

# ============================================================
# 7. CÂU 7.4.4 — CHI PHÍ CƠ HỘI CỦA MỤC TIÊU TĂNG TRƯỞNG
# ============================================================

print("""
============================================================
7. CÂU 7.4.4 — CHI PHÍ CƠ HỘI CỦA NGHIỆM TĂNG TRƯỞNG CAO NHẤT
============================================================
""")

growth_idx = pareto_df["GDP_gain"].idxmax()
growth_solution = pareto_df.loc[growth_idx]

opportunity_df = pd.DataFrame({
    "Chỉ tiêu": [
        "GDP gain",
        "Inequality MAD",
        "Emission",
        "Data risk"
    ],
    "Nghiệm thỏa hiệp TOPSIS": [
        best_objectives["GDP_gain"],
        best_objectives["Inequality_MAD"],
        best_objectives["Emission"],
        best_objectives["Data_risk"]
    ],
    "Nghiệm tăng trưởng cao nhất": [
        growth_solution["GDP_gain"],
        growth_solution["Inequality_MAD"],
        growth_solution["Emission"],
        growth_solution["Data_risk"]
    ]
})

opportunity_df["Chênh lệch tuyệt đối"] = (
    opportunity_df["Nghiệm tăng trưởng cao nhất"] -
    opportunity_df["Nghiệm thỏa hiệp TOPSIS"]
)

opportunity_df["Chênh lệch % so với thỏa hiệp"] = (
    opportunity_df["Chênh lệch tuyệt đối"] /
    opportunity_df["Nghiệm thỏa hiệp TOPSIS"].replace(0, np.nan)
    * 100
)

display(opportunity_df.round(4))

ineq_cost_pct = (
    (growth_solution["Inequality_MAD"] - best_objectives["Inequality_MAD"])
    / best_objectives["Inequality_MAD"] * 100
)

emission_cost_pct = (
    (growth_solution["Emission"] - best_objectives["Emission"])
    / best_objectives["Emission"] * 100
)

print(f"""
So với nghiệm thỏa hiệp TOPSIS:

- Nghiệm tăng trưởng cao nhất làm bất bình đẳng vùng thay đổi khoảng {ineq_cost_pct:.2f}%.
- Nghiệm tăng trưởng cao nhất làm phát thải thay đổi khoảng {emission_cost_pct:.2f}%.

Đây là chi phí cơ hội của việc ưu tiên tăng trưởng GDP cao nhất.
""")

# Phân bổ nghiệm tăng trưởng cao nhất
growth_alloc = X_pareto[growth_idx].reshape(6,4)

growth_alloc_df = pd.DataFrame(
    growth_alloc,
    index=[region_names[r] for r in regions],
    columns=[item_names[j] for j in items]
)

print("Ma trận phân bổ ngân sách của nghiệm tăng trưởng cao nhất:")
display(growth_alloc_df.round(2))

# So sánh ngân sách theo vùng: compromise vs growth max
compare_region = pd.DataFrame({
    "TOPSIS compromise": best_alloc_df.sum(axis=1),
    "Growth max": growth_alloc_df.sum(axis=1)
})

compare_region.plot(kind="bar", figsize=(12,6))
plt.title("So sánh phân bổ theo vùng: nghiệm thỏa hiệp và nghiệm tăng trưởng cao nhất")
plt.ylabel("Tỷ VND")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 8. MỞ RỘNG — SO SÁNH CÁC NGHIỆM CỰC TRỊ
# ============================================================

print("""
============================================================
8. MỞ RỘNG — SO SÁNH CÁC NGHIỆM CỰC TRỊ TRÊN PARETO FRONT
============================================================
""")

best_growth_idx = pareto_df["GDP_gain"].idxmax()
best_inclusion_idx = pareto_df["Inequality_MAD"].idxmin()
best_environment_idx = pareto_df["Emission"].idxmin()
best_security_idx = pareto_df["Data_risk"].idxmin()

extreme_df = pd.DataFrame({
    "Loại nghiệm": [
        "Tăng trưởng cao nhất",
        "Bao trùm tốt nhất",
        "Môi trường tốt nhất",
        "An ninh dữ liệu tốt nhất",
        "Thỏa hiệp TOPSIS"
    ],
    "Solution_ID": [
        best_growth_idx,
        best_inclusion_idx,
        best_environment_idx,
        best_security_idx,
        best_idx
    ],
    "GDP_gain": [
        pareto_df.loc[best_growth_idx, "GDP_gain"],
        pareto_df.loc[best_inclusion_idx, "GDP_gain"],
        pareto_df.loc[best_environment_idx, "GDP_gain"],
        pareto_df.loc[best_security_idx, "GDP_gain"],
        pareto_df.loc[best_idx, "GDP_gain"]
    ],
    "Inequality_MAD": [
        pareto_df.loc[best_growth_idx, "Inequality_MAD"],
        pareto_df.loc[best_inclusion_idx, "Inequality_MAD"],
        pareto_df.loc[best_environment_idx, "Inequality_MAD"],
        pareto_df.loc[best_security_idx, "Inequality_MAD"],
        pareto_df.loc[best_idx, "Inequality_MAD"]
    ],
    "Emission": [
        pareto_df.loc[best_growth_idx, "Emission"],
        pareto_df.loc[best_inclusion_idx, "Emission"],
        pareto_df.loc[best_environment_idx, "Emission"],
        pareto_df.loc[best_security_idx, "Emission"],
        pareto_df.loc[best_idx, "Emission"]
    ],
    "Data_risk": [
        pareto_df.loc[best_growth_idx, "Data_risk"],
        pareto_df.loc[best_inclusion_idx, "Data_risk"],
        pareto_df.loc[best_environment_idx, "Data_risk"],
        pareto_df.loc[best_security_idx, "Data_risk"],
        pareto_df.loc[best_idx, "Data_risk"]
    ]
})

display(extreme_df.round(4))

extreme_plot = extreme_df.set_index("Loại nghiệm")[
    ["GDP_gain", "Inequality_MAD", "Emission", "Data_risk"]
].copy()

# Chuẩn hóa min-max để so sánh trực quan
for col in extreme_plot.columns:
    extreme_plot[col] = (extreme_plot[col] - extreme_plot[col].min()) / (
        extreme_plot[col].max() - extreme_plot[col].min() + 1e-12
    )

extreme_plot.plot(kind="bar", figsize=(13,6))
plt.title("So sánh các nghiệm cực trị và nghiệm thỏa hiệp")
plt.ylabel("Giá trị chuẩn hóa")
plt.xticks(rotation=25, ha="right")
plt.grid(axis="y")
plt.show()

# ============================================================
# 9. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
9. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

print(f"""
1. Đánh đổi giữa tăng trưởng và bao trùm có rõ ràng không?

Kết quả Pareto cho thấy tồn tại đánh đổi giữa tăng trưởng GDP và bao trùm vùng.
Các nghiệm có GDP gain cao thường có xu hướng phân bổ ngân sách nhiều hơn
vào các vùng hoặc hạng mục có hiệu quả biên cao. Điều này có thể làm tăng
bất bình đẳng phân bổ giữa các vùng.

Nói cách khác, nếu chỉ ưu tiên tăng trưởng, mô hình dễ nghiêng về hiệu quả kinh tế.
Nếu ưu tiên bao trùm, mô hình phải chấp nhận giảm một phần tăng trưởng để phân bổ
đều hơn giữa các vùng.

2. Trọng số chính sách (0.40; 0.25; 0.20; 0.15) có hợp lý không?

Bộ trọng số này đặt tăng trưởng GDP là ưu tiên lớn nhất, nhưng vẫn dành trọng số đáng kể
cho bao trùm, môi trường và an ninh dữ liệu.

Nếu muốn phù hợp hơn với cam kết COP26 và mục tiêu net-zero, có thể tăng trọng số
môi trường từ 0.20 lên 0.25 hoặc 0.30.

Nếu muốn phù hợp hơn với Quyết định 127/QĐ-TTg về AI, có thể giữ trọng số tăng trưởng
cao nhưng tăng thêm tiêu chí an ninh dữ liệu, vì AI càng phát triển thì rủi ro dữ liệu
và chủ quyền số càng quan trọng.

3. Vai trò của NSGA-II khác gì LP đơn mục tiêu?

LP đơn mục tiêu đưa ra một nghiệm tối ưu duy nhất theo một hàm mục tiêu.
Trong khi đó, NSGA-II tạo ra một tập nghiệm Pareto, cho thấy nhiều phương án
khả thi với các mức đánh đổi khác nhau.

Điều này phù hợp hơn với chính sách công, vì chính sách thực tế thường không chỉ
tối đa hóa một chỉ tiêu mà phải cân bằng giữa tăng trưởng, công bằng, môi trường
và an ninh.

4. NSGA-II có thay thế được quyết định chính trị không?

Không. NSGA-II chỉ là công cụ hỗ trợ ra quyết định.
Nó giúp minh bạch hóa các đánh đổi chính sách, nhưng không thể tự quyết định
xã hội nên ưu tiên mục tiêu nào.

Việc chọn nghiệm cuối cùng vẫn cần:
- thảo luận chính sách,
- tham vấn chuyên gia,
- cân nhắc thể chế,
- đánh giá tác động xã hội,
- và quyết định chính trị hợp pháp.
""")

# ============================================================
# 10. KẾT LUẬN
# ============================================================

print("""
============================================================
10. KẾT LUẬN
============================================================

Bài 7 đã xây dựng mô hình tối ưu đa mục tiêu cho phân bổ ngân sách kinh tế số
và AI tại Việt Nam.

Khác với các bài toán LP đơn mục tiêu, mô hình này xem xét đồng thời bốn mục tiêu:
tăng trưởng GDP, bao trùm vùng, môi trường và an ninh dữ liệu.

Thuật toán NSGA-II cho phép trích xuất tập nghiệm Pareto, qua đó thể hiện rõ
các đánh đổi giữa các mục tiêu chính sách. Sau đó, TOPSIS được sử dụng để chọn
một nghiệm thỏa hiệp dựa trên bộ trọng số chính sách.

Kết quả cho thấy tối ưu hóa chính sách công không chỉ là bài toán kỹ thuật.
Tập nghiệm Pareto giúp nhà hoạch định chính sách nhìn thấy nhiều phương án lựa chọn,
nhưng quyết định cuối cùng vẫn cần được đặt trong bối cảnh ưu tiên phát triển,
cam kết môi trường, an ninh dữ liệu và tính chính danh chính sách.
""")

