# -*- coding: utf-8 -*-
"""Bài 8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-AL9Dt3O2JxTACFzp5uLsZpMGoSca0G
"""

# ============================================================
# BÀI 8 — TỐI ƯU ĐỘNG PHÂN BỔ LIÊN THỜI GIAN 2026–2035
# Dạng notebook/báo cáo thực nghiệm dùng cho Google Colab
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import minimize

pd.set_option("display.float_format", lambda x: f"{x:,.4f}")

# ============================================================
# 0. BỐI CẢNH BÀI TOÁN
# ============================================================

print("""
============================================================
0. BỐI CẢNH BÀI TOÁN
============================================================

Việt Nam đặt mục tiêu trở thành nước thu nhập trung bình cao vào năm 2030
và nước phát triển có thu nhập cao vào năm 2045.

Để đạt mục tiêu đó, Chính phủ cần thiết kế chiến lược phân bổ vốn dài hạn
giữa bốn nhóm đầu tư:

1. Vốn vật chất K
2. Hạ tầng số D
3. Năng lực AI
4. Vốn nhân lực H

Bài toán này xây dựng mô hình tối ưu động giai đoạn 2026–2035 để xác định
quỹ đạo tiêu dùng và đầu tư tối ưu theo thời gian.
""")

# ============================================================
# 1. MÔ HÌNH TOÁN HỌC
# ============================================================

print("""
============================================================
1. MÔ HÌNH TOÁN HỌC
============================================================

Mục tiêu:

Max Σ rho^t * log(C_t)

Trong đó:
- C_t là tiêu dùng tại năm t.
- rho là hệ số chiết khấu liên thời gian.

Hàm sản xuất Cobb-Douglas mở rộng:

Y_t = A_t * K_t^0.33 * L_t^0.42 * D_t^0.10 * AI_t^0.08 * H_t^0.07

Động học tích lũy vốn:

K_{t+1}  = (1 - delta_K)*K_t  + I_K,t
D_{t+1}  = (1 - delta_D)*D_t  + I_D,t
AI_{t+1} = (1 - delta_AI)*AI_t + I_AI,t
H_{t+1}  = H_t + theta_H*I_H,t - mu*H_t

Ràng buộc nguồn lực hằng năm:

C_t + I_K,t + I_D,t + I_AI,t + I_H,t <= Y_t

Vì bài toán có hàm Cobb-Douglas phi tuyến, ta giải bằng scipy.optimize.minimize
với phương pháp SLSQP.
""")

# ============================================================
# 2. THAM SỐ MÔ HÌNH
# ============================================================

print("""
============================================================
2. THAM SỐ MÔ HÌNH
============================================================
""")

years = np.arange(2026, 2036)
T = len(years)

# Hệ số Cobb-Douglas
alpha_K = 0.33
alpha_L = 0.42
alpha_D = 0.10
alpha_AI = 0.08
alpha_H = 0.07

# Tham số động học
delta_K = 0.05
delta_D = 0.12
delta_AI = 0.15
theta_H = 0.8
mu = 0.02

# TFP endogenous
phi1 = 0.003
phi2 = 0.002
phi3 = 0.004

rho = 0.97

# Điều kiện ban đầu 2026
K0 = 27500.0
L0 = 53.9
D0 = 20.3
AI0 = 86.0
H0 = 30.0
A0 = 35.0

params_df = pd.DataFrame({
    "Tham số": [
        "alpha_K", "alpha_L", "alpha_D", "alpha_AI", "alpha_H",
        "delta_K", "delta_D", "delta_AI", "theta_H", "mu",
        "phi1", "phi2", "phi3", "rho",
        "K0", "L0", "D0", "AI0", "H0", "A0"
    ],
    "Giá trị": [
        alpha_K, alpha_L, alpha_D, alpha_AI, alpha_H,
        delta_K, delta_D, delta_AI, theta_H, mu,
        phi1, phi2, phi3, rho,
        K0, L0, D0, AI0, H0, A0
    ]
})

display(params_df)

# ============================================================
# 3. CÁC HÀM PHỤ TRỢ
# ============================================================

def production(A, K, L, D, AI, H):
    """Hàm sản xuất Cobb-Douglas mở rộng."""
    return A * (K ** alpha_K) * (L ** alpha_L) * (D ** alpha_D) * (AI ** alpha_AI) * (H ** alpha_H)


def simulate_path(investment_shares, shock_2028=False):
    """
    investment_shares là vector độ dài 4*T:
    mỗi năm gồm tỷ lệ đầu tư vào K, D, AI, H trên Y_t.
    Tiêu dùng là phần còn lại.

    shares phải không âm và tổng 4 khoản đầu tư mỗi năm < 1.
    """

    shares = investment_shares.reshape(T, 4)

    K = np.zeros(T + 1)
    D = np.zeros(T + 1)
    AI = np.zeros(T + 1)
    H = np.zeros(T + 1)
    A = np.zeros(T + 1)
    Y = np.zeros(T)
    C = np.zeros(T)

    I_K = np.zeros(T)
    I_D = np.zeros(T)
    I_AI = np.zeros(T)
    I_H = np.zeros(T)

    K[0] = K0
    D[0] = D0
    AI[0] = AI0
    H[0] = H0
    A[0] = A0

    welfare = 0

    for t in range(T):
        L_t = L0 * ((1.006) ** t)

        Y_t = production(A[t], K[t], L_t, D[t], AI[t], H[t])

        # Shock năm 2028, tức t = 2
        if shock_2028 and years[t] == 2028:
            Y_t = Y_t * 0.92

        Y[t] = Y_t

        sK, sD, sAI, sH = shares[t]
        total_s = sK + sD + sAI + sH

        if total_s >= 0.95:
            return None

        I_K[t] = sK * Y_t
        I_D[t] = sD * Y_t
        I_AI[t] = sAI * Y_t
        I_H[t] = sH * Y_t

        C[t] = Y_t - I_K[t] - I_D[t] - I_AI[t] - I_H[t]

        if C[t] <= 0:
            return None

        welfare += (rho ** t) * np.log(C[t])

        K[t+1] = (1 - delta_K) * K[t] + I_K[t]
        D[t+1] = (1 - delta_D) * D[t] + I_D[t]
        AI[t+1] = (1 - delta_AI) * AI[t] + I_AI[t]
        H[t+1] = H[t] + theta_H * I_H[t] - mu * H[t]

        A[t+1] = A[t] * (1 + phi1 * D[t] + phi2 * AI[t] + phi3 * H[t])

    result = {
        "K": K,
        "D": D,
        "AI": AI,
        "H": H,
        "A": A,
        "Y": Y,
        "C": C,
        "I_K": I_K,
        "I_D": I_D,
        "I_AI": I_AI,
        "I_H": I_H,
        "welfare": welfare,
        "shares": shares
    }

    return result


def objective(x):
    """Hàm mục tiêu cho scipy: minimize negative welfare."""
    sim = simulate_path(x, shock_2028=False)

    if sim is None:
        return 1e9

    return -sim["welfare"]


def yearly_budget_constraint(x):
    """
    Ràng buộc tổng tỷ lệ đầu tư mỗi năm <= 0.80.
    Để tránh nghiệm tiêu dùng quá thấp, đặt trần đầu tư 80% Y_t.
    """
    shares = x.reshape(T, 4)
    return 0.80 - shares.sum(axis=1)


# ============================================================
# 4. CÂU 8.3.1 — TỐI ƯU BẰNG SCIPY SLSQP
# ============================================================

print("""
============================================================
4. CÂU 8.3.1 — GIẢI BÀI TOÁN BẰNG SCIPY SLSQP
============================================================
""")

# Khởi tạo: mỗi năm đầu tư 10% Y vào K, 5% vào D, 4% vào AI, 5% vào H
x0 = np.tile(np.array([0.10, 0.05, 0.04, 0.05]), T)

bounds = [(0.00, 0.50)] * (4 * T)

constraints = [
    {
        "type": "ineq",
        "fun": yearly_budget_constraint
    }
]

res = minimize(
    objective,
    x0,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints,
    options={
        "maxiter": 2000,
        "ftol": 1e-9,
        "disp": True
    }
)

print("Trạng thái tối ưu:", res.message)
print("Giá trị welfare tối ưu:", -res.fun)

opt_sim = simulate_path(res.x, shock_2028=False)

if opt_sim is None:
    raise ValueError("Không mô phỏng được nghiệm tối ưu.")

# ============================================================
# 5. CÂU 8.3.2 — BẢNG VÀ BIỂU ĐỒ QUỸ ĐẠO TỐI ƯU
# ============================================================

print("""
============================================================
5. CÂU 8.3.2 — QUỸ ĐẠO TỐI ƯU 2026–2035
============================================================
""")

opt_df = pd.DataFrame({
    "Năm": years,
    "K": opt_sim["K"][:-1],
    "D": opt_sim["D"][:-1],
    "AI": opt_sim["AI"][:-1],
    "H": opt_sim["H"][:-1],
    "A": opt_sim["A"][:-1],
    "Y": opt_sim["Y"],
    "C": opt_sim["C"],
    "I_K": opt_sim["I_K"],
    "I_D": opt_sim["I_D"],
    "I_AI": opt_sim["I_AI"],
    "I_H": opt_sim["I_H"],
    "Tỷ lệ đầu tư K": opt_sim["shares"][:, 0],
    "Tỷ lệ đầu tư D": opt_sim["shares"][:, 1],
    "Tỷ lệ đầu tư AI": opt_sim["shares"][:, 2],
    "Tỷ lệ đầu tư H": opt_sim["shares"][:, 3]
})

display(opt_df.round(4))

plt.figure(figsize=(12,6))
for col in ["K", "D", "AI", "H"]:
    plt.plot(opt_df["Năm"], opt_df[col], marker="o", linewidth=2, label=col)
plt.title("Quỹ đạo tối ưu của K, D, AI, H")
plt.xlabel("Năm")
plt.ylabel("Mức vốn/trạng thái")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(12,6))
plt.plot(opt_df["Năm"], opt_df["Y"], marker="o", linewidth=3, label="Y - sản lượng")
plt.plot(opt_df["Năm"], opt_df["C"], marker="s", linewidth=3, label="C - tiêu dùng")
plt.title("Quỹ đạo tối ưu của sản lượng Y và tiêu dùng C")
plt.xlabel("Năm")
plt.ylabel("Giá trị")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(12,6))
plt.stackplot(
    opt_df["Năm"],
    opt_df["I_K"],
    opt_df["I_D"],
    opt_df["I_AI"],
    opt_df["I_H"],
    labels=["I_K", "I_D", "I_AI", "I_H"]
)
plt.title("Cơ cấu đầu tư tối ưu theo thời gian")
plt.xlabel("Năm")
plt.ylabel("Mức đầu tư")
plt.legend(loc="upper left")
plt.grid(True)
plt.show()

plt.figure(figsize=(12,6))
for col in ["Tỷ lệ đầu tư K", "Tỷ lệ đầu tư D", "Tỷ lệ đầu tư AI", "Tỷ lệ đầu tư H"]:
    plt.plot(opt_df["Năm"], opt_df[col], marker="o", linewidth=2, label=col)
plt.title("Tỷ lệ đầu tư tối ưu theo thời gian")
plt.xlabel("Năm")
plt.ylabel("Tỷ lệ trên Y")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# 6. CÂU 8.3.3 — CÚ SỐC NĂM 2028
# ============================================================

print("""
============================================================
6. CÂU 8.3.3 — PHÂN TÍCH CÚ SỐC NĂM 2028
============================================================

Giả sử năm 2028 xảy ra khủng hoảng khiến Y_2028 giảm 8%.
Ta giữ cùng chiến lược đầu tư tối ưu ban đầu và quan sát quỹ đạo điều chỉnh.
""")

shock_sim = simulate_path(res.x, shock_2028=True)

shock_df = pd.DataFrame({
    "Năm": years,
    "Y cơ sở": opt_sim["Y"],
    "Y có cú sốc": shock_sim["Y"],
    "C cơ sở": opt_sim["C"],
    "C có cú sốc": shock_sim["C"],
    "K cơ sở": opt_sim["K"][:-1],
    "K có cú sốc": shock_sim["K"][:-1],
    "D cơ sở": opt_sim["D"][:-1],
    "D có cú sốc": shock_sim["D"][:-1],
    "AI cơ sở": opt_sim["AI"][:-1],
    "AI có cú sốc": shock_sim["AI"][:-1],
    "H cơ sở": opt_sim["H"][:-1],
    "H có cú sốc": shock_sim["H"][:-1]
})

shock_df["Chênh lệch Y (%)"] = (shock_df["Y có cú sốc"] - shock_df["Y cơ sở"]) / shock_df["Y cơ sở"] * 100
shock_df["Chênh lệch C (%)"] = (shock_df["C có cú sốc"] - shock_df["C cơ sở"]) / shock_df["C cơ sở"] * 100

display(shock_df.round(4))

plt.figure(figsize=(12,6))
plt.plot(shock_df["Năm"], shock_df["Y cơ sở"], marker="o", linewidth=3, label="Y cơ sở")
plt.plot(shock_df["Năm"], shock_df["Y có cú sốc"], marker="s", linewidth=3, linestyle="--", label="Y có cú sốc")
plt.axvline(2028, linestyle=":", linewidth=2, label="Cú sốc 2028")
plt.title("Tác động cú sốc 2028 đến sản lượng")
plt.xlabel("Năm")
plt.ylabel("Y")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(12,6))
plt.plot(shock_df["Năm"], shock_df["C cơ sở"], marker="o", linewidth=3, label="C cơ sở")
plt.plot(shock_df["Năm"], shock_df["C có cú sốc"], marker="s", linewidth=3, linestyle="--", label="C có cú sốc")
plt.axvline(2028, linestyle=":", linewidth=2, label="Cú sốc 2028")
plt.title("Tác động cú sốc 2028 đến tiêu dùng")
plt.xlabel("Năm")
plt.ylabel("C")
plt.legend()
plt.grid(True)
plt.show()

print(f"""
Welfare cơ sở = {opt_sim["welfare"]:.4f}
Welfare khi có cú sốc = {shock_sim["welfare"]:.4f}
Mức giảm welfare = {shock_sim["welfare"] - opt_sim["welfare"]:.4f}

Nhận xét:
Cú sốc năm 2028 làm giảm sản lượng và tiêu dùng trong năm xảy ra cú sốc.
Do các biến trạng thái K, D, AI, H tích lũy theo thời gian, cú sốc có thể tạo
hiệu ứng lan truyền sang các năm sau thông qua mức đầu tư tuyệt đối thấp hơn.
""")

# ============================================================
# 7. CÂU 8.3.4 — SO SÁNH CHIẾN LƯỢC TRẢI ĐỀU VÀ FRONT-LOAD
# ============================================================

print("""
============================================================
7. CÂU 8.3.4 — SO SÁNH CHIẾN LƯỢC TRẢI ĐỀU VÀ FRONT-LOAD
============================================================
""")

# Chiến lược trải đều
even_shares = np.tile(np.array([0.10, 0.05, 0.04, 0.05]), T)

# Chiến lược front-load: 3 năm đầu đầu tư mạnh, sau đó giảm dần
front_shares = np.zeros((T, 4))

for t in range(T):
    if t <= 2:
        front_shares[t] = np.array([0.16, 0.08, 0.07, 0.07])
    elif t <= 5:
        front_shares[t] = np.array([0.11, 0.05, 0.04, 0.05])
    else:
        front_shares[t] = np.array([0.07, 0.03, 0.02, 0.04])

front_shares = front_shares.flatten()

even_sim = simulate_path(even_shares, shock_2028=False)
front_sim = simulate_path(front_shares, shock_2028=False)

strategy_df = pd.DataFrame({
    "Chiến lược": ["Tối ưu SLSQP", "Đầu tư trải đều", "Đầu tư front-load"],
    "Welfare": [opt_sim["welfare"], even_sim["welfare"], front_sim["welfare"]],
    "Y năm 2035": [opt_sim["Y"][-1], even_sim["Y"][-1], front_sim["Y"][-1]],
    "C năm 2035": [opt_sim["C"][-1], even_sim["C"][-1], front_sim["C"][-1]],
    "K cuối kỳ": [opt_sim["K"][-1], even_sim["K"][-1], front_sim["K"][-1]],
    "D cuối kỳ": [opt_sim["D"][-1], even_sim["D"][-1], front_sim["D"][-1]],
    "AI cuối kỳ": [opt_sim["AI"][-1], even_sim["AI"][-1], front_sim["AI"][-1]],
    "H cuối kỳ": [opt_sim["H"][-1], even_sim["H"][-1], front_sim["H"][-1]]
})

display(strategy_df.round(4))

plt.figure(figsize=(10,5))
plt.bar(strategy_df["Chiến lược"], strategy_df["Welfare"])
plt.title("So sánh tổng welfare giữa các chiến lược")
plt.ylabel("Welfare")
plt.grid(axis="y")
plt.show()

plt.figure(figsize=(12,6))
plt.plot(years, opt_sim["Y"], marker="o", label="Tối ưu SLSQP")
plt.plot(years, even_sim["Y"], marker="s", label="Trải đều")
plt.plot(years, front_sim["Y"], marker="^", label="Front-load")
plt.title("So sánh quỹ đạo sản lượng Y")
plt.xlabel("Năm")
plt.ylabel("Y")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(12,6))
plt.plot(years, opt_sim["C"], marker="o", label="Tối ưu SLSQP")
plt.plot(years, even_sim["C"], marker="s", label="Trải đều")
plt.plot(years, front_sim["C"], marker="^", label="Front-load")
plt.title("So sánh quỹ đạo tiêu dùng C")
plt.xlabel("Năm")
plt.ylabel("C")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# 8. MỞ RỘNG — ẢNH HƯỞNG CỦA HỆ SỐ CHIẾT KHẤU rho
# ============================================================

print("""
============================================================
8. MỞ RỘNG — SO SÁNH rho = 0.97 VÀ rho = 0.90
============================================================
""")

def objective_with_rho(x, rho_value):
    sim = simulate_path(x, shock_2028=False)

    if sim is None:
        return 1e9

    welfare = 0
    for t in range(T):
        if sim["C"][t] <= 0:
            return 1e9
        welfare += (rho_value ** t) * np.log(sim["C"][t])

    return -welfare


res_rho90 = minimize(
    lambda x: objective_with_rho(x, 0.90),
    x0,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints,
    options={
        "maxiter": 2000,
        "ftol": 1e-9,
        "disp": False
    }
)

sim_rho90 = simulate_path(res_rho90.x, shock_2028=False)

rho_compare_df = pd.DataFrame({
    "Năm": years,
    "Tổng đầu tư rho=0.97": opt_sim["I_K"] + opt_sim["I_D"] + opt_sim["I_AI"] + opt_sim["I_H"],
    "Tổng đầu tư rho=0.90": sim_rho90["I_K"] + sim_rho90["I_D"] + sim_rho90["I_AI"] + sim_rho90["I_H"],
    "Tiêu dùng rho=0.97": opt_sim["C"],
    "Tiêu dùng rho=0.90": sim_rho90["C"],
    "Y rho=0.97": opt_sim["Y"],
    "Y rho=0.90": sim_rho90["Y"]
})

display(rho_compare_df.round(4))

plt.figure(figsize=(12,6))
plt.plot(years, rho_compare_df["Tổng đầu tư rho=0.97"], marker="o", label="Tổng đầu tư rho=0.97")
plt.plot(years, rho_compare_df["Tổng đầu tư rho=0.90"], marker="s", label="Tổng đầu tư rho=0.90")
plt.title("So sánh tổng đầu tư khi thay đổi hệ số chiết khấu")
plt.xlabel("Năm")
plt.ylabel("Tổng đầu tư")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
# 9. PHÂN TÍCH CHÍNH SÁCH
# ============================================================

print("""
============================================================
9. PHÂN TÍCH CHÍNH SÁCH
============================================================
""")

total_invest = opt_df[["I_K", "I_D", "I_AI", "I_H"]].sum(axis=1)
first3 = total_invest.iloc[:3].mean()
last3 = total_invest.iloc[-3:].mean()

pattern = "front-loaded" if first3 > last3 else "back-loaded hoặc dàn đều"

ai_h_ratio = opt_df["I_AI"] / (opt_df["I_H"] + 1e-9)

print(f"""
1. Quỹ đạo tối ưu có front-loaded hay không?

Tổng đầu tư trung bình 3 năm đầu = {first3:,.4f}
Tổng đầu tư trung bình 3 năm cuối = {last3:,.4f}

Do đó, quỹ đạo đầu tư tối ưu có xu hướng: {pattern}.

Nếu mô hình front-loaded, điều này phản ánh lợi ích của việc đầu tư sớm vào
K, D, AI và H để các biến trạng thái tích lũy và tạo sản lượng cao hơn trong tương lai.

2. Tỷ lệ đầu tư AI/H có ổn định không?

Tỷ lệ I_AI/I_H trung bình = {ai_h_ratio.mean():.4f}
Tỷ lệ I_AI/I_H nhỏ nhất = {ai_h_ratio.min():.4f}
Tỷ lệ I_AI/I_H lớn nhất = {ai_h_ratio.max():.4f}

Nếu tỷ lệ này biến động, mô hình hàm ý rằng đầu tư AI và đầu tư nhân lực số
không nên được thiết kế cứng nhắc. Trong các giai đoạn đầu, nhân lực số có thể
cần đi trước hoặc đi song song với AI để bảo đảm khả năng hấp thụ công nghệ.

3. Ảnh hưởng của rho

rho = 0.97 phản ánh chính phủ quan tâm mạnh đến phúc lợi dài hạn.
Khi rho giảm xuống 0.90, mô hình có xu hướng coi trọng hiện tại hơn,
do đó thường tăng tiêu dùng hiện tại và giảm động cơ đầu tư dài hạn.

Điều này giúp giải thích vì sao trong thực tế, các chính phủ có thể dưới đầu tư
vào R&D, AI, giáo dục và hạ tầng số: lợi ích của các khoản đầu tư này thường
xuất hiện muộn, trong khi chi phí ngân sách phát sinh ngay.

4. Hàm ý chính sách

Mô hình cho thấy đầu tư liên thời gian không nên chỉ nhìn vào tác động ngắn hạn.
Các khoản đầu tư vào hạ tầng số, AI và nhân lực số có thể có tác động tích lũy,
làm tăng TFP và sản lượng trong dài hạn.

Do đó, Việt Nam cần một chiến lược đầu tư ổn định, có tính cam kết dài hạn,
tránh tình trạng cắt giảm đầu tư vào công nghệ và nhân lực khi gặp áp lực
ngân sách ngắn hạn.
""")

# ============================================================
# 10. KẾT LUẬN
# ============================================================

print("""
============================================================
10. KẾT LUẬN
============================================================

Bài 8 đã xây dựng mô hình tối ưu động cho giai đoạn 2026–2035 nhằm phân bổ
nguồn lực giữa tiêu dùng hiện tại và bốn loại đầu tư: vốn vật chất, hạ tầng số,
AI và vốn nhân lực.

Do hàm sản xuất Cobb-Douglas phi tuyến, bài toán được giải bằng scipy.optimize
với phương pháp SLSQP. Kết quả cho phép mô phỏng quỹ đạo tối ưu của K, D, AI,
H, Y và C theo thời gian.

Phân tích cú sốc năm 2028 cho thấy giảm sản lượng trong một năm có thể ảnh hưởng
đến tiêu dùng và tích lũy trong các năm tiếp theo. So sánh chiến lược đầu tư
trải đều và front-load cho thấy welfare phụ thuộc mạnh vào thời điểm đầu tư,
không chỉ tổng mức đầu tư.

Về mặt chính sách, mô hình nhấn mạnh tầm quan trọng của tầm nhìn dài hạn.
Nếu hệ số chiết khấu thấp, xã hội có xu hướng ưu tiên tiêu dùng hiện tại và
dưới đầu tư cho các yếu tố tạo năng suất dài hạn như R&D, AI, hạ tầng số
và nhân lực chất lượng cao.
""")

